{
  "url": "https://api.github.com/repos/status-im/status-mobile/issues/14013",
  "repository_url": "https://api.github.com/repos/status-im/status-mobile",
  "labels_url": "https://api.github.com/repos/status-im/status-mobile/issues/14013/labels{/name}",
  "comments_url": "https://api.github.com/repos/status-im/status-mobile/issues/14013/comments",
  "events_url": "https://api.github.com/repos/status-im/status-mobile/issues/14013/events",
  "html_url": "https://github.com/status-im/status-mobile/issues/14013",
  "id": 1374613740,
  "node_id": "I_kwDOAx4p2c5R7vDs",
  "number": 14013,
  "title": "Backed up contacts do not appear after account restoration for more that 1 minute (sometimes they don't restore at all)",
  "user": {
    "login": "pavloburykh",
    "id": 97245802,
    "node_id": "U_kgDOBcvaag",
    "avatar_url": "https://avatars.githubusercontent.com/u/97245802?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/pavloburykh",
    "html_url": "https://github.com/pavloburykh",
    "followers_url": "https://api.github.com/users/pavloburykh/followers",
    "following_url": "https://api.github.com/users/pavloburykh/following{/other_user}",
    "gists_url": "https://api.github.com/users/pavloburykh/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/pavloburykh/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/pavloburykh/subscriptions",
    "organizations_url": "https://api.github.com/users/pavloburykh/orgs",
    "repos_url": "https://api.github.com/users/pavloburykh/repos",
    "events_url": "https://api.github.com/users/pavloburykh/events{/privacy}",
    "received_events_url": "https://api.github.com/users/pavloburykh/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [
    {
      "id": 330296931,
      "node_id": "MDU6TGFiZWwzMzAyOTY5MzE=",
      "url": "https://api.github.com/repos/status-im/status-mobile/labels/bug",
      "name": "bug",
      "color": "fc2929",
      "default": true,
      "description": null
    },
    {
      "id": 916015974,
      "node_id": "MDU6TGFiZWw5MTYwMTU5NzQ=",
      "url": "https://api.github.com/repos/status-im/status-mobile/labels/e2e%20test%20blocker",
      "name": "e2e test blocker",
      "color": "bc0753",
      "default": false,
      "description": ""
    },
    {
      "id": 3957916962,
      "node_id": "LA_kwDOAx4p2c7r6QUi",
      "url": "https://api.github.com/repos/status-im/status-mobile/labels/backup",
      "name": "backup",
      "color": "1AAACE",
      "default": false,
      "description": ""
    },
    {
      "id": 3990911030,
      "node_id": "LA_kwDOAx4p2c7t4Hg2",
      "url": "https://api.github.com/repos/status-im/status-mobile/labels/E:Bugfixes",
      "name": "E:Bugfixes",
      "color": "32BD0C",
      "default": false,
      "description": ""
    }
  ],
  "state": "closed",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": {
    "url": "https://api.github.com/repos/status-im/status-mobile/milestones/60",
    "html_url": "https://github.com/status-im/status-mobile/milestone/60",
    "labels_url": "https://api.github.com/repos/status-im/status-mobile/milestones/60/labels",
    "id": 8197709,
    "node_id": "MI_kwDOAx4p2c4AfRZN",
    "number": 60,
    "title": "Release 1.21",
    "description": "",
    "creator": {
      "login": "cammellos",
      "id": 1017008,
      "node_id": "MDQ6VXNlcjEwMTcwMDg=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1017008?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/cammellos",
      "html_url": "https://github.com/cammellos",
      "followers_url": "https://api.github.com/users/cammellos/followers",
      "following_url": "https://api.github.com/users/cammellos/following{/other_user}",
      "gists_url": "https://api.github.com/users/cammellos/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/cammellos/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/cammellos/subscriptions",
      "organizations_url": "https://api.github.com/users/cammellos/orgs",
      "repos_url": "https://api.github.com/users/cammellos/repos",
      "events_url": "https://api.github.com/users/cammellos/events{/privacy}",
      "received_events_url": "https://api.github.com/users/cammellos/received_events",
      "type": "User",
      "site_admin": false
    },
    "open_issues": 8,
    "closed_issues": 18,
    "state": "closed",
    "created_at": "2022-07-15T09:35:16Z",
    "updated_at": "2023-01-26T17:14:14Z",
    "due_on": null,
    "closed_at": "2022-12-02T16:05:58Z"
  },
  "comments": 4,
  "created_at": "2022-09-15T14:22:07Z",
  "updated_at": "2023-01-26T17:14:15Z",
  "closed_at": "2023-01-26T17:14:14Z",
  "author_association": "CONTRIBUTOR",
  "active_lock_reason": null,
  "body": "Sometimes backed up contacts do not appear for more that 1 minute after account has been restored. \r\n\r\nBelow case was caught by e2e tests and demonstrates contacts are not appearing after 120 seconds of waiting for them which has lead to test failure. \r\n\r\nHere you can see a video of test run https://app.saucelabs.com/tests/246fb0f6a48f4046a83997e5a406651b?auth=db55f3c91771580c7439817abd3c9717#64\r\n\r\nLogs of virtual device which caught a bug \r\n[test_group_chat_cant_add_more_twenty_participants_geth.log](https://github.com/status-im/status-mobile/files/9575969/test_group_chat_cant_add_more_twenty_participants_geth.log)\r\n\r\n**Steps** (do not guarantee reproduction)\r\n\r\n1. Restore an account that has backed up contacts\r\n2. Go to Profile tab\r\n3. Pay attention at contacts menu\r\n4. See how much time it will take for contacts to appear\r\n\r\n**Actual result**: sometimes it takes more than 1 minute for contacts to appear\r\n\r\n**Expected result:** we should decide what time period of showing backed up data is acceptable for us. From user perspective it should be at least less that 1 minute. \r\n\r\n### Additional Information\r\n\r\n- Status version: nightly \r\n- Operating System: Android, iOS\r\n\r\n",
  "closed_by": {
    "login": "churik",
    "id": 4557972,
    "node_id": "MDQ6VXNlcjQ1NTc5NzI=",
    "avatar_url": "https://avatars.githubusercontent.com/u/4557972?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/churik",
    "html_url": "https://github.com/churik",
    "followers_url": "https://api.github.com/users/churik/followers",
    "following_url": "https://api.github.com/users/churik/following{/other_user}",
    "gists_url": "https://api.github.com/users/churik/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/churik/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/churik/subscriptions",
    "organizations_url": "https://api.github.com/users/churik/orgs",
    "repos_url": "https://api.github.com/users/churik/repos",
    "events_url": "https://api.github.com/users/churik/events{/privacy}",
    "received_events_url": "https://api.github.com/users/churik/received_events",
    "type": "User",
    "site_admin": false
  },
  "reactions": {
    "url": "https://api.github.com/repos/status-im/status-mobile/issues/14013/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/status-im/status-mobile/issues/14013/timeline",
  "performed_via_github_app": null,
  "state_reason": "completed"
}
[
  {
    "url": "https://api.github.com/repos/status-im/status-mobile/issues/comments/1249361792",
    "html_url": "https://github.com/status-im/status-mobile/issues/14013#issuecomment-1249361792",
    "issue_url": "https://api.github.com/repos/status-im/status-mobile/issues/14013",
    "id": 1249361792,
    "node_id": "IC_kwDOAx4p2c5Kd7-A",
    "user": {
      "login": "churik",
      "id": 4557972,
      "node_id": "MDQ6VXNlcjQ1NTc5NzI=",
      "avatar_url": "https://avatars.githubusercontent.com/u/4557972?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/churik",
      "html_url": "https://github.com/churik",
      "followers_url": "https://api.github.com/users/churik/followers",
      "following_url": "https://api.github.com/users/churik/following{/other_user}",
      "gists_url": "https://api.github.com/users/churik/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/churik/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/churik/subscriptions",
      "organizations_url": "https://api.github.com/users/churik/orgs",
      "repos_url": "https://api.github.com/users/churik/repos",
      "events_url": "https://api.github.com/users/churik/events{/privacy}",
      "received_events_url": "https://api.github.com/users/churik/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-09-16T13:24:14Z",
    "updated_at": "2022-09-16T13:24:14Z",
    "author_association": "MEMBER",
    "body": "Sometimes restoring contacts from backup may take up to 1 hour. Couldn't save a log for this, but it may be an issue and it is sometimes may block our e2e, where timeout for this action is set for 120 sec.\r\n\r\ncc @cammellos ",
    "reactions": {
      "url": "https://api.github.com/repos/status-im/status-mobile/issues/comments/1249361792/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/status-im/status-mobile/issues/comments/1250985762",
    "html_url": "https://github.com/status-im/status-mobile/issues/14013#issuecomment-1250985762",
    "issue_url": "https://api.github.com/repos/status-im/status-mobile/issues/14013",
    "id": 1250985762,
    "node_id": "IC_kwDOAx4p2c5KkIci",
    "user": {
      "login": "churik",
      "id": 4557972,
      "node_id": "MDQ6VXNlcjQ1NTc5NzI=",
      "avatar_url": "https://avatars.githubusercontent.com/u/4557972?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/churik",
      "html_url": "https://github.com/churik",
      "followers_url": "https://api.github.com/users/churik/followers",
      "following_url": "https://api.github.com/users/churik/following{/other_user}",
      "gists_url": "https://api.github.com/users/churik/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/churik/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/churik/subscriptions",
      "organizations_url": "https://api.github.com/users/churik/orgs",
      "repos_url": "https://api.github.com/users/churik/repos",
      "events_url": "https://api.github.com/users/churik/events{/privacy}",
      "received_events_url": "https://api.github.com/users/churik/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-09-19T12:58:12Z",
    "updated_at": "2022-09-19T12:58:12Z",
    "author_association": "MEMBER",
    "body": "When trying to reporoduce issue for upgrade, faced that contacts were not restored at all (waiting > 1h)\r\nLogs (DEBUG): [logs (7).zip](https://github.com/status-im/status-mobile/files/9599055/logs.7.zip)\r\n",
    "reactions": {
      "url": "https://api.github.com/repos/status-im/status-mobile/issues/comments/1250985762/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/status-im/status-mobile/issues/comments/1270089226",
    "html_url": "https://github.com/status-im/status-mobile/issues/14013#issuecomment-1270089226",
    "issue_url": "https://api.github.com/repos/status-im/status-mobile/issues/14013",
    "id": 1270089226,
    "node_id": "IC_kwDOAx4p2c5LtAYK",
    "user": {
      "login": "rasom",
      "id": 2364994,
      "node_id": "MDQ6VXNlcjIzNjQ5OTQ=",
      "avatar_url": "https://avatars.githubusercontent.com/u/2364994?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rasom",
      "html_url": "https://github.com/rasom",
      "followers_url": "https://api.github.com/users/rasom/followers",
      "following_url": "https://api.github.com/users/rasom/following{/other_user}",
      "gists_url": "https://api.github.com/users/rasom/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rasom/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rasom/subscriptions",
      "organizations_url": "https://api.github.com/users/rasom/orgs",
      "repos_url": "https://api.github.com/users/rasom/repos",
      "events_url": "https://api.github.com/users/rasom/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rasom/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-10-06T13:50:51Z",
    "updated_at": "2022-10-06T13:50:51Z",
    "author_association": "MEMBER",
    "body": "Tested locally with my own multipacc, and in the worst cases it took up to 2 minutes due to lack of responses from mail servers and reconnection. \r\n\r\nAlso tested on the multiaccount provided by @churik which was claimed to have around 20 synced contacts in backup. It seems that either backup messages which contained those 20 contacts become outdated or never existed, because fetching of backup works as expected but backup messages do not contain 20 contacts.\r\n\r\n",
    "reactions": {
      "url": "https://api.github.com/repos/status-im/status-mobile/issues/comments/1270089226/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/status-im/status-mobile/issues/comments/1405333096",
    "html_url": "https://github.com/status-im/status-mobile/issues/14013#issuecomment-1405333096",
    "issue_url": "https://api.github.com/repos/status-im/status-mobile/issues/14013",
    "id": 1405333096,
    "node_id": "IC_kwDOAx4p2c5Tw65o",
    "user": {
      "login": "churik",
      "id": 4557972,
      "node_id": "MDQ6VXNlcjQ1NTc5NzI=",
      "avatar_url": "https://avatars.githubusercontent.com/u/4557972?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/churik",
      "html_url": "https://github.com/churik",
      "followers_url": "https://api.github.com/users/churik/followers",
      "following_url": "https://api.github.com/users/churik/following{/other_user}",
      "gists_url": "https://api.github.com/users/churik/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/churik/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/churik/subscriptions",
      "organizations_url": "https://api.github.com/users/churik/orgs",
      "repos_url": "https://api.github.com/users/churik/repos",
      "events_url": "https://api.github.com/users/churik/events{/privacy}",
      "received_events_url": "https://api.github.com/users/churik/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2023-01-26T17:14:14Z",
    "updated_at": "2023-01-26T17:14:14Z",
    "author_association": "MEMBER",
    "body": "don't think it is still relevant, closing",
    "reactions": {
      "url": "https://api.github.com/repos/status-im/status-mobile/issues/comments/1405333096/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  }
]
