{
  "url": "https://api.github.com/repos/status-im/status-mobile/issues/9269",
  "repository_url": "https://api.github.com/repos/status-im/status-mobile",
  "labels_url": "https://api.github.com/repos/status-im/status-mobile/issues/9269/labels{/name}",
  "comments_url": "https://api.github.com/repos/status-im/status-mobile/issues/9269/comments",
  "events_url": "https://api.github.com/repos/status-im/status-mobile/issues/9269/events",
  "html_url": "https://github.com/status-im/status-mobile/issues/9269",
  "id": 511330736,
  "node_id": "MDU6SXNzdWU1MTEzMzA3MzY=",
  "number": 9269,
  "title": "Often 'Could not connect to mailserver' when unstable connection and pinned mailserver",
  "user": {
    "login": "Serhy",
    "id": 8749671,
    "node_id": "MDQ6VXNlcjg3NDk2NzE=",
    "avatar_url": "https://avatars.githubusercontent.com/u/8749671?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Serhy",
    "html_url": "https://github.com/Serhy",
    "followers_url": "https://api.github.com/users/Serhy/followers",
    "following_url": "https://api.github.com/users/Serhy/following{/other_user}",
    "gists_url": "https://api.github.com/users/Serhy/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Serhy/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Serhy/subscriptions",
    "organizations_url": "https://api.github.com/users/Serhy/orgs",
    "repos_url": "https://api.github.com/users/Serhy/repos",
    "events_url": "https://api.github.com/users/Serhy/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Serhy/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [
    {
      "id": 330296931,
      "node_id": "MDU6TGFiZWwzMzAyOTY5MzE=",
      "url": "https://api.github.com/repos/status-im/status-mobile/labels/bug",
      "name": "bug",
      "color": "fc2929",
      "default": true,
      "description": null
    }
  ],
  "state": "closed",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 4,
  "created_at": "2019-10-23T13:39:21Z",
  "updated_at": "2020-09-17T11:07:57Z",
  "closed_at": "2020-09-17T10:58:17Z",
  "author_association": "CONTRIBUTOR",
  "active_lock_reason": null,
  "body": "# Bug Report\n\n## Problem\nWhen connection is not stable it's not rare case to see 'Could not connect to mailserver'. There are different scenarios but all of them has the same root cause: when trying to connect to the same mailsever in a short period of time (not sure exact value but < 10s for sure) the 'Could not connect to mailserver' appears. See below user scenarios:\n\n**Usecase#1:** \nUser has unstable WiFi connection and mobile data enabled. And account has pinned mailsever. \nIn that case we have often switch of the network WiFi <-> 3G/4G which ends in attempt to connect to the same mailserver\n\n**Usecase#2:** \nUser has pinned mailserver. And at some point connection lost. The 'Could not connect to mailserver' appeared with 'Retry' option. User taps 'Retry' and gets  'Could not connect to mailserver' again. Taps 'Retry' and again ->  'Could not connect to mailserver'. It is happened because same mailserver has attempted to connect.\n\n \n\n#### Expected behavior\nConnecting to the same mailsever in less than 10 seconds establishes connection without  'Could not connect to mailserver'\n\n#### Actual behavior\nConnecting to the same mailserver in less than 10 seconds fails with the following 'Could not connect to mailserver' pop-up \n\n![2019_10_23_16_09_03](https://user-images.githubusercontent.com/8749671/67396321-08ab3d00-f5b0-11e9-96ab-146e6f7b71c1.gif)\n\n### Reproduction is simple\n\n- Open Status and create new account\n- Navigate to `Profile` -> `Sync Settings` -> `Mailserver`\n- Uncheck `Automatic selection`\n- Tap upon mailserver you are connected to now \n\n### Additional Information\n\n[comment]: # (Please do your best to fill this out.)\n- Status version: develop `0.14.0 (2019102115)`\n- Operating System: Android and iOS\n\n#### Logs\n\nLogcat with error when same mailserver connected: \n[logcat_tap_to_connect_twice.log](https://github.com/status-im/status-react/files/3762612/Log_Tap_to_connect_twice.log)",
  "closed_by": {
    "login": "cammellos",
    "id": 1017008,
    "node_id": "MDQ6VXNlcjEwMTcwMDg=",
    "avatar_url": "https://avatars.githubusercontent.com/u/1017008?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/cammellos",
    "html_url": "https://github.com/cammellos",
    "followers_url": "https://api.github.com/users/cammellos/followers",
    "following_url": "https://api.github.com/users/cammellos/following{/other_user}",
    "gists_url": "https://api.github.com/users/cammellos/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/cammellos/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/cammellos/subscriptions",
    "organizations_url": "https://api.github.com/users/cammellos/orgs",
    "repos_url": "https://api.github.com/users/cammellos/repos",
    "events_url": "https://api.github.com/users/cammellos/events{/privacy}",
    "received_events_url": "https://api.github.com/users/cammellos/received_events",
    "type": "User",
    "site_admin": false
  },
  "reactions": {
    "url": "https://api.github.com/repos/status-im/status-mobile/issues/9269/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/status-im/status-mobile/issues/9269/timeline",
  "performed_via_github_app": null,
  "state_reason": "completed"
}
[
  {
    "url": "https://api.github.com/repos/status-im/status-mobile/issues/comments/545449553",
    "html_url": "https://github.com/status-im/status-mobile/issues/9269#issuecomment-545449553",
    "issue_url": "https://api.github.com/repos/status-im/status-mobile/issues/9269",
    "id": 545449553,
    "node_id": "MDEyOklzc3VlQ29tbWVudDU0NTQ0OTU1Mw==",
    "user": {
      "login": "Serhy",
      "id": 8749671,
      "node_id": "MDQ6VXNlcjg3NDk2NzE=",
      "avatar_url": "https://avatars.githubusercontent.com/u/8749671?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Serhy",
      "html_url": "https://github.com/Serhy",
      "followers_url": "https://api.github.com/users/Serhy/followers",
      "following_url": "https://api.github.com/users/Serhy/following{/other_user}",
      "gists_url": "https://api.github.com/users/Serhy/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Serhy/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Serhy/subscriptions",
      "organizations_url": "https://api.github.com/users/Serhy/orgs",
      "repos_url": "https://api.github.com/users/Serhy/repos",
      "events_url": "https://api.github.com/users/Serhy/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Serhy/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-10-23T13:41:19Z",
    "updated_at": "2019-10-23T13:41:19Z",
    "author_association": "CONTRIBUTOR",
    "body": "@rachelhamlin I would like to include it in V1-scope. Fix of this issue should increase UX by not alarming with 'Could not connect to mailserver' for those who use pinned mailservers. ",
    "reactions": {
      "url": "https://api.github.com/repos/status-im/status-mobile/issues/comments/545449553/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/status-im/status-mobile/issues/comments/616603262",
    "html_url": "https://github.com/status-im/status-mobile/issues/9269#issuecomment-616603262",
    "issue_url": "https://api.github.com/repos/status-im/status-mobile/issues/9269",
    "id": 616603262,
    "node_id": "MDEyOklzc3VlQ29tbWVudDYxNjYwMzI2Mg==",
    "user": {
      "login": "andremedeiros",
      "id": 9689,
      "node_id": "MDQ6VXNlcjk2ODk=",
      "avatar_url": "https://avatars.githubusercontent.com/u/9689?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/andremedeiros",
      "html_url": "https://github.com/andremedeiros",
      "followers_url": "https://api.github.com/users/andremedeiros/followers",
      "following_url": "https://api.github.com/users/andremedeiros/following{/other_user}",
      "gists_url": "https://api.github.com/users/andremedeiros/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/andremedeiros/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/andremedeiros/subscriptions",
      "organizations_url": "https://api.github.com/users/andremedeiros/orgs",
      "repos_url": "https://api.github.com/users/andremedeiros/repos",
      "events_url": "https://api.github.com/users/andremedeiros/events{/privacy}",
      "received_events_url": "https://api.github.com/users/andremedeiros/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2020-04-20T14:49:26Z",
    "updated_at": "2020-04-20T14:49:26Z",
    "author_association": "CONTRIBUTOR",
    "body": "@cammellos @Serhy sounds like this one can be closed. Is that right?",
    "reactions": {
      "url": "https://api.github.com/repos/status-im/status-mobile/issues/comments/616603262/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/status-im/status-mobile/issues/comments/617024328",
    "html_url": "https://github.com/status-im/status-mobile/issues/9269#issuecomment-617024328",
    "issue_url": "https://api.github.com/repos/status-im/status-mobile/issues/9269",
    "id": 617024328,
    "node_id": "MDEyOklzc3VlQ29tbWVudDYxNzAyNDMyOA==",
    "user": {
      "login": "Serhy",
      "id": 8749671,
      "node_id": "MDQ6VXNlcjg3NDk2NzE=",
      "avatar_url": "https://avatars.githubusercontent.com/u/8749671?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Serhy",
      "html_url": "https://github.com/Serhy",
      "followers_url": "https://api.github.com/users/Serhy/followers",
      "following_url": "https://api.github.com/users/Serhy/following{/other_user}",
      "gists_url": "https://api.github.com/users/Serhy/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Serhy/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Serhy/subscriptions",
      "organizations_url": "https://api.github.com/users/Serhy/orgs",
      "repos_url": "https://api.github.com/users/Serhy/repos",
      "events_url": "https://api.github.com/users/Serhy/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Serhy/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2020-04-21T08:08:33Z",
    "updated_at": "2020-04-21T08:08:33Z",
    "author_association": "CONTRIBUTOR",
    "body": "Mm, i'd actually be glad if we look at it. \r\n\r\nSo the `Reproduction` there in description is just to show how to reproduce the issue. And it still reproducible. \r\nAnd so consequences of connecting to same mailserver in less than 10 sec may still be on place.",
    "reactions": {
      "url": "https://api.github.com/repos/status-im/status-mobile/issues/comments/617024328/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/status-im/status-mobile/issues/comments/617026207",
    "html_url": "https://github.com/status-im/status-mobile/issues/9269#issuecomment-617026207",
    "issue_url": "https://api.github.com/repos/status-im/status-mobile/issues/9269",
    "id": 617026207,
    "node_id": "MDEyOklzc3VlQ29tbWVudDYxNzAyNjIwNw==",
    "user": {
      "login": "cammellos",
      "id": 1017008,
      "node_id": "MDQ6VXNlcjEwMTcwMDg=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1017008?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/cammellos",
      "html_url": "https://github.com/cammellos",
      "followers_url": "https://api.github.com/users/cammellos/followers",
      "following_url": "https://api.github.com/users/cammellos/following{/other_user}",
      "gists_url": "https://api.github.com/users/cammellos/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/cammellos/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/cammellos/subscriptions",
      "organizations_url": "https://api.github.com/users/cammellos/orgs",
      "repos_url": "https://api.github.com/users/cammellos/repos",
      "events_url": "https://api.github.com/users/cammellos/events{/privacy}",
      "received_events_url": "https://api.github.com/users/cammellos/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2020-04-21T08:12:29Z",
    "updated_at": "2020-04-21T08:12:29Z",
    "author_association": "MEMBER",
    "body": "Yes, I think we should keep this open for now, as we haven't done any work with that regard",
    "reactions": {
      "url": "https://api.github.com/repos/status-im/status-mobile/issues/comments/617026207/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  }
]
