{
  "url": "https://api.github.com/repos/sigp/lighthouse/issues/2858",
  "repository_url": "https://api.github.com/repos/sigp/lighthouse",
  "labels_url": "https://api.github.com/repos/sigp/lighthouse/issues/2858/labels{/name}",
  "comments_url": "https://api.github.com/repos/sigp/lighthouse/issues/2858/comments",
  "events_url": "https://api.github.com/repos/sigp/lighthouse/issues/2858/events",
  "html_url": "https://github.com/sigp/lighthouse/issues/2858",
  "id": 1073360249,
  "node_id": "I_kwDOCFeAzc4_-i15",
  "number": 2858,
  "title": "InsufficientPeers resulting in missing sync commitees",
  "user": {
    "login": "fkbenjamin",
    "id": 7634997,
    "node_id": "MDQ6VXNlcjc2MzQ5OTc=",
    "avatar_url": "https://avatars.githubusercontent.com/u/7634997?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/fkbenjamin",
    "html_url": "https://github.com/fkbenjamin",
    "followers_url": "https://api.github.com/users/fkbenjamin/followers",
    "following_url": "https://api.github.com/users/fkbenjamin/following{/other_user}",
    "gists_url": "https://api.github.com/users/fkbenjamin/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/fkbenjamin/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/fkbenjamin/subscriptions",
    "organizations_url": "https://api.github.com/users/fkbenjamin/orgs",
    "repos_url": "https://api.github.com/users/fkbenjamin/repos",
    "events_url": "https://api.github.com/users/fkbenjamin/events{/privacy}",
    "received_events_url": "https://api.github.com/users/fkbenjamin/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [
    {
      "id": 985647281,
      "node_id": "MDU6TGFiZWw5ODU2NDcyODE=",
      "url": "https://api.github.com/repos/sigp/lighthouse/labels/bug",
      "name": "bug",
      "color": "d73a4a",
      "default": true,
      "description": "Something isn't working"
    }
  ],
  "state": "closed",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 20,
  "created_at": "2021-12-07T13:34:57Z",
  "updated_at": "2022-09-07T23:22:48Z",
  "closed_at": "2022-09-07T23:22:48Z",
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "## Description\r\n\r\nOur lighthouse nodes occasionally start to miss attestations and today also missed sync committees. Looking at the beaconchain node logs, it seems that it has issues with publishing these messages because of  Insufficient Peers, despite being connected to 50+ peers. Restarting the node solves the issue.\r\n\r\n## Version\r\n\r\nLighthouse v2.0.1 \r\n(using vouch as the validator client)\r\n\r\n## Present Behaviour\r\n\r\nDescribe the present behaviour of the application, with regards to this\r\nissue.\r\n\r\n```\r\nDec 07 13:30:41 lhs-val01 lighthouse[997]: Dec 07 13:30:41.000 INFO Synced                                  slot: 2671351, block: 0xb807…9b44, epoch: 83479, finalized_epoch: 83477, finalized_root: 0x0e20…8ae0, peers: 55, service: slot_notifier\r\nDec 07 13:30:49 lhs-val01 lighthouse[997]: Dec 07 13:30:49.652 INFO New block received                      hash: 0x81272318e6771c48a8cdd656255c1c61afd45d9a6cc5d037d28059235600e05e, slot: 2671352\r\nDec 07 13:30:50 lhs-val01 lighthouse[997]: Dec 07 13:30:50.467 WARN Could not publish message               error: InsufficientPeers, service: libp2p\r\nDec 07 13:30:51 lhs-val01 lighthouse[997]: Dec 07 13:30:51.487 WARN Could not publish message               error: InsufficientPeers, service: libp2p\r\nDec 07 13:30:51 lhs-val01 lighthouse[997]: Dec 07 13:30:51.490 WARN Could not publish message               error: InsufficientPeers, service: libp2p\r\nDec 07 13:30:51 lhs-val01 lighthouse[997]: Dec 07 13:30:51.491 WARN Could not publish message               error: InsufficientPeers, service: libp2p\r\n```\r\n\r\n## Steps to resolve\r\n\r\nRestarting the beaconchain node usually resolves the issue.",
  "closed_by": {
    "login": "AgeManning",
    "id": 7454587,
    "node_id": "MDQ6VXNlcjc0NTQ1ODc=",
    "avatar_url": "https://avatars.githubusercontent.com/u/7454587?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/AgeManning",
    "html_url": "https://github.com/AgeManning",
    "followers_url": "https://api.github.com/users/AgeManning/followers",
    "following_url": "https://api.github.com/users/AgeManning/following{/other_user}",
    "gists_url": "https://api.github.com/users/AgeManning/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/AgeManning/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/AgeManning/subscriptions",
    "organizations_url": "https://api.github.com/users/AgeManning/orgs",
    "repos_url": "https://api.github.com/users/AgeManning/repos",
    "events_url": "https://api.github.com/users/AgeManning/events{/privacy}",
    "received_events_url": "https://api.github.com/users/AgeManning/received_events",
    "type": "User",
    "site_admin": false
  },
  "reactions": {
    "url": "https://api.github.com/repos/sigp/lighthouse/issues/2858/reactions",
    "total_count": 4,
    "+1": 2,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 2
  },
  "timeline_url": "https://api.github.com/repos/sigp/lighthouse/issues/2858/timeline",
  "performed_via_github_app": null,
  "state_reason": "completed"
}
[
  {
    "url": "https://api.github.com/repos/sigp/lighthouse/issues/comments/993057081",
    "html_url": "https://github.com/sigp/lighthouse/issues/2858#issuecomment-993057081",
    "issue_url": "https://api.github.com/repos/sigp/lighthouse/issues/2858",
    "id": 993057081,
    "node_id": "IC_kwDOCFeAzc47MNk5",
    "user": {
      "login": "paulhauner",
      "id": 6660660,
      "node_id": "MDQ6VXNlcjY2NjA2NjA=",
      "avatar_url": "https://avatars.githubusercontent.com/u/6660660?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/paulhauner",
      "html_url": "https://github.com/paulhauner",
      "followers_url": "https://api.github.com/users/paulhauner/followers",
      "following_url": "https://api.github.com/users/paulhauner/following{/other_user}",
      "gists_url": "https://api.github.com/users/paulhauner/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/paulhauner/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/paulhauner/subscriptions",
      "organizations_url": "https://api.github.com/users/paulhauner/orgs",
      "repos_url": "https://api.github.com/users/paulhauner/repos",
      "events_url": "https://api.github.com/users/paulhauner/events{/privacy}",
      "received_events_url": "https://api.github.com/users/paulhauner/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2021-12-14T01:01:21Z",
    "updated_at": "2021-12-14T01:01:21Z",
    "author_association": "MEMBER",
    "body": "Thanks for reporting @fkbenjamin. There are some networking-wide issues with maintaining a healthy count of sync-committee peers at present. There are nascent talks about modifying the spec to increase the number of nodes which are required to connect to sync committees.\r\n\r\nI'll leave this open so we can track the issue in Lighthouse specifically.",
    "reactions": {
      "url": "https://api.github.com/repos/sigp/lighthouse/issues/comments/993057081/reactions",
      "total_count": 2,
      "+1": 2,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/sigp/lighthouse/issues/comments/999700240",
    "html_url": "https://github.com/sigp/lighthouse/issues/2858#issuecomment-999700240",
    "issue_url": "https://api.github.com/repos/sigp/lighthouse/issues/2858",
    "id": 999700240,
    "node_id": "IC_kwDOCFeAzc47ljcQ",
    "user": {
      "login": "mnguyen-io",
      "id": 16768116,
      "node_id": "MDQ6VXNlcjE2NzY4MTE2",
      "avatar_url": "https://avatars.githubusercontent.com/u/16768116?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mnguyen-io",
      "html_url": "https://github.com/mnguyen-io",
      "followers_url": "https://api.github.com/users/mnguyen-io/followers",
      "following_url": "https://api.github.com/users/mnguyen-io/following{/other_user}",
      "gists_url": "https://api.github.com/users/mnguyen-io/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mnguyen-io/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mnguyen-io/subscriptions",
      "organizations_url": "https://api.github.com/users/mnguyen-io/orgs",
      "repos_url": "https://api.github.com/users/mnguyen-io/repos",
      "events_url": "https://api.github.com/users/mnguyen-io/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mnguyen-io/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2021-12-22T16:18:56Z",
    "updated_at": "2021-12-22T16:20:13Z",
    "author_association": "NONE",
    "body": "We're also seeing similar issues.  We're using lighthouse as the VC\r\n\r\nRestarting beacon node fixes it:\r\n\r\n```\r\nDec 22 09:17:03 eth2-combo-bhs--mainnet--4 lighthouse[17274]: Dec 22 09:17:03.726 DEBG Sending pubsub messages                 topics: [Attestation(SubnetId(37))], count: 1, service: network\r\nDec 22 09:17:03 eth2-combo-bhs--mainnet--4 lighthouse[17274]: Dec 22 09:17:03.727 INFO Unaggregated attestation                validator: XXXXXX, src: api, slot: 2778383, epoch: 86824, delay_ms: 725, index: 4, head: 0xd1df7d0963ab48900eeedd7faf15e95d3b20f0577f8d64f6608a9b788bb9decb, service: val_mon\r\nDec 22 09:17:03 eth2-combo-bhs--mainnet--4 lighthouse[17274]: Dec 22 09:17:03.728 INFO Unaggregated attestation                validator: XXXXXX, src: api, slot: 2778383, epoch: 86824, delay_ms: 725, index: 4, head: 0xd1df7d0963ab48900eeedd7faf15e95d3b20f0577f8d64f6608a9b788bb9decb, service: val_mon\r\nDec 22 09:17:03 eth2-combo-bhs--mainnet--4 lighthouse[17274]: Dec 22 09:17:03.728 DEBG Processed HTTP API request              method: POST, path: /eth/v1/beacon/pool/attestations, status: 200 OK, elapsed: 3.356549ms\r\nDec 22 09:17:03 eth2-combo-bhs--mainnet--4 lighthouse[17274]: Dec 22 09:17:03.729 DEBG Sending pubsub messages                 topics: [SyncCommitteeMessage(SyncSubnetId(2))], count: 1, service: network\r\nDec 22 09:17:03 eth2-combo-bhs--mainnet--4 lighthouse[17274]: Dec 22 09:17:03.730 WARN Could not publish message               error: InsufficientPeers, service: libp2p\r\nDec 22 09:17:03 eth2-combo-bhs--mainnet--4 lighthouse[17274]: Dec 22 09:17:03.730 DEBG Sending pubsub messages                 topics: [Attestation(SubnetId(30))], count: 1, service: network\r\nDec 22 09:17:03 eth2-combo-bhs--mainnet--4 lighthouse[17274]: Dec 22 09:17:03.730 DEBG Sending pubsub messages                 topics: [SyncCommitteeMessage(SyncSubnetId(1))], count: 1, service: network\r\nDec 22 09:17:03 eth2-combo-bhs--mainnet--4 lighthouse[17274]: Dec 22 09:17:03.730 DEBG Sending pubsub messages                 topics: [SyncCommitteeMessage(SyncSubnetId(2))], count: 1, service: network\r\nDec 22 09:17:03 eth2-combo-bhs--mainnet--4 lighthouse[17274]: Dec 22 09:17:03.730 WARN Could not publish message               error: InsufficientPeers, service: libp2p\r\n```",
    "reactions": {
      "url": "https://api.github.com/repos/sigp/lighthouse/issues/comments/999700240/reactions",
      "total_count": 1,
      "+1": 1,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/sigp/lighthouse/issues/comments/1004089499",
    "html_url": "https://github.com/sigp/lighthouse/issues/2858#issuecomment-1004089499",
    "issue_url": "https://api.github.com/repos/sigp/lighthouse/issues/2858",
    "id": 1004089499,
    "node_id": "IC_kwDOCFeAzc472TCb",
    "user": {
      "login": "1swaraj",
      "id": 36474630,
      "node_id": "MDQ6VXNlcjM2NDc0NjMw",
      "avatar_url": "https://avatars.githubusercontent.com/u/36474630?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/1swaraj",
      "html_url": "https://github.com/1swaraj",
      "followers_url": "https://api.github.com/users/1swaraj/followers",
      "following_url": "https://api.github.com/users/1swaraj/following{/other_user}",
      "gists_url": "https://api.github.com/users/1swaraj/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/1swaraj/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/1swaraj/subscriptions",
      "organizations_url": "https://api.github.com/users/1swaraj/orgs",
      "repos_url": "https://api.github.com/users/1swaraj/repos",
      "events_url": "https://api.github.com/users/1swaraj/events{/privacy}",
      "received_events_url": "https://api.github.com/users/1swaraj/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-01-03T13:23:52Z",
    "updated_at": "2022-01-03T13:23:52Z",
    "author_association": "NONE",
    "body": "Our lighthouse consensus clients keeps disconnecting from peers and after a few minutes starts throwing these errors :-\r\nWARN Could not publish message error: InsufficientPeers, service: libp2p\r\nWe are running multiple lighthouse nodes on the xdai network ( now gnosis ) and it happens with almost all of them\r\nRestarting solves the issue for a few minutes but it usually presists",
    "reactions": {
      "url": "https://api.github.com/repos/sigp/lighthouse/issues/comments/1004089499/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/sigp/lighthouse/issues/comments/1004406948",
    "html_url": "https://github.com/sigp/lighthouse/issues/2858#issuecomment-1004406948",
    "issue_url": "https://api.github.com/repos/sigp/lighthouse/issues/2858",
    "id": 1004406948,
    "node_id": "IC_kwDOCFeAzc473gik",
    "user": {
      "login": "michaelsproul",
      "id": 4452260,
      "node_id": "MDQ6VXNlcjQ0NTIyNjA=",
      "avatar_url": "https://avatars.githubusercontent.com/u/4452260?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/michaelsproul",
      "html_url": "https://github.com/michaelsproul",
      "followers_url": "https://api.github.com/users/michaelsproul/followers",
      "following_url": "https://api.github.com/users/michaelsproul/following{/other_user}",
      "gists_url": "https://api.github.com/users/michaelsproul/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/michaelsproul/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/michaelsproul/subscriptions",
      "organizations_url": "https://api.github.com/users/michaelsproul/orgs",
      "repos_url": "https://api.github.com/users/michaelsproul/repos",
      "events_url": "https://api.github.com/users/michaelsproul/events{/privacy}",
      "received_events_url": "https://api.github.com/users/michaelsproul/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-01-03T22:42:56Z",
    "updated_at": "2022-01-03T22:42:56Z",
    "author_association": "MEMBER",
    "body": "> We are running multiple lighthouse nodes on the xdai network ( now gnosis ) and it happens with almost all of them\n\nWhich commit are you running? One of the issues causing mass banning was late sync committee messages, which we've reduced the penalty for in `unstable`.",
    "reactions": {
      "url": "https://api.github.com/repos/sigp/lighthouse/issues/comments/1004406948/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/sigp/lighthouse/issues/comments/1006121988",
    "html_url": "https://github.com/sigp/lighthouse/issues/2858#issuecomment-1006121988",
    "issue_url": "https://api.github.com/repos/sigp/lighthouse/issues/2858",
    "id": 1006121988,
    "node_id": "IC_kwDOCFeAzc47-DQE",
    "user": {
      "login": "mieubrisse",
      "id": 1142185,
      "node_id": "MDQ6VXNlcjExNDIxODU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1142185?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mieubrisse",
      "html_url": "https://github.com/mieubrisse",
      "followers_url": "https://api.github.com/users/mieubrisse/followers",
      "following_url": "https://api.github.com/users/mieubrisse/following{/other_user}",
      "gists_url": "https://api.github.com/users/mieubrisse/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mieubrisse/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mieubrisse/subscriptions",
      "organizations_url": "https://api.github.com/users/mieubrisse/orgs",
      "repos_url": "https://api.github.com/users/mieubrisse/repos",
      "events_url": "https://api.github.com/users/mieubrisse/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mieubrisse/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-01-05T22:17:15Z",
    "updated_at": "2022-01-05T22:23:37Z",
    "author_association": "NONE",
    "body": "We're seeing the same problem trying to run Lighthouse in a localnet (2 Geth nodes, 1 Nimbus node, 1 Lighthouse node). The Beacon node spams the same \"InsufficientPeers\" output as above:\r\n```\r\nJan 05 22:15:50.003 WARN Could not publish message               error: InsufficientPeers, service: libp2p\r\nJan 05 22:15:50.016 WARN Could not publish message               error: InsufficientPeers, service: libp2p\r\nJan 05 22:15:50.039 WARN Could not publish message               error: InsufficientPeers, service: libp2p\r\nJan 05 22:15:50.047 WARN Could not publish message               error: InsufficientPeers, service: libp2p\r\nJan 05 22:15:53.967 WARN Producing block that conflicts with head, slot: 113, message: this block is more likely to be orphaned, service: beacon\r\nJan 05 22:15:54.019 ERRO No valid eth1_data votes, `votes_to_consider` empty, outcome: casting `state.eth1_data` as eth1 vote, genesis_time: 1641419586, earliest_block_timestamp: 1641419586, lowest_block_number: 0, service: eth1_rpc\r\nJan 05 22:15:54.062 WARN Could not publish message               error: InsufficientPeers, service: libp2p\r\nJan 05 22:15:54.085 INFO Valid block from HTTP API               slot: 114, proposer_index: 83, root: 0x2558…4667, block_delay: 59.949ms\r\nJan 05 22:15:54.148 ERRO No valid eth1_data votes, `votes_to_consider` empty, outcome: casting `state.eth1_data` as eth1 vote, genesis_time: 1641419586, earliest_block_timestamp: 1641419586, lowest_block_number: 0, service: eth1_rpc\r\nJan 05 22:15:58.025 WARN Could not publish message               error: InsufficientPeers, service: libp2p\r\nJan 05 22:15:58.032 WARN Could not publish message               error: InsufficientPeers, service: libp2p\r\nJan 05 22:15:58.046 WARN Could not publish message               error: InsufficientPeers, service: libp2p\r\nJan 05 22:15:58.052 WARN Could not publish message               error: InsufficientPeers, service: libp2p\r\nJan 05 22:15:58.055 WARN Could not publish message               error: InsufficientPeers, service: libp2p\r\nJan 05 22:15:58.056 WARN Could not publish message               error: InsufficientPeers, service: libp2p\r\nJan 05 22:15:58.062 WARN Could not publish message               error: InsufficientPeers, service: libp2p\r\nJan 05 22:15:58.073 WARN Could not publish message               error: InsufficientPeers, service: libp2p\r\nJan 05 22:15:58.078 WARN Could not publish message               error: InsufficientPeers, service: libp2p\r\nJan 05 22:15:58.085 WARN Could not publish message               error: InsufficientPeers, service: libp2p\r\n```\r\n\r\nOf note: the Lighthouse Beacon node is in fact peered with the Nimbus Beacon node:\r\n```\r\nJan 05 22:22:34.118 WARN Could not publish message               error: InsufficientPeers, service: libp2p\r\nJan 05 22:22:34.121 WARN Could not publish message               error: InsufficientPeers, service: libp2p\r\nJan 05 22:22:34.122 WARN Low peer count                          peer_count: 1, service: slot_notifier\r\nJan 05 22:22:34.122 INFO Synced                                  slot: 147, block:    …  empty, epoch: 4, finalized_epoch: 1, finalized_root: 0xe595…4e9b, exec_hash: 0xd496…2200 (verified), peers: 1, service: slot_notifier\r\nJan 05 22:22:34.125 WARN Could not publish message               error: InsufficientPeers, service: libp2p\r\nJan 05 22:22:34.128 WARN Could not publish message               error: InsufficientPeers, service: libp2p\r\nJan 05 22:22:34.131 WARN Could not publish message               error: InsufficientPeers, service: libp2p\r\n```",
    "reactions": {
      "url": "https://api.github.com/repos/sigp/lighthouse/issues/comments/1006121988/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/sigp/lighthouse/issues/comments/1006322597",
    "html_url": "https://github.com/sigp/lighthouse/issues/2858#issuecomment-1006322597",
    "issue_url": "https://api.github.com/repos/sigp/lighthouse/issues/2858",
    "id": 1006322597,
    "node_id": "IC_kwDOCFeAzc47-0Ol",
    "user": {
      "login": "pawanjay176",
      "id": 9890508,
      "node_id": "MDQ6VXNlcjk4OTA1MDg=",
      "avatar_url": "https://avatars.githubusercontent.com/u/9890508?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/pawanjay176",
      "html_url": "https://github.com/pawanjay176",
      "followers_url": "https://api.github.com/users/pawanjay176/followers",
      "following_url": "https://api.github.com/users/pawanjay176/following{/other_user}",
      "gists_url": "https://api.github.com/users/pawanjay176/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/pawanjay176/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/pawanjay176/subscriptions",
      "organizations_url": "https://api.github.com/users/pawanjay176/orgs",
      "repos_url": "https://api.github.com/users/pawanjay176/repos",
      "events_url": "https://api.github.com/users/pawanjay176/events{/privacy}",
      "received_events_url": "https://api.github.com/users/pawanjay176/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-01-06T06:41:25Z",
    "updated_at": "2022-01-06T06:41:25Z",
    "author_association": "MEMBER",
    "body": "@mieubrisse Assuming it's a `SyncCommittee` message that couldn't get published, is your nimbus node subscribed to the required sync committee subnets? debug logs would be helpful if you have them.",
    "reactions": {
      "url": "https://api.github.com/repos/sigp/lighthouse/issues/comments/1006322597/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/sigp/lighthouse/issues/comments/1014262262",
    "html_url": "https://github.com/sigp/lighthouse/issues/2858#issuecomment-1014262262",
    "issue_url": "https://api.github.com/repos/sigp/lighthouse/issues/2858",
    "id": 1014262262,
    "node_id": "IC_kwDOCFeAzc48dGn2",
    "user": {
      "login": "AgeManning",
      "id": 7454587,
      "node_id": "MDQ6VXNlcjc0NTQ1ODc=",
      "avatar_url": "https://avatars.githubusercontent.com/u/7454587?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/AgeManning",
      "html_url": "https://github.com/AgeManning",
      "followers_url": "https://api.github.com/users/AgeManning/followers",
      "following_url": "https://api.github.com/users/AgeManning/following{/other_user}",
      "gists_url": "https://api.github.com/users/AgeManning/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/AgeManning/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/AgeManning/subscriptions",
      "organizations_url": "https://api.github.com/users/AgeManning/orgs",
      "repos_url": "https://api.github.com/users/AgeManning/repos",
      "events_url": "https://api.github.com/users/AgeManning/events{/privacy}",
      "received_events_url": "https://api.github.com/users/AgeManning/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-01-17T08:33:36Z",
    "updated_at": "2022-01-17T08:33:36Z",
    "author_association": "MEMBER",
    "body": "A full set of debug logs would be nice (especially if this is a recurring issue). 10-30 mins prior to the warning would be great.",
    "reactions": {
      "url": "https://api.github.com/repos/sigp/lighthouse/issues/comments/1014262262/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/sigp/lighthouse/issues/comments/1014792997",
    "html_url": "https://github.com/sigp/lighthouse/issues/2858#issuecomment-1014792997",
    "issue_url": "https://api.github.com/repos/sigp/lighthouse/issues/2858",
    "id": 1014792997,
    "node_id": "IC_kwDOCFeAzc48fIMl",
    "user": {
      "login": "mnguyen-io",
      "id": 16768116,
      "node_id": "MDQ6VXNlcjE2NzY4MTE2",
      "avatar_url": "https://avatars.githubusercontent.com/u/16768116?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mnguyen-io",
      "html_url": "https://github.com/mnguyen-io",
      "followers_url": "https://api.github.com/users/mnguyen-io/followers",
      "following_url": "https://api.github.com/users/mnguyen-io/following{/other_user}",
      "gists_url": "https://api.github.com/users/mnguyen-io/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mnguyen-io/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mnguyen-io/subscriptions",
      "organizations_url": "https://api.github.com/users/mnguyen-io/orgs",
      "repos_url": "https://api.github.com/users/mnguyen-io/repos",
      "events_url": "https://api.github.com/users/mnguyen-io/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mnguyen-io/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-01-17T18:15:07Z",
    "updated_at": "2022-01-17T18:15:07Z",
    "author_association": "NONE",
    "body": "> A full set of debug logs would be nice (especially if this is a recurring issue). 10-30 mins prior to the warning would be great.\r\n\r\nProblem hasn't come up in the past month or so for us so I'm unable to provide logs. I'll keep an eye out if it happens again as it use to happen some what frequently (every week or so).\r\n\r\nThanks",
    "reactions": {
      "url": "https://api.github.com/repos/sigp/lighthouse/issues/comments/1014792997/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/sigp/lighthouse/issues/comments/1014959823",
    "html_url": "https://github.com/sigp/lighthouse/issues/2858#issuecomment-1014959823",
    "issue_url": "https://api.github.com/repos/sigp/lighthouse/issues/2858",
    "id": 1014959823,
    "node_id": "IC_kwDOCFeAzc48fw7P",
    "user": {
      "login": "AgeManning",
      "id": 7454587,
      "node_id": "MDQ6VXNlcjc0NTQ1ODc=",
      "avatar_url": "https://avatars.githubusercontent.com/u/7454587?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/AgeManning",
      "html_url": "https://github.com/AgeManning",
      "followers_url": "https://api.github.com/users/AgeManning/followers",
      "following_url": "https://api.github.com/users/AgeManning/following{/other_user}",
      "gists_url": "https://api.github.com/users/AgeManning/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/AgeManning/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/AgeManning/subscriptions",
      "organizations_url": "https://api.github.com/users/AgeManning/orgs",
      "repos_url": "https://api.github.com/users/AgeManning/repos",
      "events_url": "https://api.github.com/users/AgeManning/events{/privacy}",
      "received_events_url": "https://api.github.com/users/AgeManning/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-01-17T23:52:08Z",
    "updated_at": "2022-01-17T23:52:08Z",
    "author_association": "MEMBER",
    "body": "My initial thinking is the following:\r\n- Discovery takes a while (especially for subnets) to search for peers on a given subnet. If the network isn't rich with validating nodes subscribed to a log of subnets these can backlog and you can miss finding peers for subnets with a lower slot times. You can check this in the metrics, and look at the discovery queries queue. \r\n- Gossipsub has a backoff period of 1 minute. If you subscribe to a subnet with some peers, you have to wait 1 minute before re-subscribing. With a short slot time, you may subscribe and unsubscribe from a subnet and then lock yourself out from re-subscribing with the same peers for a whole minute. There is a PR that was just merged in gossipsub that lowers this to 10 seconds. It should come in the next lighthouse release, which may help",
    "reactions": {
      "url": "https://api.github.com/repos/sigp/lighthouse/issues/comments/1014959823/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/sigp/lighthouse/issues/comments/1017832404",
    "html_url": "https://github.com/sigp/lighthouse/issues/2858#issuecomment-1017832404",
    "issue_url": "https://api.github.com/repos/sigp/lighthouse/issues/2858",
    "id": 1017832404,
    "node_id": "IC_kwDOCFeAzc48quPU",
    "user": {
      "login": "mnguyen-io",
      "id": 16768116,
      "node_id": "MDQ6VXNlcjE2NzY4MTE2",
      "avatar_url": "https://avatars.githubusercontent.com/u/16768116?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mnguyen-io",
      "html_url": "https://github.com/mnguyen-io",
      "followers_url": "https://api.github.com/users/mnguyen-io/followers",
      "following_url": "https://api.github.com/users/mnguyen-io/following{/other_user}",
      "gists_url": "https://api.github.com/users/mnguyen-io/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mnguyen-io/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mnguyen-io/subscriptions",
      "organizations_url": "https://api.github.com/users/mnguyen-io/orgs",
      "repos_url": "https://api.github.com/users/mnguyen-io/repos",
      "events_url": "https://api.github.com/users/mnguyen-io/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mnguyen-io/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-01-20T19:07:05Z",
    "updated_at": "2022-01-20T19:07:05Z",
    "author_association": "NONE",
    "body": "> A full set of debug logs would be nice (especially if this is a recurring issue). 10-30 mins prior to the warning would be great.\r\n\r\nHi - this happened a few times today. Here are some logs that will hopefully help:\r\n\r\nhttps://filebin.net/7f0e8m8yxzrlqa79/p2p.ZIP\r\n\r\nThe InsufficientPeers messages start to come in around Jan 20 15:23:51\r\n\r\nThanks",
    "reactions": {
      "url": "https://api.github.com/repos/sigp/lighthouse/issues/comments/1017832404/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/sigp/lighthouse/issues/comments/1233796457",
    "html_url": "https://github.com/sigp/lighthouse/issues/2858#issuecomment-1233796457",
    "issue_url": "https://api.github.com/repos/sigp/lighthouse/issues/2858",
    "id": 1233796457,
    "node_id": "IC_kwDOCFeAzc5Jij1p",
    "user": {
      "login": "3cl1ps",
      "id": 2938587,
      "node_id": "MDQ6VXNlcjI5Mzg1ODc=",
      "avatar_url": "https://avatars.githubusercontent.com/u/2938587?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/3cl1ps",
      "html_url": "https://github.com/3cl1ps",
      "followers_url": "https://api.github.com/users/3cl1ps/followers",
      "following_url": "https://api.github.com/users/3cl1ps/following{/other_user}",
      "gists_url": "https://api.github.com/users/3cl1ps/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/3cl1ps/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/3cl1ps/subscriptions",
      "organizations_url": "https://api.github.com/users/3cl1ps/orgs",
      "repos_url": "https://api.github.com/users/3cl1ps/repos",
      "events_url": "https://api.github.com/users/3cl1ps/events{/privacy}",
      "received_events_url": "https://api.github.com/users/3cl1ps/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-09-01T06:19:52Z",
    "updated_at": "2022-09-01T06:19:52Z",
    "author_association": "NONE",
    "body": "had this bug on 3.0.0 once a week, updated to 3.0.1. following.",
    "reactions": {
      "url": "https://api.github.com/repos/sigp/lighthouse/issues/comments/1233796457/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/sigp/lighthouse/issues/comments/1236611873",
    "html_url": "https://github.com/sigp/lighthouse/issues/2858#issuecomment-1236611873",
    "issue_url": "https://api.github.com/repos/sigp/lighthouse/issues/2858",
    "id": 1236611873,
    "node_id": "IC_kwDOCFeAzc5JtTMh",
    "user": {
      "login": "3cl1ps",
      "id": 2938587,
      "node_id": "MDQ6VXNlcjI5Mzg1ODc=",
      "avatar_url": "https://avatars.githubusercontent.com/u/2938587?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/3cl1ps",
      "html_url": "https://github.com/3cl1ps",
      "followers_url": "https://api.github.com/users/3cl1ps/followers",
      "following_url": "https://api.github.com/users/3cl1ps/following{/other_user}",
      "gists_url": "https://api.github.com/users/3cl1ps/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/3cl1ps/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/3cl1ps/subscriptions",
      "organizations_url": "https://api.github.com/users/3cl1ps/orgs",
      "repos_url": "https://api.github.com/users/3cl1ps/repos",
      "events_url": "https://api.github.com/users/3cl1ps/events{/privacy}",
      "received_events_url": "https://api.github.com/users/3cl1ps/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-09-05T07:00:54Z",
    "updated_at": "2022-09-05T07:02:01Z",
    "author_association": "NONE",
    "body": "error is still there, here just after a restart of the beacon service : \r\n```Sep 05 07:58:53 eth3 lighthouse[14158]: Sep 05 06:58:53.004 INFO Ready for the merge                     current_difficulty: 58003823773103876707853, terminal_total_difficulty: 58750000000000000000000, service: slot_notifier \r\nSep 05 07:58:59 eth3 lighthouse[14158]: Sep 05 06:58:59.842 INFO New RPC block received                  hash: 0x2f82~@a094, slot: 4628093 \r\nSep 05 07:59:03 eth3 lighthouse[14158]: Sep 05 06:59:03.039 WARN Could not publish message               error: InsufficientPeers, service: libp2p \r\nSep 05 07:59:03 eth3 lighthouse[14158]: Sep 05 06:59:03.567 WARN Gossip message published on retry       topic: beacon_attestation, service: libp2p",
    "reactions": {
      "url": "https://api.github.com/repos/sigp/lighthouse/issues/comments/1236611873/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/sigp/lighthouse/issues/comments/1236613831",
    "html_url": "https://github.com/sigp/lighthouse/issues/2858#issuecomment-1236613831",
    "issue_url": "https://api.github.com/repos/sigp/lighthouse/issues/2858",
    "id": 1236613831,
    "node_id": "IC_kwDOCFeAzc5JtTrH",
    "user": {
      "login": "michaelsproul",
      "id": 4452260,
      "node_id": "MDQ6VXNlcjQ0NTIyNjA=",
      "avatar_url": "https://avatars.githubusercontent.com/u/4452260?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/michaelsproul",
      "html_url": "https://github.com/michaelsproul",
      "followers_url": "https://api.github.com/users/michaelsproul/followers",
      "following_url": "https://api.github.com/users/michaelsproul/following{/other_user}",
      "gists_url": "https://api.github.com/users/michaelsproul/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/michaelsproul/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/michaelsproul/subscriptions",
      "organizations_url": "https://api.github.com/users/michaelsproul/orgs",
      "repos_url": "https://api.github.com/users/michaelsproul/repos",
      "events_url": "https://api.github.com/users/michaelsproul/events{/privacy}",
      "received_events_url": "https://api.github.com/users/michaelsproul/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-09-05T07:03:42Z",
    "updated_at": "2022-09-05T07:03:51Z",
    "author_association": "MEMBER",
    "body": "@3cl1ps it's possible (and likely) to get the warning immediately after start-up when the node hasn't got enough peers yet\r\n\r\nIf you're seeing it when the node otherwise has a high peer count, then that's an issue. One common cause is not having ports forwarded properly, can you please run `curl http://localhost:5052/lighthouse/nat` and show us the output?",
    "reactions": {
      "url": "https://api.github.com/repos/sigp/lighthouse/issues/comments/1236613831/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/sigp/lighthouse/issues/comments/1236624484",
    "html_url": "https://github.com/sigp/lighthouse/issues/2858#issuecomment-1236624484",
    "issue_url": "https://api.github.com/repos/sigp/lighthouse/issues/2858",
    "id": 1236624484,
    "node_id": "IC_kwDOCFeAzc5JtWRk",
    "user": {
      "login": "3cl1ps",
      "id": 2938587,
      "node_id": "MDQ6VXNlcjI5Mzg1ODc=",
      "avatar_url": "https://avatars.githubusercontent.com/u/2938587?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/3cl1ps",
      "html_url": "https://github.com/3cl1ps",
      "followers_url": "https://api.github.com/users/3cl1ps/followers",
      "following_url": "https://api.github.com/users/3cl1ps/following{/other_user}",
      "gists_url": "https://api.github.com/users/3cl1ps/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/3cl1ps/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/3cl1ps/subscriptions",
      "organizations_url": "https://api.github.com/users/3cl1ps/orgs",
      "repos_url": "https://api.github.com/users/3cl1ps/repos",
      "events_url": "https://api.github.com/users/3cl1ps/events{/privacy}",
      "received_events_url": "https://api.github.com/users/3cl1ps/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-09-05T07:17:14Z",
    "updated_at": "2022-09-05T07:17:14Z",
    "author_association": "NONE",
    "body": "thx for fast  response\r\n➜  ~ curl http://localhost:5052/lighthouse/nat\r\n{\"data\":true}\r\n\r\nfull logs : \r\nhttps://paste.ubuntu.com/p/fxzmDVPkvn/",
    "reactions": {
      "url": "https://api.github.com/repos/sigp/lighthouse/issues/comments/1236624484/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/sigp/lighthouse/issues/comments/1236652495",
    "html_url": "https://github.com/sigp/lighthouse/issues/2858#issuecomment-1236652495",
    "issue_url": "https://api.github.com/repos/sigp/lighthouse/issues/2858",
    "id": 1236652495,
    "node_id": "IC_kwDOCFeAzc5JtdHP",
    "user": {
      "login": "3cl1ps",
      "id": 2938587,
      "node_id": "MDQ6VXNlcjI5Mzg1ODc=",
      "avatar_url": "https://avatars.githubusercontent.com/u/2938587?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/3cl1ps",
      "html_url": "https://github.com/3cl1ps",
      "followers_url": "https://api.github.com/users/3cl1ps/followers",
      "following_url": "https://api.github.com/users/3cl1ps/following{/other_user}",
      "gists_url": "https://api.github.com/users/3cl1ps/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/3cl1ps/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/3cl1ps/subscriptions",
      "organizations_url": "https://api.github.com/users/3cl1ps/orgs",
      "repos_url": "https://api.github.com/users/3cl1ps/repos",
      "events_url": "https://api.github.com/users/3cl1ps/events{/privacy}",
      "received_events_url": "https://api.github.com/users/3cl1ps/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-09-05T07:45:54Z",
    "updated_at": "2022-09-05T08:02:47Z",
    "author_association": "NONE",
    "body": "debug log : \r\nhttp://sprunge.us/72J4Uh\r\n\r\nand attestation (in)effectiveness on beaconcha.in\r\n\r\n![image](https://user-images.githubusercontent.com/2938587/188399281-caca9c40-8c43-43eb-bdea-8b09839a12bc.png)\r\n",
    "reactions": {
      "url": "https://api.github.com/repos/sigp/lighthouse/issues/comments/1236652495/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/sigp/lighthouse/issues/comments/1237732317",
    "html_url": "https://github.com/sigp/lighthouse/issues/2858#issuecomment-1237732317",
    "issue_url": "https://api.github.com/repos/sigp/lighthouse/issues/2858",
    "id": 1237732317,
    "node_id": "IC_kwDOCFeAzc5Jxkvd",
    "user": {
      "login": "AgeManning",
      "id": 7454587,
      "node_id": "MDQ6VXNlcjc0NTQ1ODc=",
      "avatar_url": "https://avatars.githubusercontent.com/u/7454587?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/AgeManning",
      "html_url": "https://github.com/AgeManning",
      "followers_url": "https://api.github.com/users/AgeManning/followers",
      "following_url": "https://api.github.com/users/AgeManning/following{/other_user}",
      "gists_url": "https://api.github.com/users/AgeManning/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/AgeManning/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/AgeManning/subscriptions",
      "organizations_url": "https://api.github.com/users/AgeManning/orgs",
      "repos_url": "https://api.github.com/users/AgeManning/repos",
      "events_url": "https://api.github.com/users/AgeManning/events{/privacy}",
      "received_events_url": "https://api.github.com/users/AgeManning/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-09-06T06:54:54Z",
    "updated_at": "2022-09-06T06:55:10Z",
    "author_association": "MEMBER",
    "body": "I had a look through your logs. It looks like your system clock could be out. You are kicking peers for sending attestations at the wrong time. \r\n\r\nYou should make sure your system clock is synced to a network clock, using something like ntp. ",
    "reactions": {
      "url": "https://api.github.com/repos/sigp/lighthouse/issues/comments/1237732317/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/sigp/lighthouse/issues/comments/1237760754",
    "html_url": "https://github.com/sigp/lighthouse/issues/2858#issuecomment-1237760754",
    "issue_url": "https://api.github.com/repos/sigp/lighthouse/issues/2858",
    "id": 1237760754,
    "node_id": "IC_kwDOCFeAzc5Jxrry",
    "user": {
      "login": "3cl1ps",
      "id": 2938587,
      "node_id": "MDQ6VXNlcjI5Mzg1ODc=",
      "avatar_url": "https://avatars.githubusercontent.com/u/2938587?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/3cl1ps",
      "html_url": "https://github.com/3cl1ps",
      "followers_url": "https://api.github.com/users/3cl1ps/followers",
      "following_url": "https://api.github.com/users/3cl1ps/following{/other_user}",
      "gists_url": "https://api.github.com/users/3cl1ps/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/3cl1ps/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/3cl1ps/subscriptions",
      "organizations_url": "https://api.github.com/users/3cl1ps/orgs",
      "repos_url": "https://api.github.com/users/3cl1ps/repos",
      "events_url": "https://api.github.com/users/3cl1ps/events{/privacy}",
      "received_events_url": "https://api.github.com/users/3cl1ps/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-09-06T07:26:08Z",
    "updated_at": "2022-09-06T08:20:54Z",
    "author_association": "NONE",
    "body": "thanks for looking into this. i used somer esta's guide with ntp service configured :\r\nSystem clock synchronized: yes                         \r\nNTP service: active\r\n\r\ni had a case with this service being active but not sync, i'll watch this next time i have bad effectiveness.\r\n\r\nfor anyone reading this, this is a kind of error to look for : \r\n```Sep 05 08:31:55 eth3 lighthouse[26048]: Sep 05 07:31:55.984 DEBG Invalid attestation from network        type: \"aggregated\", peer_id: 16Uiu2HAm4zThK1zDn8jhGoLiycPZfYNiJyi4p1xcBHEY7q7jAHC4, block: 0x259168fa37ca9548abf2812bba8d551c386a12ac380bc7d91a400ee0fa134f98, reason: FutureSlot { attestation_slot: Slot(4628258), latest_permissible_slot: Slot(4628257) }```\r\n\r\nedit : can confirm it's a ntp issue : \r\n```systemd-timesyncd[713]: Failed to set up connection socket: Address family not supported by protocol```\r\ncaused by disabling ipv6.",
    "reactions": {
      "url": "https://api.github.com/repos/sigp/lighthouse/issues/comments/1237760754/reactions",
      "total_count": 2,
      "+1": 2,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/sigp/lighthouse/issues/comments/1238804892",
    "html_url": "https://github.com/sigp/lighthouse/issues/2858#issuecomment-1238804892",
    "issue_url": "https://api.github.com/repos/sigp/lighthouse/issues/2858",
    "id": 1238804892,
    "node_id": "IC_kwDOCFeAzc5J1qmc",
    "user": {
      "login": "AgeManning",
      "id": 7454587,
      "node_id": "MDQ6VXNlcjc0NTQ1ODc=",
      "avatar_url": "https://avatars.githubusercontent.com/u/7454587?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/AgeManning",
      "html_url": "https://github.com/AgeManning",
      "followers_url": "https://api.github.com/users/AgeManning/followers",
      "following_url": "https://api.github.com/users/AgeManning/following{/other_user}",
      "gists_url": "https://api.github.com/users/AgeManning/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/AgeManning/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/AgeManning/subscriptions",
      "organizations_url": "https://api.github.com/users/AgeManning/orgs",
      "repos_url": "https://api.github.com/users/AgeManning/repos",
      "events_url": "https://api.github.com/users/AgeManning/events{/privacy}",
      "received_events_url": "https://api.github.com/users/AgeManning/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-09-07T01:24:08Z",
    "updated_at": "2022-09-07T01:24:08Z",
    "author_association": "MEMBER",
    "body": "Awesome. I'll add something to our FAQ docs, as a time sync issue is a common occurrence. \r\n\r\nIf it is now behaving as expected, feel free to close the issue :)",
    "reactions": {
      "url": "https://api.github.com/repos/sigp/lighthouse/issues/comments/1238804892/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/sigp/lighthouse/issues/comments/1238978693",
    "html_url": "https://github.com/sigp/lighthouse/issues/2858#issuecomment-1238978693",
    "issue_url": "https://api.github.com/repos/sigp/lighthouse/issues/2858",
    "id": 1238978693,
    "node_id": "IC_kwDOCFeAzc5J2VCF",
    "user": {
      "login": "3cl1ps",
      "id": 2938587,
      "node_id": "MDQ6VXNlcjI5Mzg1ODc=",
      "avatar_url": "https://avatars.githubusercontent.com/u/2938587?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/3cl1ps",
      "html_url": "https://github.com/3cl1ps",
      "followers_url": "https://api.github.com/users/3cl1ps/followers",
      "following_url": "https://api.github.com/users/3cl1ps/following{/other_user}",
      "gists_url": "https://api.github.com/users/3cl1ps/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/3cl1ps/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/3cl1ps/subscriptions",
      "organizations_url": "https://api.github.com/users/3cl1ps/orgs",
      "repos_url": "https://api.github.com/users/3cl1ps/repos",
      "events_url": "https://api.github.com/users/3cl1ps/events{/privacy}",
      "received_events_url": "https://api.github.com/users/3cl1ps/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-09-07T06:49:58Z",
    "updated_at": "2022-09-07T06:49:58Z",
    "author_association": "NONE",
    "body": "I can't, i didn't open it.",
    "reactions": {
      "url": "https://api.github.com/repos/sigp/lighthouse/issues/comments/1238978693/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/sigp/lighthouse/issues/comments/1240014022",
    "html_url": "https://github.com/sigp/lighthouse/issues/2858#issuecomment-1240014022",
    "issue_url": "https://api.github.com/repos/sigp/lighthouse/issues/2858",
    "id": 1240014022,
    "node_id": "IC_kwDOCFeAzc5J6RzG",
    "user": {
      "login": "AgeManning",
      "id": 7454587,
      "node_id": "MDQ6VXNlcjc0NTQ1ODc=",
      "avatar_url": "https://avatars.githubusercontent.com/u/7454587?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/AgeManning",
      "html_url": "https://github.com/AgeManning",
      "followers_url": "https://api.github.com/users/AgeManning/followers",
      "following_url": "https://api.github.com/users/AgeManning/following{/other_user}",
      "gists_url": "https://api.github.com/users/AgeManning/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/AgeManning/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/AgeManning/subscriptions",
      "organizations_url": "https://api.github.com/users/AgeManning/orgs",
      "repos_url": "https://api.github.com/users/AgeManning/repos",
      "events_url": "https://api.github.com/users/AgeManning/events{/privacy}",
      "received_events_url": "https://api.github.com/users/AgeManning/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-09-07T23:22:48Z",
    "updated_at": "2022-09-07T23:22:48Z",
    "author_association": "MEMBER",
    "body": "Fair. Assuming this is resolved.",
    "reactions": {
      "url": "https://api.github.com/repos/sigp/lighthouse/issues/comments/1240014022/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  }
]
