{
  "url": "https://api.github.com/repos/sigp/lighthouse/issues/4331",
  "repository_url": "https://api.github.com/repos/sigp/lighthouse",
  "labels_url": "https://api.github.com/repos/sigp/lighthouse/issues/4331/labels{/name}",
  "comments_url": "https://api.github.com/repos/sigp/lighthouse/issues/4331/comments",
  "events_url": "https://api.github.com/repos/sigp/lighthouse/issues/4331/events",
  "html_url": "https://github.com/sigp/lighthouse/issues/4331",
  "id": 1724976749,
  "node_id": "I_kwDOCFeAzc5m0Q5t",
  "number": 4331,
  "title": "Historical block download doesn't realize it's finished",
  "user": {
    "login": "yorickdowne",
    "id": 71337066,
    "node_id": "MDQ6VXNlcjcxMzM3MDY2",
    "avatar_url": "https://avatars.githubusercontent.com/u/71337066?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/yorickdowne",
    "html_url": "https://github.com/yorickdowne",
    "followers_url": "https://api.github.com/users/yorickdowne/followers",
    "following_url": "https://api.github.com/users/yorickdowne/following{/other_user}",
    "gists_url": "https://api.github.com/users/yorickdowne/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/yorickdowne/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/yorickdowne/subscriptions",
    "organizations_url": "https://api.github.com/users/yorickdowne/orgs",
    "repos_url": "https://api.github.com/users/yorickdowne/repos",
    "events_url": "https://api.github.com/users/yorickdowne/events{/privacy}",
    "received_events_url": "https://api.github.com/users/yorickdowne/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [
    {
      "id": 985647281,
      "node_id": "MDU6TGFiZWw5ODU2NDcyODE=",
      "url": "https://api.github.com/repos/sigp/lighthouse/labels/bug",
      "name": "bug",
      "color": "d73a4a",
      "default": true,
      "description": "Something isn't working"
    },
    {
      "id": 2336800125,
      "node_id": "MDU6TGFiZWwyMzM2ODAwMTI1",
      "url": "https://api.github.com/repos/sigp/lighthouse/labels/t%20Networking",
      "name": "t Networking",
      "color": "40E0D0",
      "default": false,
      "description": ""
    },
    {
      "id": 5676700781,
      "node_id": "LA_kwDOCFeAzc8AAAABUluUbQ",
      "url": "https://api.github.com/repos/sigp/lighthouse/labels/v4.4.1",
      "name": "v4.4.1",
      "color": "FE5F2B",
      "default": false,
      "description": "ETA August 2023"
    }
  ],
  "state": "closed",
  "locked": false,
  "assignee": {
    "login": "jmcph4",
    "id": 717268,
    "node_id": "MDQ6VXNlcjcxNzI2OA==",
    "avatar_url": "https://avatars.githubusercontent.com/u/717268?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/jmcph4",
    "html_url": "https://github.com/jmcph4",
    "followers_url": "https://api.github.com/users/jmcph4/followers",
    "following_url": "https://api.github.com/users/jmcph4/following{/other_user}",
    "gists_url": "https://api.github.com/users/jmcph4/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/jmcph4/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/jmcph4/subscriptions",
    "organizations_url": "https://api.github.com/users/jmcph4/orgs",
    "repos_url": "https://api.github.com/users/jmcph4/repos",
    "events_url": "https://api.github.com/users/jmcph4/events{/privacy}",
    "received_events_url": "https://api.github.com/users/jmcph4/received_events",
    "type": "User",
    "site_admin": false
  },
  "assignees": [
    {
      "login": "jmcph4",
      "id": 717268,
      "node_id": "MDQ6VXNlcjcxNzI2OA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/717268?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jmcph4",
      "html_url": "https://github.com/jmcph4",
      "followers_url": "https://api.github.com/users/jmcph4/followers",
      "following_url": "https://api.github.com/users/jmcph4/following{/other_user}",
      "gists_url": "https://api.github.com/users/jmcph4/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jmcph4/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jmcph4/subscriptions",
      "organizations_url": "https://api.github.com/users/jmcph4/orgs",
      "repos_url": "https://api.github.com/users/jmcph4/repos",
      "events_url": "https://api.github.com/users/jmcph4/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jmcph4/received_events",
      "type": "User",
      "site_admin": false
    }
  ],
  "milestone": null,
  "comments": 5,
  "created_at": "2023-05-25T02:20:23Z",
  "updated_at": "2023-09-12T05:48:41Z",
  "closed_at": "2023-07-07T04:23:48Z",
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "## Description\r\n\r\nAfter historical block download completes, it continues showing:\r\n\r\n`May 25 02:16:22.500 INFO Downloading historical blocks           est_time: --, speed: 19.25 slots/sec, distance: 0 slots (--), service: slot_notifier`\r\n\r\nAnd `/eth/v1/node/health` returns 206.\r\n\r\nAfter restarting Lighthouse, it returns 200, and the historical block log no longer shows.\r\n\r\nThis is with execution not yet done syncing, while Lighthouse is done. Unsure whether it's related to execution sync state at all.\r\n\r\n## Version\r\n\r\n`4.2.0`\r\n",
  "closed_by": {
    "login": "jmcph4",
    "id": 717268,
    "node_id": "MDQ6VXNlcjcxNzI2OA==",
    "avatar_url": "https://avatars.githubusercontent.com/u/717268?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/jmcph4",
    "html_url": "https://github.com/jmcph4",
    "followers_url": "https://api.github.com/users/jmcph4/followers",
    "following_url": "https://api.github.com/users/jmcph4/following{/other_user}",
    "gists_url": "https://api.github.com/users/jmcph4/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/jmcph4/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/jmcph4/subscriptions",
    "organizations_url": "https://api.github.com/users/jmcph4/orgs",
    "repos_url": "https://api.github.com/users/jmcph4/repos",
    "events_url": "https://api.github.com/users/jmcph4/events{/privacy}",
    "received_events_url": "https://api.github.com/users/jmcph4/received_events",
    "type": "User",
    "site_admin": false
  },
  "reactions": {
    "url": "https://api.github.com/repos/sigp/lighthouse/issues/4331/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/sigp/lighthouse/issues/4331/timeline",
  "performed_via_github_app": null,
  "state_reason": "completed"
}
[
  {
    "url": "https://api.github.com/repos/sigp/lighthouse/issues/comments/1562259800",
    "html_url": "https://github.com/sigp/lighthouse/issues/4331#issuecomment-1562259800",
    "issue_url": "https://api.github.com/repos/sigp/lighthouse/issues/4331",
    "id": 1562259800,
    "node_id": "IC_kwDOCFeAzc5dHjFY",
    "user": {
      "login": "AgeManning",
      "id": 7454587,
      "node_id": "MDQ6VXNlcjc0NTQ1ODc=",
      "avatar_url": "https://avatars.githubusercontent.com/u/7454587?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/AgeManning",
      "html_url": "https://github.com/AgeManning",
      "followers_url": "https://api.github.com/users/AgeManning/followers",
      "following_url": "https://api.github.com/users/AgeManning/following{/other_user}",
      "gists_url": "https://api.github.com/users/AgeManning/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/AgeManning/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/AgeManning/subscriptions",
      "organizations_url": "https://api.github.com/users/AgeManning/orgs",
      "repos_url": "https://api.github.com/users/AgeManning/repos",
      "events_url": "https://api.github.com/users/AgeManning/events{/privacy}",
      "received_events_url": "https://api.github.com/users/AgeManning/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2023-05-25T04:46:36Z",
    "updated_at": "2023-05-25T04:46:36Z",
    "author_association": "MEMBER",
    "body": "Thanks for the report. \r\n\r\nWill be fixed in the next release :)",
    "reactions": {
      "url": "https://api.github.com/repos/sigp/lighthouse/issues/comments/1562259800/reactions",
      "total_count": 1,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 1,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/sigp/lighthouse/issues/comments/1614137735",
    "html_url": "https://github.com/sigp/lighthouse/issues/4331#issuecomment-1614137735",
    "issue_url": "https://api.github.com/repos/sigp/lighthouse/issues/4331",
    "id": 1614137735,
    "node_id": "IC_kwDOCFeAzc5gNcmH",
    "user": {
      "login": "paulhauner",
      "id": 6660660,
      "node_id": "MDQ6VXNlcjY2NjA2NjA=",
      "avatar_url": "https://avatars.githubusercontent.com/u/6660660?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/paulhauner",
      "html_url": "https://github.com/paulhauner",
      "followers_url": "https://api.github.com/users/paulhauner/followers",
      "following_url": "https://api.github.com/users/paulhauner/following{/other_user}",
      "gists_url": "https://api.github.com/users/paulhauner/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/paulhauner/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/paulhauner/subscriptions",
      "organizations_url": "https://api.github.com/users/paulhauner/orgs",
      "repos_url": "https://api.github.com/users/paulhauner/repos",
      "events_url": "https://api.github.com/users/paulhauner/events{/privacy}",
      "received_events_url": "https://api.github.com/users/paulhauner/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2023-06-30T05:11:44Z",
    "updated_at": "2023-06-30T05:11:44Z",
    "author_association": "MEMBER",
    "body": "Unfortunately this didn't make it into our v4.3.0 release :( We're being pressured to get v4.3.0 out for a Gnosis upgrade and we just couldn't get this one done in time. We're keen to get it fixed in the following release, though!",
    "reactions": {
      "url": "https://api.github.com/repos/sigp/lighthouse/issues/comments/1614137735/reactions",
      "total_count": 1,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 1,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/sigp/lighthouse/issues/comments/1624694522",
    "html_url": "https://github.com/sigp/lighthouse/issues/4331#issuecomment-1624694522",
    "issue_url": "https://api.github.com/repos/sigp/lighthouse/issues/4331",
    "id": 1624694522,
    "node_id": "IC_kwDOCFeAzc5g1t76",
    "user": {
      "login": "jmcph4",
      "id": 717268,
      "node_id": "MDQ6VXNlcjcxNzI2OA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/717268?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jmcph4",
      "html_url": "https://github.com/jmcph4",
      "followers_url": "https://api.github.com/users/jmcph4/followers",
      "following_url": "https://api.github.com/users/jmcph4/following{/other_user}",
      "gists_url": "https://api.github.com/users/jmcph4/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jmcph4/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jmcph4/subscriptions",
      "organizations_url": "https://api.github.com/users/jmcph4/orgs",
      "repos_url": "https://api.github.com/users/jmcph4/repos",
      "events_url": "https://api.github.com/users/jmcph4/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jmcph4/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2023-07-07T04:23:48Z",
    "updated_at": "2023-07-07T04:23:48Z",
    "author_association": "COLLABORATOR",
    "body": "Closed by #4465 ",
    "reactions": {
      "url": "https://api.github.com/repos/sigp/lighthouse/issues/comments/1624694522/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/sigp/lighthouse/issues/comments/1714971066",
    "html_url": "https://github.com/sigp/lighthouse/issues/4331#issuecomment-1714971066",
    "issue_url": "https://api.github.com/repos/sigp/lighthouse/issues/4331",
    "id": 1714971066,
    "node_id": "IC_kwDOCFeAzc5mOGG6",
    "user": {
      "login": "elsesiy",
      "id": 7075075,
      "node_id": "MDQ6VXNlcjcwNzUwNzU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/7075075?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/elsesiy",
      "html_url": "https://github.com/elsesiy",
      "followers_url": "https://api.github.com/users/elsesiy/followers",
      "following_url": "https://api.github.com/users/elsesiy/following{/other_user}",
      "gists_url": "https://api.github.com/users/elsesiy/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/elsesiy/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/elsesiy/subscriptions",
      "organizations_url": "https://api.github.com/users/elsesiy/orgs",
      "repos_url": "https://api.github.com/users/elsesiy/repos",
      "events_url": "https://api.github.com/users/elsesiy/events{/privacy}",
      "received_events_url": "https://api.github.com/users/elsesiy/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2023-09-12T05:01:07Z",
    "updated_at": "2023-09-12T05:01:07Z",
    "author_association": "NONE",
    "body": "@jmcph4 @michaelsproul I'm observing the same behavior as documented in #4346 with `4.4.1` after a fresh checkpoint sync:\r\n```\r\nSep 12 06:59:05 v2202209182301199785 lighthouse[3450]: Sep 12 04:59:05.332 ERRO Backfill sync failed                    error: InvalidSyncState(\"Batch not found for current processing target 195168\"), service: sync\r\nSep 12 06:59:05 v2202209182301199785 lighthouse[3450]: Sep 12 04:59:05.332 INFO Sync state updated                      new_state: Synced, old_state: Syncing Historical Blocks, service: sync\r\nSep 12 06:59:05 v2202209182301199785 lighthouse[3450]: Sep 12 04:59:05.809 INFO Sync state updated                      new_state: Syncing Historical Blocks, old_state: Synced, service: sync\r\nSep 12 06:59:11 v2202209182301199785 lighthouse[3450]: Sep 12 04:59:11.828 INFO New block received                      root: 0x5b9add3620e8d053d78f271745c09fe31e9f9dc547d63979f4f24f09c5889742, slot: 7305894\r\nSep 12 06:59:17 v2202209182301199785 lighthouse[3450]: Sep 12 04:59:17.001 INFO Synced                                  slot: 7305894, block: 0x5b9a…9742, epoch: 228309, finalized_epoch: 228307, finalized_root: 0x4ef8…9bd4, exec_hash: 0xfb04…701f (verified), peers: 88, service: slot_notifier\r\nSep 12 06:59:17 v2202209182301199785 lighthouse[3450]: Sep 12 04:59:17.321 ERRO Backfill out of sync with beacon chain  service: sync\r\nSep 12 06:59:17 v2202209182301199785 lighthouse[3450]: Sep 12 04:59:17.321 ERRO Backfill sync failed                    error: InvalidSyncState(\"Batch not found for current processing target 195168\"), service: sync\r\nSep 12 06:59:17 v2202209182301199785 lighthouse[3450]: Sep 12 04:59:17.321 INFO Sync state updated                      new_state: Synced, old_state: Syncing Historical Blocks, service: sync\r\nSep 12 06:59:24 v2202209182301199785 lighthouse[3450]: Sep 12 04:59:24.621 INFO New block received                      root: 0x7fc1263c50f2e0bd8ea4af84f23cf52e95802f8acca65b65c00985b8105bf415, slot: 7305895\r\nSep 12 06:59:29 v2202209182301199785 lighthouse[3450]: Sep 12 04:59:29.001 INFO Historical block download complete      service: slot_notifier\r\nSep 12 06:59:29 v2202209182301199785 lighthouse[3450]: Sep 12 04:59:29.001 INFO Synced                                  slot: 7305895, block: 0x7fc1…f415, epoch: 228309, finalized_epoch: 228307, finalized_root: 0x4ef8…9bd4, exec_hash: 0x056d…1af3 (verified), peers: 88, service: slot_notifier\r\nSep 12 06:59:30 v2202209182301199785 lighthouse[3450]: Sep 12 04:59:30.907 INFO Sync state updated                      new_state: Syncing Historical Blocks, old_state: Synced, service: sync\r\nSep 12 06:59:37 v2202209182301199785 lighthouse[3450]: Sep 12 04:59:37.267 INFO New block received                      root: 0xd1669139a3b6e85943a6c17a7f7d0a4115c750e9e37c9437823f0356c93ebb22, slot: 7305896\r\nSep 12 06:59:41 v2202209182301199785 lighthouse[3450]: Sep 12 04:59:41.001 INFO Downloading historical blocks           est_time: --, distance: 1 slots (0 mins), service: slot_notifier\r\nSep 12 06:59:41 v2202209182301199785 lighthouse[3450]: Sep 12 04:59:41.001 INFO Synced                                  slot: 7305896, block: 0xd166…bb22, epoch: 228309, finalized_epoch: 228307, finalized_root: 0x4ef8…9bd4, exec_hash: 0xbcc0…61f1 (verified), peers: 86, service: slot_notifier\r\nSep 12 06:59:41 v2202209182301199785 lighthouse[3450]: Sep 12 04:59:41.316 ERRO Backfill out of sync with beacon chain  service: sync\r\nSep 12 06:59:41 v2202209182301199785 lighthouse[3450]: Sep 12 04:59:41.316 ERRO Backfill sync failed                    error: InvalidSyncState(\"Batch not found for current processing target 195168\"), service: sync\r\nSep 12 06:59:41 v2202209182301199785 lighthouse[3450]: Sep 12 04:59:41.317 ERRO Backfill sync failed                    error: InvalidSyncState(\"Batch not found for current processing target 195168\"), service: sync\r\nSep 12 06:59:41 v2202209182301199785 lighthouse[3450]: Sep 12 04:59:41.317 INFO Sync state updated                      new_state: Synced, old_state: Syncing Historical Blocks, service: sync\r\n```\r\n\r\nDo you have any recommendations on how to get unstuck? Thanks!",
    "reactions": {
      "url": "https://api.github.com/repos/sigp/lighthouse/issues/comments/1714971066/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/sigp/lighthouse/issues/comments/1715011631",
    "html_url": "https://github.com/sigp/lighthouse/issues/4331#issuecomment-1715011631",
    "issue_url": "https://api.github.com/repos/sigp/lighthouse/issues/4331",
    "id": 1715011631,
    "node_id": "IC_kwDOCFeAzc5mOQAv",
    "user": {
      "login": "michaelsproul",
      "id": 4452260,
      "node_id": "MDQ6VXNlcjQ0NTIyNjA=",
      "avatar_url": "https://avatars.githubusercontent.com/u/4452260?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/michaelsproul",
      "html_url": "https://github.com/michaelsproul",
      "followers_url": "https://api.github.com/users/michaelsproul/followers",
      "following_url": "https://api.github.com/users/michaelsproul/following{/other_user}",
      "gists_url": "https://api.github.com/users/michaelsproul/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/michaelsproul/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/michaelsproul/subscriptions",
      "organizations_url": "https://api.github.com/users/michaelsproul/orgs",
      "repos_url": "https://api.github.com/users/michaelsproul/repos",
      "events_url": "https://api.github.com/users/michaelsproul/events{/privacy}",
      "received_events_url": "https://api.github.com/users/michaelsproul/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2023-09-12T05:48:40Z",
    "updated_at": "2023-09-12T05:48:40Z",
    "author_association": "MEMBER",
    "body": "> Do you have any recommendations on how to get unstuck? Thanks!\r\n\r\nRestarting the node fixed it previously, try that.\r\n\r\nWould you also mind sharing some debug logs so we can investigate and fix the root cause? You can find debug logs in `$datadir/beacon/logs/beacon.log`. If you compress those and DM them to me on Discord (`@sproul`) or send them via email (`michael at sigmaprime.io`) that would be great. Thanks!",
    "reactions": {
      "url": "https://api.github.com/repos/sigp/lighthouse/issues/comments/1715011631/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  }
]
