{
  "url": "https://api.github.com/repos/prysmaticlabs/prysm/issues/8073",
  "repository_url": "https://api.github.com/repos/prysmaticlabs/prysm",
  "labels_url": "https://api.github.com/repos/prysmaticlabs/prysm/issues/8073/labels{/name}",
  "comments_url": "https://api.github.com/repos/prysmaticlabs/prysm/issues/8073/comments",
  "events_url": "https://api.github.com/repos/prysmaticlabs/prysm/issues/8073/events",
  "html_url": "https://github.com/prysmaticlabs/prysm/issues/8073",
  "id": 759375935,
  "node_id": "MDU6SXNzdWU3NTkzNzU5MzU=",
  "number": 8073,
  "title": "help./prysm.sh beacon-chain --http-web3provider=http://localhost:8545  ",
  "user": {
    "login": "navy665180",
    "id": 75147624,
    "node_id": "MDQ6VXNlcjc1MTQ3NjI0",
    "avatar_url": "https://avatars.githubusercontent.com/u/75147624?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/navy665180",
    "html_url": "https://github.com/navy665180",
    "followers_url": "https://api.github.com/users/navy665180/followers",
    "following_url": "https://api.github.com/users/navy665180/following{/other_user}",
    "gists_url": "https://api.github.com/users/navy665180/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/navy665180/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/navy665180/subscriptions",
    "organizations_url": "https://api.github.com/users/navy665180/orgs",
    "repos_url": "https://api.github.com/users/navy665180/repos",
    "events_url": "https://api.github.com/users/navy665180/events{/privacy}",
    "received_events_url": "https://api.github.com/users/navy665180/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [

  ],
  "state": "closed",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 1,
  "created_at": "2020-12-08T11:41:13Z",
  "updated_at": "2020-12-16T08:08:47Z",
  "closed_at": "2020-12-16T08:08:47Z",
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "\r\n![snapshot1 20201208](https://user-images.githubusercontent.com/75147624/101481097-981bd700-398f-11eb-9b5f-085fdba2d2e1.png)\r\n![snapshot  geth syncing  20201208](https://user-images.githubusercontent.com/75147624/101481126-9eaa4e80-398f-11eb-9e77-86b51944cf24.png)\r\n\r\n<!--üíéüíéüíéüíéüíéüíéüíéüíéüíéüíéüíéüíéüíéüíéüíéüíéüíéüíéüíéüíéüíéüíéüíéüíéüíéüíéüíéüíéüíéüíé\r\n\r\nHellooo! üòÑ \r\n\r\nTo help us tend to your issue faster, please search our currently open issues before submitting a new one.\r\nExisting issues often contain information about workarounds, resolution, or progress updates.\r\n\r\nüíéüíéüíéüíéüíéüíéüíéüíéüíéüíéüíéüíéüíéüíéüíéüíéüíéüíéüíéüíéüíéüíéüíéüíéüíéüíéüíéüíéüíéüíéüíéüíéüíéüíéüíé-->\r\n\r\n# üêû Bug Report\r\n\r\n### Description\r\n\r\n<!-- ‚úçÔ∏è--> A clear and concise description of the problem...\r\ni use geth as the eth1.0.  2days later,geth get the newest block\r\nthen\r\ni start to run prysm\r\nthe step two,  i write the note like this in terminal window:\r\n\r\n./prysm.sh beacon-chain --http-web3provider=http://localhost:8545  \r\n\r\nthen return a error:like this:\r\n\r\nERROR powchain: Could not connect to powchain endpoint error=eth1 node has not finished syncing yet\r\n\r\n\r\n### Has this worked before in a previous version?\r\n\r\n<!-- Did this behavior use to work in the previous version? -->no\r\n<!-- ‚úçÔ∏è--> Yes, the previous version in which this bug was not present was: ....1.0.4\r\n\r\n## üî¨ Minimal Reproduction\r\n\r\n<!--\r\nPlease let us know how we can reproduce this issue. Include the exact method you used to run Prysm along with any flags used in your beacon chain and/or validator. Make sure you don't upload any confidential files or private keys.\r\n-->i did not upload any confidential files or private keys.it is step three,now i am step two:\r\n\r\n## üî• Error\r\n\r\n<pre><code>\r\n<!-- If the issue is accompanied by an error, please share the error logs with us below. If you have a lot of logs, place make a paste bin with your logs and share the link with us here: -->\r\n<!-- ‚úçÔ∏è-->\r\n\r\n</code></pre>\r\nethereum@ubuntu:~/prysm$ ./prysm.sh beacon-chain --http-web3provider=http://localhost:8545\r\nLatest Prysm version is v1.0.4.\r\nBeacon chain is up to date.\r\nVerifying binary integrity.\r\nbeacon-chain-v1.0.4-linux-amd64: OK\r\ngpg: Signature made Mon 07 Dec 2020 09:46:32 AM PST\r\ngpg:                using RSA key 0AE0051D647BA3C1A917AF4072E33E4DF1A5036E\r\ngpg: Good signature from \"Preston Van Loon <preston@prysmaticlabs.com>\" [unknown]\r\ngpg: WARNING: This key is not certified with a trusted signature!\r\ngpg:          There is no indication that the signature belongs to the owner.\r\nPrimary key fingerprint: 0AE0 051D 647B A3C1 A917  AF40 72E3 3E4D F1A5 036E\r\nVerified /home/ethereum/prysm/dist/beacon-chain-v1.0.4-linux-amd64 has been signed by Prysmatic Labs.\r\nStarting Prysm beacon-chain --http-web3provider=http://localhost:8545\r\n[2020-12-08 03:36:39]  WARN flags: Running on ETH2 Mainnet\r\n[2020-12-08 03:36:39]  INFO flags: Using \"max_cover\" strategy on attestation aggregation\r\n[2020-12-08 03:36:39]  INFO node: Checking DB database-path=/home/ethereum/.eth2/beaconchaindata\r\n[2020-12-08 03:36:39]  INFO node: Deposit contract: 0x00000000219ab540356cbb839cbe05303d7705fa\r\n[2020-12-08 03:36:39]  INFO initial-sync: Waiting for state to be initialized\r\n[2020-12-08 03:36:39]  INFO node: Starting beacon node version=Prysm/v1.0.4/b4437e6cecd78257d2699f42073a90a940baf716. Built at: 2020-12-07 16:42:42+00:00\r\n[2020-12-08 03:36:39]  INFO blockchain: Waiting to reach the validator deposit threshold to start the beacon chain...\r\n[2020-12-08 03:36:39]  INFO rpc: gRPC server listening on port address=127.0.0.1:4000\r\n[2020-12-08 03:36:39]  WARN rpc: You are using an insecure gRPC server. If you are running your beacon node and validator on the same machines, you can ignore this message. If you want to know how to enable secure connections, see: https://docs.prylabs.network/docs/prysm-usage/secure-grpc\r\n[2020-12-08 03:36:39]  INFO gateway: Starting JSON-HTTP API address=127.0.0.1:3500\r\n[2020-12-08 03:36:39] ERROR powchain: Could not connect to powchain endpoint error=eth1 node has not finished syncing yet\r\ngithub.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Service).dialETH1Nodes\r\n\tbeacon-chain/powchain/service.go:401\r\ngithub.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Service).connectToPowChain\r\n\tbeacon-chain/powchain/service.go:364\r\ngithub.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Service).waitForConnection\r\n\tbeacon-chain/powchain/service.go:438\r\ngithub.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Service).Start.func1\r\n\tbeacon-chain/powchain/service.go:257\r\nruntime.goexit\r\n\tGOROOT/src/runtime/asm_amd64.s:1374\r\ncould not dial eth1 nodes\r\ngithub.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Service).connectToPowChain\r\n\tbeacon-chain/powchain/service.go:366\r\ngithub.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Service).waitForConnection\r\n\tbeacon-chain/powchain/service.go:438\r\ngithub.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Service).Start.func1\r\n\tbeacon-chain/powchain/service.go:257\r\nruntime.goexit\r\n\tGOROOT/src/runtime/asm_amd64.s:1374\r\n\r\n![snapshot1 20201208](https://user-images.githubusercontent.com/75147624/101480376-900f6780-398e-11eb-9b20-e604f690c40d.png)\r\n![snapshot  geth syncing  20201208](https://user-images.githubusercontent.com/75147624/101480387-96054880-398e-11eb-8194-367fe37fe572.png)\r\n\r\n## üåç  Your Environment\r\n\r\n**Operating System:**ubuntu \r\n\r\n<pre>\r\n  <code>\r\n\r\n  </code>\r\n</pre>\r\n\r\n**What version of Prysm are you running? (Which release)**1.0.4\r\n\r\n<pre>\r\n  <code>\r\n\r\n  </code>\r\n</pre>\r\n\r\n**Anything else relevant (validator index / public key)?**\r\ni don't know the mistake ,about do the work more than 2 weeks ,can any hot-heart man/women could help me??thanks!!\r\n",
  "closed_by": {
    "login": "nisdas",
    "id": 33201827,
    "node_id": "MDQ6VXNlcjMzMjAxODI3",
    "avatar_url": "https://avatars.githubusercontent.com/u/33201827?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/nisdas",
    "html_url": "https://github.com/nisdas",
    "followers_url": "https://api.github.com/users/nisdas/followers",
    "following_url": "https://api.github.com/users/nisdas/following{/other_user}",
    "gists_url": "https://api.github.com/users/nisdas/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/nisdas/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/nisdas/subscriptions",
    "organizations_url": "https://api.github.com/users/nisdas/orgs",
    "repos_url": "https://api.github.com/users/nisdas/repos",
    "events_url": "https://api.github.com/users/nisdas/events{/privacy}",
    "received_events_url": "https://api.github.com/users/nisdas/received_events",
    "type": "User",
    "site_admin": false
  },
  "reactions": {
    "url": "https://api.github.com/repos/prysmaticlabs/prysm/issues/8073/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/prysmaticlabs/prysm/issues/8073/timeline",
  "performed_via_github_app": null,
  "state_reason": "completed"
}
[
  {
    "url": "https://api.github.com/repos/prysmaticlabs/prysm/issues/comments/745881454",
    "html_url": "https://github.com/prysmaticlabs/prysm/issues/8073#issuecomment-745881454",
    "issue_url": "https://api.github.com/repos/prysmaticlabs/prysm/issues/8073",
    "id": 745881454,
    "node_id": "MDEyOklzc3VlQ29tbWVudDc0NTg4MTQ1NA==",
    "user": {
      "login": "nisdas",
      "id": 33201827,
      "node_id": "MDQ6VXNlcjMzMjAxODI3",
      "avatar_url": "https://avatars.githubusercontent.com/u/33201827?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/nisdas",
      "html_url": "https://github.com/nisdas",
      "followers_url": "https://api.github.com/users/nisdas/followers",
      "following_url": "https://api.github.com/users/nisdas/following{/other_user}",
      "gists_url": "https://api.github.com/users/nisdas/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/nisdas/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/nisdas/subscriptions",
      "organizations_url": "https://api.github.com/users/nisdas/orgs",
      "repos_url": "https://api.github.com/users/nisdas/repos",
      "events_url": "https://api.github.com/users/nisdas/events{/privacy}",
      "received_events_url": "https://api.github.com/users/nisdas/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2020-12-16T08:08:47Z",
    "updated_at": "2020-12-16T08:08:47Z",
    "author_association": "MEMBER",
    "body": "@navy665180 Your eth1 node is still syncing, which is why you still see that error. You have to wait a while before your geth node is ready to serve after syncing. ",
    "reactions": {
      "url": "https://api.github.com/repos/prysmaticlabs/prysm/issues/comments/745881454/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  }
]
