{
  "url": "https://api.github.com/repos/ethereum-optimism/optimism/issues/3686",
  "repository_url": "https://api.github.com/repos/ethereum-optimism/optimism",
  "labels_url": "https://api.github.com/repos/ethereum-optimism/optimism/issues/3686/labels{/name}",
  "comments_url": "https://api.github.com/repos/ethereum-optimism/optimism/issues/3686/comments",
  "events_url": "https://api.github.com/repos/ethereum-optimism/optimism/issues/3686/events",
  "html_url": "https://github.com/ethereum-optimism/optimism/issues/3686",
  "id": 1403877325,
  "node_id": "I_kwDODjvEJM5TrXfN",
  "number": 3686,
  "title": "Unable to exit geth gracefully",
  "user": {
    "login": "masayil",
    "id": 65291464,
    "node_id": "MDQ6VXNlcjY1MjkxNDY0",
    "avatar_url": "https://avatars.githubusercontent.com/u/65291464?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/masayil",
    "html_url": "https://github.com/masayil",
    "followers_url": "https://api.github.com/users/masayil/followers",
    "following_url": "https://api.github.com/users/masayil/following{/other_user}",
    "gists_url": "https://api.github.com/users/masayil/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/masayil/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/masayil/subscriptions",
    "organizations_url": "https://api.github.com/users/masayil/orgs",
    "repos_url": "https://api.github.com/users/masayil/repos",
    "events_url": "https://api.github.com/users/masayil/events{/privacy}",
    "received_events_url": "https://api.github.com/users/masayil/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [
    {
      "id": 2907832490,
      "node_id": "MDU6TGFiZWwyOTA3ODMyNDkw",
      "url": "https://api.github.com/repos/ethereum-optimism/optimism/labels/C-bug",
      "name": "C-bug",
      "color": "C5DEF5",
      "default": false,
      "description": "Category: This is a bug."
    },
    {
      "id": 2930018676,
      "node_id": "MDU6TGFiZWwyOTMwMDE4Njc2",
      "url": "https://api.github.com/repos/ethereum-optimism/optimism/labels/P-unconfirmed",
      "name": "P-unconfirmed",
      "color": "BFD4F2",
      "default": false,
      "description": "Issue might be valid, but it’s not yet confirmed"
    },
    {
      "id": 3357535896,
      "node_id": "MDU6TGFiZWwzMzU3NTM1ODk2",
      "url": "https://api.github.com/repos/ethereum-optimism/optimism/labels/M-l2geth",
      "name": "M-l2geth",
      "color": "FBCA04",
      "default": false,
      "description": "Module: l2geth"
    }
  ],
  "state": "closed",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 2,
  "created_at": "2022-10-11T01:27:01Z",
  "updated_at": "2023-05-23T15:44:19Z",
  "closed_at": "2022-11-15T00:57:57Z",
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "running the node with `gcmode=full`\r\n[log.txt](https://github.com/ethereum-optimism/optimism/files/9750237/log.txt)\r\nstop steps:docker-compose stop -t 300",
  "closed_by": {
    "login": "masayil",
    "id": 65291464,
    "node_id": "MDQ6VXNlcjY1MjkxNDY0",
    "avatar_url": "https://avatars.githubusercontent.com/u/65291464?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/masayil",
    "html_url": "https://github.com/masayil",
    "followers_url": "https://api.github.com/users/masayil/followers",
    "following_url": "https://api.github.com/users/masayil/following{/other_user}",
    "gists_url": "https://api.github.com/users/masayil/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/masayil/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/masayil/subscriptions",
    "organizations_url": "https://api.github.com/users/masayil/orgs",
    "repos_url": "https://api.github.com/users/masayil/repos",
    "events_url": "https://api.github.com/users/masayil/events{/privacy}",
    "received_events_url": "https://api.github.com/users/masayil/received_events",
    "type": "User",
    "site_admin": false
  },
  "reactions": {
    "url": "https://api.github.com/repos/ethereum-optimism/optimism/issues/3686/reactions",
    "total_count": 1,
    "+1": 1,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/ethereum-optimism/optimism/issues/3686/timeline",
  "performed_via_github_app": null,
  "state_reason": "completed"
}
[
  {
    "url": "https://api.github.com/repos/ethereum-optimism/optimism/issues/comments/1274594940",
    "html_url": "https://github.com/ethereum-optimism/optimism/issues/3686#issuecomment-1274594940",
    "issue_url": "https://api.github.com/repos/ethereum-optimism/optimism/issues/3686",
    "id": 1274594940,
    "node_id": "IC_kwDODjvEJM5L-MZ8",
    "user": {
      "login": "masayil",
      "id": 65291464,
      "node_id": "MDQ6VXNlcjY1MjkxNDY0",
      "avatar_url": "https://avatars.githubusercontent.com/u/65291464?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/masayil",
      "html_url": "https://github.com/masayil",
      "followers_url": "https://api.github.com/users/masayil/followers",
      "following_url": "https://api.github.com/users/masayil/following{/other_user}",
      "gists_url": "https://api.github.com/users/masayil/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/masayil/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/masayil/subscriptions",
      "organizations_url": "https://api.github.com/users/masayil/orgs",
      "repos_url": "https://api.github.com/users/masayil/repos",
      "events_url": "https://api.github.com/users/masayil/events{/privacy}",
      "received_events_url": "https://api.github.com/users/masayil/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-10-11T12:19:12Z",
    "updated_at": "2022-10-11T12:19:12Z",
    "author_association": "NONE",
    "body": "Also, when I restart the node, it fails to sync\r\n<details><summary>log</summary>\r\n<p>\r\n\r\n\r\n\r\n```bash\r\nINFO [10-10|03:25:58.198] Syncing transaction range                start=2913829 end=7962835 backend=l2\r\nDEBUG[10-10|03:25:58.201] Applying transaction to tip              index=2913829 hash=0x0f26f4293b7aab41ccd25974b81b3f3e93659145d8654551239b7031119d3147 origin=sequencer\r\nDEBUG[10-10|03:25:58.201] Attempting to commit rollup transaction  hash=0x0f26f4293b7aab41ccd25974b81b3f3e93659145d8654551239b7031119d3147\r\nDEBUG[10-10|03:25:58.202] Transaction failed, account skipped      hash=0f26f4…9d3147 err=\"insufficient balance for transfer\"\r\nERROR[10-10|03:25:58.202] Problem committing transaction           msg=\"insufficient balance for transfer\"\r\nERROR[10-10|03:25:58.203] Got error waiting for transaction to be added to chain msg=\"insufficient balance for transfer\"\r\nERROR[10-10|03:25:58.203] Could not verify                         error=\"Verifier cannot sync transactions with BackendL2: Verifier cannot sync transactions with backend l2: Cannot sync transactions with backend l2: Cannot apply transaction: insufficient balance for transfer\"\r\nINFO [10-10|03:25:59.199] Syncing transaction range                start=2913829 end=7963000 backend=l2\r\nDEBUG[10-10|03:25:59.202] Applying transaction to tip              index=2913829 hash=0x0f26f4293b7aab41ccd25974b81b3f3e93659145d8654551239b7031119d3147 origin=sequencer\r\nDEBUG[10-10|03:25:59.202] Attempting to commit rollup transaction  hash=0x0f26f4293b7aab41ccd25974b81b3f3e93659145d8654551239b7031119d3147\r\nDEBUG[10-10|03:25:59.204] Transaction failed, account skipped      hash=0f26f4…9d3147 err=\"insufficient balance for transfer\"\r\nERROR[10-10|03:25:59.204] Problem committing transaction           msg=\"insufficient balance for transfer\"\r\nERROR[10-10|03:25:59.204] Got error waiting for transaction to be added to chain msg=\"insufficient balance for transfer\"\r\nERROR[10-10|03:25:59.204] Could not verify                         error=\"Verifier cannot sync transactions with BackendL2: Verifier cannot sync transactions with backend l2: Cannot sync transactions with backend l2: Cannot apply transaction: insufficient balance for transfer\"\r\nINFO [10-10|03:26:00.198] Syncing transaction range                start=2913829 end=7963000 backend=l2\r\nDEBUG[10-10|03:26:00.202] Applying transaction to tip              index=2913829 hash=0x0f26f4293b7aab41ccd25974b81b3f3e93659145d8654551239b7031119d3147 origin=sequencer\r\nDEBUG[10-10|03:26:00.202] Attempting to commit rollup transaction  hash=0x0f26f4293b7aab41ccd25974b81b3f3e93659145d8654551239b7031119d3147\r\nDEBUG[10-10|03:26:00.203] Transaction failed, account skipped      hash=0f26f4…9d3147 err=\"insufficient balance for transfer\"\r\nERROR[10-10|03:26:00.203] Problem committing transaction           msg=\"insufficient balance for transfer\"\r\nERROR[10-10|03:26:00.203] Got error waiting for transaction to be added to chain msg=\"insufficient balance for transfer\"\r\nERROR[10-10|03:26:00.203] Could not verify                         error=\"Verifier cannot sync transactions with BackendL2: Verifier cannot sync transactions with backend l2: Cannot sync transactions with backend l2: Cannot apply transaction: insufficient balance for transfer\"\r\nINFO [10-10|03:26:01.199] Syncing transaction range                start=2913829 end=7963000 backend=l2\r\nDEBUG[10-10|03:26:01.203] Applying transaction to tip              index=2913829 hash=0x0f26f4293b7aab41ccd25974b81b3f3e93659145d8654551239b7031119d3147 origin=sequencer\r\nDEBUG[10-10|03:26:01.203] Attempting to commit rollup transaction  hash=0x0f26f4293b7aab41ccd25974b81b3f3e93659145d8654551239b7031119d3147\r\nDEBUG[10-10|03:26:01.204] Transaction failed, account skipped      hash=0f26f4…9d3147 err=\"insufficient balance for transfer\"\r\nERROR[10-10|03:26:01.204] Problem committing transaction           msg=\"insufficient balance for transfer\"\r\nERROR[10-10|03:26:01.204] Got error waiting for transaction to be added to chain msg=\"insufficient balance for transfer\"\r\nERROR[10-10|03:26:01.204] Could not verify                         error=\"Verifier cannot sync transactions with BackendL2: Verifier cannot sync transactions with backend l2: Cannot sync transactions with backend l2: Cannot apply transaction: insufficient balance for transfer\"\r\n```\r\n\r\n</p>\r\n</details>",
    "reactions": {
      "url": "https://api.github.com/repos/ethereum-optimism/optimism/issues/comments/1274594940/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ethereum-optimism/optimism/issues/comments/1559699592",
    "html_url": "https://github.com/ethereum-optimism/optimism/issues/3686#issuecomment-1559699592",
    "issue_url": "https://api.github.com/repos/ethereum-optimism/optimism/issues/3686",
    "id": 1559699592,
    "node_id": "IC_kwDODjvEJM5c9yCI",
    "user": {
      "login": "popconst",
      "id": 118303999,
      "node_id": "U_kgDOBw0s_w",
      "avatar_url": "https://avatars.githubusercontent.com/u/118303999?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/popconst",
      "html_url": "https://github.com/popconst",
      "followers_url": "https://api.github.com/users/popconst/followers",
      "following_url": "https://api.github.com/users/popconst/following{/other_user}",
      "gists_url": "https://api.github.com/users/popconst/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/popconst/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/popconst/subscriptions",
      "organizations_url": "https://api.github.com/users/popconst/orgs",
      "repos_url": "https://api.github.com/users/popconst/repos",
      "events_url": "https://api.github.com/users/popconst/events{/privacy}",
      "received_events_url": "https://api.github.com/users/popconst/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2023-05-23T15:44:19Z",
    "updated_at": "2023-05-23T15:44:19Z",
    "author_association": "NONE",
    "body": "Same thing. \r\n\r\nOnce I stop the geth (via systemd or CTRL+C) it often breaks and I am getting this error: \r\n\r\n```\r\nMay 23 17:41:59 Ubuntu-2204-jammy-amd64-base bash[172931]: INFO [05-23|17:41:59.824] Syncing transaction range                start=108515 end=100809655 backend=l2\r\nMay 23 17:41:59 Ubuntu-2204-jammy-amd64-base bash[172931]: ERROR[05-23|17:41:59.825] Problem committing transaction           msg=\"nonce too high\"\r\nMay 23 17:41:59 Ubuntu-2204-jammy-amd64-base bash[172931]: ERROR[05-23|17:41:59.825] Got error waiting for transaction to be added to chain msg=\"nonce too high\"\r\n```\r\n",
    "reactions": {
      "url": "https://api.github.com/repos/ethereum-optimism/optimism/issues/comments/1559699592/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  }
]
