{
  "url": "https://api.github.com/repos/ConsenSys/teku/issues/6170",
  "repository_url": "https://api.github.com/repos/ConsenSys/teku",
  "labels_url": "https://api.github.com/repos/ConsenSys/teku/issues/6170/labels{/name}",
  "comments_url": "https://api.github.com/repos/ConsenSys/teku/issues/6170/comments",
  "events_url": "https://api.github.com/repos/ConsenSys/teku/issues/6170/events",
  "html_url": "https://github.com/ConsenSys/teku/issues/6170",
  "id": 1365260170,
  "node_id": "I_kwDOCM9I9M5RYDeK",
  "number": 6170,
  "title": "Recover gracefully from missed deposits",
  "user": {
    "login": "rolfyone",
    "id": 2967240,
    "node_id": "MDQ6VXNlcjI5NjcyNDA=",
    "avatar_url": "https://avatars.githubusercontent.com/u/2967240?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/rolfyone",
    "html_url": "https://github.com/rolfyone",
    "followers_url": "https://api.github.com/users/rolfyone/followers",
    "following_url": "https://api.github.com/users/rolfyone/following{/other_user}",
    "gists_url": "https://api.github.com/users/rolfyone/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/rolfyone/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/rolfyone/subscriptions",
    "organizations_url": "https://api.github.com/users/rolfyone/orgs",
    "repos_url": "https://api.github.com/users/rolfyone/repos",
    "events_url": "https://api.github.com/users/rolfyone/events{/privacy}",
    "received_events_url": "https://api.github.com/users/rolfyone/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [
    {
      "id": 1048919131,
      "node_id": "MDU6TGFiZWwxMDQ4OTE5MTMx",
      "url": "https://api.github.com/repos/ConsenSys/teku/labels/enhancement%20%F0%9F%95%B5%EF%B8%8F%E2%80%8D%E2%99%80%EF%B8%8F",
      "name": "enhancement üïµÔ∏è‚Äç‚ôÄÔ∏è",
      "color": "a2eeef",
      "default": false,
      "description": "New feature or request"
    }
  ],
  "state": "open",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 10,
  "created_at": "2022-09-07T22:28:14Z",
  "updated_at": "2023-02-06T02:59:21Z",
  "closed_at": null,
  "author_association": "CONTRIBUTOR",
  "active_lock_reason": null,
  "body": "When processing eth1 deposits, there are failure scenarios where we are processing through a list and between batches the eth1 client has a problem, and comes back in a different state.\n\nIn this scenario, we need to be able to recover gracefully.\n\n#6155 is an example of such an occurrence, where we are in the middle of processing, and the client is no longer able to provide deposits that it should have.\n\nA restart does fix the problem when it occurs, but it would be far better for teku to detect, wait, and retry.",
  "closed_by": null,
  "reactions": {
    "url": "https://api.github.com/repos/ConsenSys/teku/issues/6170/reactions",
    "total_count": 3,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 3
  },
  "timeline_url": "https://api.github.com/repos/ConsenSys/teku/issues/6170/timeline",
  "performed_via_github_app": null,
  "state_reason": null
}
[
  {
    "url": "https://api.github.com/repos/ConsenSys/teku/issues/comments/1273952450",
    "html_url": "https://github.com/ConsenSys/teku/issues/6170#issuecomment-1273952450",
    "issue_url": "https://api.github.com/repos/ConsenSys/teku/issues/6170",
    "id": 1273952450,
    "node_id": "IC_kwDOCM9I9M5L7vjC",
    "user": {
      "login": "shaddamciv",
      "id": 92191590,
      "node_id": "U_kgDOBX67Zg",
      "avatar_url": "https://avatars.githubusercontent.com/u/92191590?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/shaddamciv",
      "html_url": "https://github.com/shaddamciv",
      "followers_url": "https://api.github.com/users/shaddamciv/followers",
      "following_url": "https://api.github.com/users/shaddamciv/following{/other_user}",
      "gists_url": "https://api.github.com/users/shaddamciv/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/shaddamciv/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/shaddamciv/subscriptions",
      "organizations_url": "https://api.github.com/users/shaddamciv/orgs",
      "repos_url": "https://api.github.com/users/shaddamciv/repos",
      "events_url": "https://api.github.com/users/shaddamciv/events{/privacy}",
      "received_events_url": "https://api.github.com/users/shaddamciv/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-10-11T00:51:09Z",
    "updated_at": "2022-10-11T00:51:09Z",
    "author_association": "NONE",
    "body": "Adding here, since #6155 is closed. Also for anyone that runs into the same issue post restart - \r\n\r\nI restarted both teku and besu, however teku still shows the same FATAL error message. \r\nHowever, after I upgraded to latest besu version of 22.7.6, the logs seem to have cleared.\r\n\r\nteku version - teku/v22.9.1+4-ge61f57d/linux-x86_64/-privatebuild-openjdk64bitservervm-java-17\r\n\r\n```\r\n16:39 : 2022-10-11 07:16:39.562 INFO  - Loading deposits up to Eth1 block 15718546\r\nOct 11 07:16:40 : 2022-10-11 07:16:40.981 FATAL - PLEASE CHECK YOUR ETH1 NODE | Encountered a problem retrieving deposit events from eth1 endpoint: Expected next deposit at index 450831, but got 450832\r\nOct 11 07:16:40 : tech.pegasys.teku.ethereum.pow.api.InvalidDepositEventsException: Expected next deposit at index 450831, but got 450832\r\nOct 11 07:16:40 : at tech.pegasys.teku.ethereum.pow.api.InvalidDepositEventsException.expectedDepositAtIndex(InvalidDepositEventsException.java:26) ~[teku-ethereum-pow-api-develop.jar:22.9.1+4-ge61f57d]\r\nOct 11 07:16:40 : at tech.pegasys.teku.beacon.pow.ValidatingEth1EventsPublisher.assertDepositEventIsValid(ValidatingEth1EventsPublisher.java:56) ~[teku-beacon-pow-develop.jar:22.9.1+4-ge61f57d]\r\nOct 11 07:16:40 : at tech.pegasys.teku.beacon.pow.ValidatingEth1EventsPublisher.onDepositsFromBlock(ValidatingEth1EventsPublisher.java:46) ~[teku-beacon-pow-develop.jar:22.9.1+4-ge61f57d]\r\nOct 11 07:16:40 : at tech.pegasys.teku.beacon.pow.DepositFetcher.postDeposits(DepositFetcher.java:226) ~[teku-beacon-pow-develop.jar:22.9.1+4-ge61f57d]\r\nOct 11 07:16:40 : at tech.pegasys.teku.beacon.pow.DepositFetcher.postEventsForBlock(DepositFetcher.java:192) ~[teku-beacon-pow-develop.jar:22.9.1+4-ge61f57d]\r\nOct 11 07:16:40 : at tech.pegasys.teku.beacon.pow.DepositFetcher.postDepositEvents(DepositFetcher.java:163) ~[teku-beacon-pow-develop.jar:22.9.1+4-ge61f57d]\r\nOct 11 07:16:40 : at tech.pegasys.teku.beacon.pow.DepositFetcher.lambda$postDepositEvents$4(DepositFetcher.java:179) ~[teku-beacon-pow-develop.jar:22.9.1+4-ge61f57d]\r\nOct 11 07:16:40 : at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]\r\nOct 11 07:16:40 : at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]\r\nOct 11 07:16:40 : at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]\r\nOct 11 07:16:40 : at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:147) ~[teku-infrastructure-async-develop.jar:22.9.1+4-ge61f57d]\r\nOct 11 07:16:40 : at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]\r\nOct 11 07:16:40 : at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]\r\nOct 11 07:16:40 : at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]\r\nOct 11 07:16:40 : at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]\r\nOct 11 07:16:40 : at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:147) ~[teku-infrastructure-async-develop.jar:22.9.1+4-ge61f57d]\r\nOct 11 07:16:40 : at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]\r\nOct 11 07:16:40 : at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:887) ~[?:?]\r\nOct 11 07:16:40 : at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2325) ~[?:?]\r\nOct 11 07:16:40 : at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:580) ~[teku-infrastructure-async-develop.jar:22.9.1+4-ge61f57d]\r\nOct 11 07:16:40 : at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:32) ~[teku-infrastructure-async-develop.jar:22.9.1+4-ge61f57d]\r\nOct 11 07:16:40 : at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateResult(SafeFuture.java:142) ~[teku-infrastructure-async-develop.jar:22.9.1+4-ge61f57d]\r\nOct 11 07:16:40 : at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$exceptionallyCompose$30(SafeFuture.java:399) ~[teku-infrastructure-async-develop.jar:22.9.1+4-ge61f57d]\r\nOct 11 07:16:40 : at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]\r\nOct 11 07:16:40 : at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]\r\nOct 11 07:16:40 : at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]\r\nOct 11 07:16:40 : at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]\r\nOct 11 07:16:40 : at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:147) ~[teku-infrastructure-async-develop.jar:22.9.1+4-ge61f57d]\r\nOct 11 07:16:40 : at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]\r\nOct 11 07:16:40 : at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:887) ~[?:?]\r\nOct 11 07:16:40 : at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2325) ~[?:?]\r\nOct 11 07:16:40 : at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:580) ~[teku-infrastructure-async-develop.jar:22.9.1+4-ge61f57d]\r\nOct 11 07:16:40 : at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:32) ~[teku-infrastructure-async-develop.jar:22.9.1+4-ge61f57d]\r\nOct 11 07:16:40 : at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateResult(SafeFuture.java:142) ~[teku-infrastructure-async-develop.jar:22.9.1+4-ge61f57d]\r\nOct 11 07:16:40 : at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$exceptionallyCompose$30(SafeFuture.java:399) ~[teku-infrastructure-async-develop.jar:22.9.1+4-ge61f57d]\r\nOct 11 07:16:40 : at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]\r\nOct 11 07:16:40 : at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]\r\nOct 11 07:16:40 : at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]\r\nOct 11 07:16:40 : at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]\r\nOct 11 07:16:40 : at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:147) ~[teku-infrastructure-async-develop.jar:22.9.1+4-ge61f57d]\r\nOct 11 07:16:40 : at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]\r\nOct 11 07:16:40 : at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:887) ~[?:?]\r\nOct 11 07:16:40 : at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2325) ~[?:?]\r\nOct 11 07:16:40 : at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:580) ~[teku-infrastructure-async-develop.jar:22.9.1+4-ge61f57d]\r\nOct 11 07:16:40 : at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:32) ~[teku-infrastructure-async-develop.jar:22.9.1+4-ge61f57d]\r\nOct 11 07:16:40 : at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateResult(SafeFuture.java:142) ~[teku-infrastructure-async-develop.jar:22.9.1+4-ge61f57d]\r\nOct 11 07:16:40 : at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$exceptionallyCompose$30(SafeFuture.java:399) ~[teku-infrastructure-async-develop.jar:22.9.1+4-ge61f57d]\r\nOct 11 07:16:40 : at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]\r\nOct 11 07:16:40 : at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]\r\nOct 11 07:16:40 : at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]\r\nOct 11 07:16:40 : at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]\r\nOct 11 07:16:40 : at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:147) ~[teku-infrastructure-async-develop.jar:22.9.1+4-ge61f57d]\r\nOct 11 07:16:40 : at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]\r\nOct 11 07:16:40 : at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]\r\nOct 11 07:16:40 : at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]\r\nOct 11 07:16:40 : at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]\r\nOct 11 07:16:40 : at org.web3j.utils.Async.lambda$run$1(Async.java:38) ~[core-4.9.3.jar:?]\r\nOct 11 07:16:40 : at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]\r\nOct 11 07:16:40 : at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]\r\nOct 11 07:16:40 : at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]\r\nOct 11 07:16:40 : at java.lang.Thread.run(Thread.java:833) ~[?:?]\r\n```",
    "reactions": {
      "url": "https://api.github.com/repos/ConsenSys/teku/issues/comments/1273952450/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ConsenSys/teku/issues/comments/1330381322",
    "html_url": "https://github.com/ConsenSys/teku/issues/6170#issuecomment-1330381322",
    "issue_url": "https://api.github.com/repos/ConsenSys/teku/issues/6170",
    "id": 1330381322,
    "node_id": "IC_kwDOCM9I9M5PTAIK",
    "user": {
      "login": "q9f",
      "id": 58883403,
      "node_id": "MDQ6VXNlcjU4ODgzNDAz",
      "avatar_url": "https://avatars.githubusercontent.com/u/58883403?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/q9f",
      "html_url": "https://github.com/q9f",
      "followers_url": "https://api.github.com/users/q9f/followers",
      "following_url": "https://api.github.com/users/q9f/following{/other_user}",
      "gists_url": "https://api.github.com/users/q9f/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/q9f/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/q9f/subscriptions",
      "organizations_url": "https://api.github.com/users/q9f/orgs",
      "repos_url": "https://api.github.com/users/q9f/repos",
      "events_url": "https://api.github.com/users/q9f/events{/privacy}",
      "received_events_url": "https://api.github.com/users/q9f/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-11-29T10:05:26Z",
    "updated_at": "2022-11-29T10:05:26Z",
    "author_association": "CONTRIBUTOR",
    "body": "I'm facing the same issue which affects my Goerli validators. Please let me know if there is anything I can provide.\r\n\r\nBesu 22.10.0, Teku 22.11.0",
    "reactions": {
      "url": "https://api.github.com/repos/ConsenSys/teku/issues/comments/1330381322/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ConsenSys/teku/issues/comments/1334769566",
    "html_url": "https://github.com/ConsenSys/teku/issues/6170#issuecomment-1334769566",
    "issue_url": "https://api.github.com/repos/ConsenSys/teku/issues/6170",
    "id": 1334769566,
    "node_id": "IC_kwDOCM9I9M5Pjvee",
    "user": {
      "login": "q9f",
      "id": 58883403,
      "node_id": "MDQ6VXNlcjU4ODgzNDAz",
      "avatar_url": "https://avatars.githubusercontent.com/u/58883403?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/q9f",
      "html_url": "https://github.com/q9f",
      "followers_url": "https://api.github.com/users/q9f/followers",
      "following_url": "https://api.github.com/users/q9f/following{/other_user}",
      "gists_url": "https://api.github.com/users/q9f/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/q9f/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/q9f/subscriptions",
      "organizations_url": "https://api.github.com/users/q9f/orgs",
      "repos_url": "https://api.github.com/users/q9f/repos",
      "events_url": "https://api.github.com/users/q9f/events{/privacy}",
      "received_events_url": "https://api.github.com/users/q9f/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-12-02T05:06:37Z",
    "updated_at": "2022-12-02T05:06:37Z",
    "author_association": "CONTRIBUTOR",
    "body": "Is there any way to recover from this? My Prater validators are suffering big time. :(",
    "reactions": {
      "url": "https://api.github.com/repos/ConsenSys/teku/issues/comments/1334769566/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ConsenSys/teku/issues/comments/1336512229",
    "html_url": "https://github.com/ConsenSys/teku/issues/6170#issuecomment-1336512229",
    "issue_url": "https://api.github.com/repos/ConsenSys/teku/issues/6170",
    "id": 1336512229,
    "node_id": "IC_kwDOCM9I9M5PqY7l",
    "user": {
      "login": "ajsutton",
      "id": 72675,
      "node_id": "MDQ6VXNlcjcyNjc1",
      "avatar_url": "https://avatars.githubusercontent.com/u/72675?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ajsutton",
      "html_url": "https://github.com/ajsutton",
      "followers_url": "https://api.github.com/users/ajsutton/followers",
      "following_url": "https://api.github.com/users/ajsutton/following{/other_user}",
      "gists_url": "https://api.github.com/users/ajsutton/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ajsutton/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ajsutton/subscriptions",
      "organizations_url": "https://api.github.com/users/ajsutton/orgs",
      "repos_url": "https://api.github.com/users/ajsutton/repos",
      "events_url": "https://api.github.com/users/ajsutton/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ajsutton/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-12-04T20:40:34Z",
    "updated_at": "2022-12-04T20:40:34Z",
    "author_association": "CONTRIBUTOR",
    "body": "@q9f Step one is to fix the EL to ensure it is returning all deposits. Sometimes this happens automatically because its as just syncing or temporary, sometimes there's other issues that need to be fixed.  Then restart Teku and it will begin requesting deposits from the last one it successfully imported and should pick up the missed deposits.",
    "reactions": {
      "url": "https://api.github.com/repos/ConsenSys/teku/issues/comments/1336512229/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ConsenSys/teku/issues/comments/1377067026",
    "html_url": "https://github.com/ConsenSys/teku/issues/6170#issuecomment-1377067026",
    "issue_url": "https://api.github.com/repos/ConsenSys/teku/issues/6170",
    "id": 1377067026,
    "node_id": "IC_kwDOCM9I9M5SFGAS",
    "user": {
      "login": "q9f",
      "id": 58883403,
      "node_id": "MDQ6VXNlcjU4ODgzNDAz",
      "avatar_url": "https://avatars.githubusercontent.com/u/58883403?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/q9f",
      "html_url": "https://github.com/q9f",
      "followers_url": "https://api.github.com/users/q9f/followers",
      "following_url": "https://api.github.com/users/q9f/following{/other_user}",
      "gists_url": "https://api.github.com/users/q9f/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/q9f/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/q9f/subscriptions",
      "organizations_url": "https://api.github.com/users/q9f/orgs",
      "repos_url": "https://api.github.com/users/q9f/repos",
      "events_url": "https://api.github.com/users/q9f/events{/privacy}",
      "received_events_url": "https://api.github.com/users/q9f/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2023-01-10T10:49:26Z",
    "updated_at": "2023-01-10T10:49:26Z",
    "author_association": "CONTRIBUTOR",
    "body": "There is a chicken and egg problem though. I cannot fix the EL without a CL connected.\r\n\r\nUnfortunately, I have to switch to a different consensus client now, I can no longer maintain this setup. :(",
    "reactions": {
      "url": "https://api.github.com/repos/ConsenSys/teku/issues/comments/1377067026/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ConsenSys/teku/issues/comments/1380252488",
    "html_url": "https://github.com/ConsenSys/teku/issues/6170#issuecomment-1380252488",
    "issue_url": "https://api.github.com/repos/ConsenSys/teku/issues/6170",
    "id": 1380252488,
    "node_id": "IC_kwDOCM9I9M5SRPtI",
    "user": {
      "login": "benjaminion",
      "id": 20796281,
      "node_id": "MDQ6VXNlcjIwNzk2Mjgx",
      "avatar_url": "https://avatars.githubusercontent.com/u/20796281?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/benjaminion",
      "html_url": "https://github.com/benjaminion",
      "followers_url": "https://api.github.com/users/benjaminion/followers",
      "following_url": "https://api.github.com/users/benjaminion/following{/other_user}",
      "gists_url": "https://api.github.com/users/benjaminion/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/benjaminion/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/benjaminion/subscriptions",
      "organizations_url": "https://api.github.com/users/benjaminion/orgs",
      "repos_url": "https://api.github.com/users/benjaminion/repos",
      "events_url": "https://api.github.com/users/benjaminion/events{/privacy}",
      "received_events_url": "https://api.github.com/users/benjaminion/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2023-01-12T12:25:05Z",
    "updated_at": "2023-01-12T12:25:05Z",
    "author_association": "CONTRIBUTOR",
    "body": "@q9f I've raised this up the backlog, but we've been fully maxed on protocol updates and other high priority features for a while.\n\n@ajsutton's point still stands - this situation only arises when the execution client misbehaves. If (1) it's temporary misbehaviour by the EL, then restarting Teku should clear it and all will be well. We could also try to recover automatically in this case, as per this ticket. However, (2) if the exec client is buggy or in a bad state, there's nothing we can do to recover on the Teku side. That's what Adrian means by \"fix the EL\" I think. This is the most common situation we see in the wild. But generally I'm not having any trouble with recent versions of Besu.",
    "reactions": {
      "url": "https://api.github.com/repos/ConsenSys/teku/issues/comments/1380252488/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ConsenSys/teku/issues/comments/1380349247",
    "html_url": "https://github.com/ConsenSys/teku/issues/6170#issuecomment-1380349247",
    "issue_url": "https://api.github.com/repos/ConsenSys/teku/issues/6170",
    "id": 1380349247,
    "node_id": "IC_kwDOCM9I9M5SRnU_",
    "user": {
      "login": "q9f",
      "id": 58883403,
      "node_id": "MDQ6VXNlcjU4ODgzNDAz",
      "avatar_url": "https://avatars.githubusercontent.com/u/58883403?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/q9f",
      "html_url": "https://github.com/q9f",
      "followers_url": "https://api.github.com/users/q9f/followers",
      "following_url": "https://api.github.com/users/q9f/following{/other_user}",
      "gists_url": "https://api.github.com/users/q9f/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/q9f/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/q9f/subscriptions",
      "organizations_url": "https://api.github.com/users/q9f/orgs",
      "repos_url": "https://api.github.com/users/q9f/repos",
      "events_url": "https://api.github.com/users/q9f/events{/privacy}",
      "received_events_url": "https://api.github.com/users/q9f/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2023-01-12T13:22:51Z",
    "updated_at": "2023-01-12T13:22:51Z",
    "author_association": "CONTRIBUTOR",
    "body": "But it's a chicken an egg problem. Once the CL fails, the EL also stalls. There is no such thing as \"fixing the EL\" without fixing the CL.\n\nAnd my Besu node is not complaining. It just basically sits and waits for Teku to come back.",
    "reactions": {
      "url": "https://api.github.com/repos/ConsenSys/teku/issues/comments/1380349247/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ConsenSys/teku/issues/comments/1380592832",
    "html_url": "https://github.com/ConsenSys/teku/issues/6170#issuecomment-1380592832",
    "issue_url": "https://api.github.com/repos/ConsenSys/teku/issues/6170",
    "id": 1380592832,
    "node_id": "IC_kwDOCM9I9M5SSizA",
    "user": {
      "login": "benjaminion",
      "id": 20796281,
      "node_id": "MDQ6VXNlcjIwNzk2Mjgx",
      "avatar_url": "https://avatars.githubusercontent.com/u/20796281?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/benjaminion",
      "html_url": "https://github.com/benjaminion",
      "followers_url": "https://api.github.com/users/benjaminion/followers",
      "following_url": "https://api.github.com/users/benjaminion/following{/other_user}",
      "gists_url": "https://api.github.com/users/benjaminion/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/benjaminion/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/benjaminion/subscriptions",
      "organizations_url": "https://api.github.com/users/benjaminion/orgs",
      "repos_url": "https://api.github.com/users/benjaminion/repos",
      "events_url": "https://api.github.com/users/benjaminion/events{/privacy}",
      "received_events_url": "https://api.github.com/users/benjaminion/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2023-01-12T15:48:32Z",
    "updated_at": "2023-01-12T15:48:32Z",
    "author_association": "CONTRIBUTOR",
    "body": "Not really, in my experience. This issue occurs because the EL client has provided bad (incomplete) data, but it doesn't know that it has done so, hence it reports no errors. This can sometimes be resolved by restarting the EL client to clear whatever state it's got itself into, and then the CL client so that it re-requests the data. But sometimes it's due to an EL client bug and needs a genuine software fix. There's not a lot Teku can do in either of these situations. If it's simply a transient issue then it's possible that Teku can recover just by asking for the data again, and we'll look at implementing this, but I suspect it will likely help in only some circumstances.",
    "reactions": {
      "url": "https://api.github.com/repos/ConsenSys/teku/issues/comments/1380592832/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ConsenSys/teku/issues/comments/1380663416",
    "html_url": "https://github.com/ConsenSys/teku/issues/6170#issuecomment-1380663416",
    "issue_url": "https://api.github.com/repos/ConsenSys/teku/issues/6170",
    "id": 1380663416,
    "node_id": "IC_kwDOCM9I9M5SS0B4",
    "user": {
      "login": "q9f",
      "id": 58883403,
      "node_id": "MDQ6VXNlcjU4ODgzNDAz",
      "avatar_url": "https://avatars.githubusercontent.com/u/58883403?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/q9f",
      "html_url": "https://github.com/q9f",
      "followers_url": "https://api.github.com/users/q9f/followers",
      "following_url": "https://api.github.com/users/q9f/following{/other_user}",
      "gists_url": "https://api.github.com/users/q9f/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/q9f/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/q9f/subscriptions",
      "organizations_url": "https://api.github.com/users/q9f/orgs",
      "repos_url": "https://api.github.com/users/q9f/repos",
      "events_url": "https://api.github.com/users/q9f/events{/privacy}",
      "received_events_url": "https://api.github.com/users/q9f/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2023-01-12T16:20:15Z",
    "updated_at": "2023-01-12T16:20:15Z",
    "author_association": "CONTRIBUTOR",
    "body": "Ok, thanks. I replaced Besu with Geth and see if this is more stable maybe.",
    "reactions": {
      "url": "https://api.github.com/repos/ConsenSys/teku/issues/comments/1380663416/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ConsenSys/teku/issues/comments/1418431732",
    "html_url": "https://github.com/ConsenSys/teku/issues/6170#issuecomment-1418431732",
    "issue_url": "https://api.github.com/repos/ConsenSys/teku/issues/6170",
    "id": 1418431732,
    "node_id": "IC_kwDOCM9I9M5Ui4z0",
    "user": {
      "login": "smasher816",
      "id": 904012,
      "node_id": "MDQ6VXNlcjkwNDAxMg==",
      "avatar_url": "https://avatars.githubusercontent.com/u/904012?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/smasher816",
      "html_url": "https://github.com/smasher816",
      "followers_url": "https://api.github.com/users/smasher816/followers",
      "following_url": "https://api.github.com/users/smasher816/following{/other_user}",
      "gists_url": "https://api.github.com/users/smasher816/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/smasher816/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/smasher816/subscriptions",
      "organizations_url": "https://api.github.com/users/smasher816/orgs",
      "repos_url": "https://api.github.com/users/smasher816/repos",
      "events_url": "https://api.github.com/users/smasher816/events{/privacy}",
      "received_events_url": "https://api.github.com/users/smasher816/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2023-02-06T02:59:21Z",
    "updated_at": "2023-02-06T02:59:21Z",
    "author_association": "NONE",
    "body": "I'm running into something similar.\r\n```\r\nFeb 05 18:56:11 hoenir teku[29816]: 18:56:11.003 INFO  - Syncing     *** Target slot: 5735679, Head slot: 5735674, Remaining slots: 5, Connected peers: 0\r\nFeb 05 18:56:12 hoenir teku[29816]: 18:56:12.718 FATAL - PLEASE CHECK YOUR ETH1 NODE | Encountered a problem retrieving deposit events from eth1 endpoint: Expected next deposit at index 0, but got 192 tech.pegasys.teku.ethereum.pow.api.InvalidDepositEventsException: Expected next deposit at index 0, but got 192 (See log file for full stack trace)\r\nFeb 05 18:56:14 hoenir teku[29816]: 18:56:14.837 FATAL - PLEASE CHECK YOUR ETH1 NODE | Encountered a problem retrieving deposit events from eth1 endpoint: Expected next deposit at index 0, but got 192 tech.pegasys.teku.ethereum.pow.api.InvalidDepositEventsException: Expected next deposit at index 0, but got 192 (See log file for full stack trace)\r\nFeb 05 18:56:16 hoenir teku[29816]: 18:56:16.957 FATAL - PLEASE CHECK YOUR ETH1 NODE | Encountered a problem retrieving deposit events from eth1 endpoint: Expected next deposit at index 0, but got 192 tech.pegasys.teku.ethereum.pow.api.InvalidDepositEventsException: Expected next deposit at index 0, but got 192 (See log file for full stack trace)\r\nFeb 05 18:56:19 hoenir teku[29816]: 18:56:19.080 FATAL - PLEASE CHECK YOUR ETH1 NODE | Encountered a problem retrieving deposit events from eth1 endpoint: Expected next deposit at index 0, but got 192 tech.pegasys.teku.ethereum.pow.api.InvalidDepositEventsException: Expected next deposit at index 0, but got 192 (See log file for full stack trace)\r\nFeb 05 18:56:21 hoenir teku[29816]: 18:56:21.186 FATAL - PLEASE CHECK YOUR ETH1 NODE | Encountered a problem retrieving deposit events from eth1 endpoint: Expected next deposit at index 0, but got 192 tech.pegasys.teku.ethereum.pow.api.InvalidDepositEventsException: Expected next deposit at index 0, but got 192 (See log file for full stack trace)\r\nFeb 05 18:56:23 hoenir teku[29816]: 18:56:23.316 FATAL - PLEASE CHECK YOUR ETH1 NODE | Encountered a problem retrieving deposit events from eth1 endpoint: Expected next deposit at index 0, but got 192 tech.pegasys.teku.ethereum.pow.api.InvalidDepositEventsException: Expected next deposit at index 0, but got 192 (See log file for full stack trace)\r\nFeb 05 18:56:25 hoenir teku[29816]: 18:56:25.501 FATAL - PLEASE CHECK YOUR ETH1 NODE | Encountered a problem retrieving deposit events from eth1 endpoint: Expected next deposit at index 0, but got 192 tech.pegasys.teku.ethereum.pow.api.InvalidDepositEventsException: Expected next deposit at index 0, but got 192 (See log file for full stack trace)\r\n```\r\n\r\nI have opened up an issue with the EL (nethermind in this instance)\r\nhttps://github.com/NethermindEth/nethermind/issues/5235",
    "reactions": {
      "url": "https://api.github.com/repos/ConsenSys/teku/issues/comments/1418431732/reactions",
      "total_count": 2,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 2
    },
    "performed_via_github_app": null
  }
]
