{
  "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/14883",
  "repository_url": "https://api.github.com/repos/ethereum/go-ethereum",
  "labels_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/14883/labels{/name}",
  "comments_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/14883/comments",
  "events_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/14883/events",
  "html_url": "https://github.com/ethereum/go-ethereum/issues/14883",
  "id": 246780918,
  "node_id": "MDU6SXNzdWUyNDY3ODA5MTg=",
  "number": 14883,
  "title": "Geth Console blocks internet access",
  "user": {
    "login": "ginward",
    "id": 6193977,
    "node_id": "MDQ6VXNlcjYxOTM5Nzc=",
    "avatar_url": "https://avatars.githubusercontent.com/u/6193977?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/ginward",
    "html_url": "https://github.com/ginward",
    "followers_url": "https://api.github.com/users/ginward/followers",
    "following_url": "https://api.github.com/users/ginward/following{/other_user}",
    "gists_url": "https://api.github.com/users/ginward/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/ginward/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/ginward/subscriptions",
    "organizations_url": "https://api.github.com/users/ginward/orgs",
    "repos_url": "https://api.github.com/users/ginward/repos",
    "events_url": "https://api.github.com/users/ginward/events{/privacy}",
    "received_events_url": "https://api.github.com/users/ginward/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [
    {
      "id": 1132689577,
      "node_id": "MDU6TGFiZWwxMTMyNjg5NTc3",
      "url": "https://api.github.com/repos/ethereum/go-ethereum/labels/status:triage",
      "name": "status:triage",
      "color": "6be514",
      "default": false,
      "description": ""
    }
  ],
  "state": "closed",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 2,
  "created_at": "2017-07-31T14:42:40Z",
  "updated_at": "2019-04-02T09:09:04Z",
  "closed_at": "2019-04-02T09:09:04Z",
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "#### System information\r\n\r\nGeth version: \r\n\r\n```\r\nGeth\r\nVersion: 1.6.7-stable\r\nGit Commit: ab5646c532292b51e319f290afccf6a44f874372\r\nArchitecture: amd64\r\nProtocol Versions: [63 62]\r\nNetwork Id: 1\r\nGo Version: go1.8.3\r\nOperating System: darwin\r\nGOPATH=\r\nGOROOT=/usr/local/Cellar/go/1.8.3/libexec\r\n```\r\n\r\nOS & Version: \r\n`MAC OSX 10.12.5`\r\n\r\n#### Expected behaviour\r\nI should able to access internet via browsers or terminal after starting the geth client. \r\n\r\n#### Actual behaviour\r\nHowever, after running `geth console` on terminal, all internet access on my browsers (Safari and Chrome) and pings (ping google.ca) are blocked. They hang for a while and returns nothing.\r\n\r\n#### Steps to reproduce the behaviour\r\nRun geth console on Mac terminal. \r\n",
  "closed_by": {
    "login": "holiman",
    "id": 142290,
    "node_id": "MDQ6VXNlcjE0MjI5MA==",
    "avatar_url": "https://avatars.githubusercontent.com/u/142290?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/holiman",
    "html_url": "https://github.com/holiman",
    "followers_url": "https://api.github.com/users/holiman/followers",
    "following_url": "https://api.github.com/users/holiman/following{/other_user}",
    "gists_url": "https://api.github.com/users/holiman/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/holiman/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/holiman/subscriptions",
    "organizations_url": "https://api.github.com/users/holiman/orgs",
    "repos_url": "https://api.github.com/users/holiman/repos",
    "events_url": "https://api.github.com/users/holiman/events{/privacy}",
    "received_events_url": "https://api.github.com/users/holiman/received_events",
    "type": "User",
    "site_admin": false
  },
  "reactions": {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/14883/reactions",
    "total_count": 1,
    "+1": 1,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/14883/timeline",
  "performed_via_github_app": null,
  "state_reason": "completed"
}
[
  {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/384528542",
    "html_url": "https://github.com/ethereum/go-ethereum/issues/14883#issuecomment-384528542",
    "issue_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/14883",
    "id": 384528542,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM4NDUyODU0Mg==",
    "user": {
      "login": "Swader",
      "id": 1430603,
      "node_id": "MDQ6VXNlcjE0MzA2MDM=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1430603?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Swader",
      "html_url": "https://github.com/Swader",
      "followers_url": "https://api.github.com/users/Swader/followers",
      "following_url": "https://api.github.com/users/Swader/following{/other_user}",
      "gists_url": "https://api.github.com/users/Swader/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Swader/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Swader/subscriptions",
      "organizations_url": "https://api.github.com/users/Swader/orgs",
      "repos_url": "https://api.github.com/users/Swader/repos",
      "events_url": "https://api.github.com/users/Swader/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Swader/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-04-26T06:31:05Z",
    "updated_at": "2018-04-26T07:29:53Z",
    "author_association": "CONTRIBUTOR",
    "body": "Can reproduce. If all consoles are killed, it takes 5 minutes or so for things to clear up and connection starts working again. Should also be noted that while nodes are running (not even consoles) the connection is still deteriorated. It's as if the more geths are running, the worse the connectivity to the outside world.",
    "reactions": {
      "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/384528542/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/478910761",
    "html_url": "https://github.com/ethereum/go-ethereum/issues/14883#issuecomment-478910761",
    "issue_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/14883",
    "id": 478910761,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ3ODkxMDc2MQ==",
    "user": {
      "login": "holiman",
      "id": 142290,
      "node_id": "MDQ6VXNlcjE0MjI5MA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/142290?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/holiman",
      "html_url": "https://github.com/holiman",
      "followers_url": "https://api.github.com/users/holiman/followers",
      "following_url": "https://api.github.com/users/holiman/following{/other_user}",
      "gists_url": "https://api.github.com/users/holiman/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/holiman/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/holiman/subscriptions",
      "organizations_url": "https://api.github.com/users/holiman/orgs",
      "repos_url": "https://api.github.com/users/holiman/repos",
      "events_url": "https://api.github.com/users/holiman/events{/privacy}",
      "received_events_url": "https://api.github.com/users/holiman/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-04-02T09:09:04Z",
    "updated_at": "2019-04-02T09:09:04Z",
    "author_association": "MEMBER",
    "body": "The only reason I can imagine would be that the ISP detects the surge in traffic, or identifies the p2p erroneously as some 'illegal file sharing' and cuts it off. Other than that, it might be that the connection is saturated when geth is syncing. \r\nI'll close this, since I think the causes for this is outside of geth.",
    "reactions": {
      "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/478910761/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  }
]
