{
  "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25680",
  "repository_url": "https://api.github.com/repos/ethereum/go-ethereum",
  "labels_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25680/labels{/name}",
  "comments_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25680/comments",
  "events_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25680/events",
  "html_url": "https://github.com/ethereum/go-ethereum/issues/25680",
  "id": 1361347133,
  "node_id": "I_kwDOAOvK985RJII9",
  "number": 25680,
  "title": "Synchronization stopped with `Error in block freeze operation`",
  "user": {
    "login": "mone-d",
    "id": 96062141,
    "node_id": "U_kgDOBbnKvQ",
    "avatar_url": "https://avatars.githubusercontent.com/u/96062141?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/mone-d",
    "html_url": "https://github.com/mone-d",
    "followers_url": "https://api.github.com/users/mone-d/followers",
    "following_url": "https://api.github.com/users/mone-d/following{/other_user}",
    "gists_url": "https://api.github.com/users/mone-d/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/mone-d/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/mone-d/subscriptions",
    "organizations_url": "https://api.github.com/users/mone-d/orgs",
    "repos_url": "https://api.github.com/users/mone-d/repos",
    "events_url": "https://api.github.com/users/mone-d/events{/privacy}",
    "received_events_url": "https://api.github.com/users/mone-d/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [
    {
      "id": 72233650,
      "node_id": "MDU6TGFiZWw3MjIzMzY1MA==",
      "url": "https://api.github.com/repos/ethereum/go-ethereum/labels/type:bug",
      "name": "type:bug",
      "color": "FF5E5E",
      "default": false,
      "description": ""
    }
  ],
  "state": "open",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 2,
  "created_at": "2022-09-05T02:40:23Z",
  "updated_at": "2023-07-01T19:11:38Z",
  "closed_at": null,
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "#### System information\r\n\r\nGeth version: `1.10.23`\r\nPrysm version: `3.0.0`\r\nOS & Version: Linux\r\nCommit hash : -\r\n\r\n#### Expected behaviour\r\n\r\nNo errors have occurred.\r\n\r\n#### Actual behaviour\r\n\r\nError occurred and block synchronization stopped.\r\n\r\n#### Steps to reproduce the behaviour\r\n\r\nI started geth with new instance. so instance have no old blocks and geth started synchronization from genesis.\r\nGeth finished initial syncing process with snap sync.\r\nSome days later, I found this log and block synchronization is stopped.\r\n`ERROR[09-05|02:07:15.340] Error in block freeze operation          err=\"block receipts missing, can't freeze block 15377501\"`\r\n\r\nMy geth configuration.\r\n\r\ntoml\r\n```\r\n[Eth]\r\n    NetworkId = 1\r\n    SyncMode = \"snap\"\r\n    NoPruning = false\r\n    LightPeers = 100\r\n    DatabaseCache = 768\r\n    TrieCleanCache = 256\r\n    TrieDirtyCache = 256\r\n    TrieTimeout = 3600000000000\r\n    EnablePreimageRecording = false\r\n[Eth.Miner]\r\n    GasFloor = 8000000\r\n    GasCeil = 8000000\r\n    GasPrice = 1000000000\r\n    Recommit = 3000000000\r\n    Noverify = false\r\n\r\n[Eth.Ethash]\r\n    CacheDir = \"ethash\"\r\n    CachesInMem = 2\r\n    CachesOnDisk = 3\r\n    DatasetsInMem = 1\r\n    DatasetsOnDisk = 2\r\n    PowMode = 0\r\n\r\n[Eth.TxPool]\r\n    Locals = []\r\n    NoLocals = false\r\n    Journal = \"transactions.rlp\"\r\n    Rejournal = 3600000000000\r\n    PriceLimit = 1\r\n    PriceBump = 10\r\n    AccountSlots = 16\r\n    GlobalSlots = 4096\r\n    AccountQueue = 64\r\n    GlobalQueue = 1024\r\n    Lifetime = 10800000000000\r\n\r\n[Eth.GPO]\r\n    Blocks = 20\r\n    Percentile = 60\r\n\r\n[Node]\r\n    DataDir             = \"/home/app/.ethereum\"\r\n    IPCPath = \"geth.ipc\"\r\n\r\n    HTTPHost            = \"0.0.0.0\"\r\n    HTTPPort            = 8545\r\n    HTTPCors            = [\"*\"]\r\n    HTTPVirtualHosts    = [\"*\"]\r\n    HTTPModules         = [\"admin\", \"eth\", \"debug\", \"miner\", \"net\", \"txpool\", \"personal\", \"web3\"]\r\n\r\n    WSHost              = \"0.0.0.0\"\r\n    WSPort              = 8546\r\n    WSOrigins           = [\"*\"]\r\n    WSModules           = [\"admin\", \"eth\", \"debug\", \"miner\", \"net\", \"txpool\", \"personal\", \"web3\"]\r\n\r\n[Node.P2P]\r\n    MaxPeers = 100\r\n    NoDiscovery = false\r\n    ListenAddr = \":30303\"\r\n    EnableMsgEvents = false\r\n\r\n[Node.HTTPTimeouts]\r\n    ReadTimeout = 30000000000\r\n    WriteTimeout = 30000000000\r\n    IdleTimeout = 120000000000\r\n\r\n```\r\nStart commands.\r\n```\r\ngeth --config /home/app/.ethereum/config/config.toml --cache 1024 --snapshot=false\r\n```\r\n\r\n#### Backtrace\r\n\r\n````\r\n2022-09-05T11:06:15.337+09:00 | ERROR[09-05\\|02:06:15.337] Error in block freeze operation err=\"block receipts missing, can't freeze block 15377501\"\r\n-- | --\r\n  | 2022-09-05T11:06:32.260+09:00 | INFO [09-05\\|02:06:32.260] Imported new chain segment blocks=1 txs=363 mgas=29.988 elapsed=1.759s mgasps=17.039 number=15,475,174 hash=6c49d8..a7d27a age=1m39s dirty=255.80MiB\r\n  | 2022-09-05T11:06:32.267+09:00 | INFO [09-05\\|02:06:32.267] Unindexed transactions blocks=1 txs=100 tail=13,125,175 elapsed=6.674ms\r\n  | 2022-09-05T11:07:01.776+09:00 | INFO [09-05\\|02:07:01.776] Imported new chain segment blocks=1 txs=326 mgas=29.968 elapsed=416.170ms mgasps=72.008 number=15,475,175 hash=9d7feb..32b5ad dirty=254.61MiB\r\n  | 2022-09-05T11:07:01.784+09:00 | INFO [09-05\\|02:07:01.784] Unindexed transactions blocks=1 txs=326 tail=13,125,176 elapsed=7.418ms\r\n  | 2022-09-05T11:07:08.136+09:00 | INFO [09-05\\|02:07:08.136] Imported new chain segment blocks=1 txs=329 mgas=29.980 elapsed=405.613ms mgasps=73.912 number=15,475,176 hash=d062ad..1f1bea dirty=254.11MiB\r\n  | 2022-09-05T11:07:08.140+09:00 | INFO [09-05\\|02:07:08.139] Unindexed transactions blocks=1 txs=157 tail=13,125,177 elapsed=3.309ms\r\n  | 2022-09-05T11:07:15.340+09:00 | ERROR[09-05\\|02:07:15.340] Error in block freeze operation err=\"block receipts missing, can't freeze block 15377501\"\r\n  | 2022-09-05T11:07:21.936+09:00 | INFO [09-05\\|02:07:21.936] Imported new chain segment blocks=1 txs=416 mgas=29.980 elapsed=754.479ms mgasps=39.736 number=15,475,177 hash=7aa420..188263 dirty=254.53MiB\r\n  | 2022-09-05T11:07:21.940+09:00 | INFO [09-05\\|02:07:21.940] Unindexed transactions blocks=1 txs=115 tail=13,125,178 elapsed=1.800ms\r\n  | 2022-09-05T11:07:33.367+09:00 | INFO [09-05\\|02:07:33.366] Imported new chain segment blocks=1 txs=448 mgas=29.998 elapsed=1.049s mgasps=28.581 number=15,475,178 hash=63238e..e8564d dirty=254.92MiB\r\n  | 2022-09-05T11:07:33.372+09:00 | INFO [09-05\\|02:07:33.371] Unindexed transactions blocks=1 txs=227 tail=13,125,179 elapsed=4.633ms\r\n  | 2022-09-05T11:07:35.624+09:00 | INFO [09-05\\|02:07:35.624] Imported new chain segment blocks=1 txs=346 mgas=26.606 elapsed=565.968ms mgasps=47.010 number=15,475,179 hash=50bb6f..51e64f dirty=254.91MiB\r\n  | 2022-09-05T11:07:35.627+09:00 | INFO [09-05\\|02:07:35.627] Unindexed transactions blocks=1 txs=122 tail=13,125,180 elapsed=2.530ms\r\n  | 2022-09-05T11:08:10.128+09:00 | INFO [09-05\\|02:08:10.128] Imported new chain segment blocks=1 txs=281 mgas=30.044 elapsed=342.043ms mgasps=87.838 number=15,475,180 hash=60ab4c..65a6dd dirty=254.76MiB\r\n  | 2022-09-05T11:08:10.131+09:00 | INFO [09-05\\|02:08:10.131] Unindexed transactions blocks=1 txs=152 tail=13,125,181 elapsed=3.181ms\r\n  | 2022-09-05T11:08:11.069+09:00 | INFO [09-05\\|02:08:11.069] Imported new chain segment blocks=1 txs=185 mgas=19.539 elapsed=654.667ms mgasps=29.846 number=15,475,181 hash=64e629..14dcc9 dirty=255.60MiB\r\n  | 2022-09-05T11:08:11.072+09:00 | INFO [09-05\\|02:08:11.071] Unindexed transactions blocks=1 txs=58 tail=13,125,182 elapsed=1.484ms\r\n  | 2022-09-05T11:08:15.343+09:00 | ERROR[09-05\\|02:08:15.343] Error in block freeze operation err=\"block receipts missing, can't freeze block 15377501\"\r\n````\r\n",
  "closed_by": null,
  "reactions": {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25680/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25680/timeline",
  "performed_via_github_app": null,
  "state_reason": null
}
[
  {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/1238089435",
    "html_url": "https://github.com/ethereum/go-ethereum/issues/25680#issuecomment-1238089435",
    "issue_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25680",
    "id": 1238089435,
    "node_id": "IC_kwDOAOvK985Jy77b",
    "user": {
      "login": "rjl493456442",
      "id": 5959481,
      "node_id": "MDQ6VXNlcjU5NTk0ODE=",
      "avatar_url": "https://avatars.githubusercontent.com/u/5959481?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rjl493456442",
      "html_url": "https://github.com/rjl493456442",
      "followers_url": "https://api.github.com/users/rjl493456442/followers",
      "following_url": "https://api.github.com/users/rjl493456442/following{/other_user}",
      "gists_url": "https://api.github.com/users/rjl493456442/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rjl493456442/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rjl493456442/subscriptions",
      "organizations_url": "https://api.github.com/users/rjl493456442/orgs",
      "repos_url": "https://api.github.com/users/rjl493456442/repos",
      "events_url": "https://api.github.com/users/rjl493456442/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rjl493456442/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-09-06T12:33:56Z",
    "updated_at": "2022-09-06T12:33:56Z",
    "author_association": "MEMBER",
    "body": "The chain progressing is actually still going on. Another background thread for moving blocks from live database(leveldb) to ancient database(flat files) is blocked because of this missing receipts.\r\n\r\nAlso there is not enough information for us to know why it can happen. You can just ignore the error if you don't mind and the data freezing function will be disabled(so all the data will be put in the leveldb), but will recommend to resync if you can allow a few offline time.",
    "reactions": {
      "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/1238089435/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/1616055043",
    "html_url": "https://github.com/ethereum/go-ethereum/issues/25680#issuecomment-1616055043",
    "issue_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25680",
    "id": 1616055043,
    "node_id": "IC_kwDOAOvK985gUwsD",
    "user": {
      "login": "amplicity",
      "id": 2263838,
      "node_id": "MDQ6VXNlcjIyNjM4Mzg=",
      "avatar_url": "https://avatars.githubusercontent.com/u/2263838?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/amplicity",
      "html_url": "https://github.com/amplicity",
      "followers_url": "https://api.github.com/users/amplicity/followers",
      "following_url": "https://api.github.com/users/amplicity/following{/other_user}",
      "gists_url": "https://api.github.com/users/amplicity/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/amplicity/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/amplicity/subscriptions",
      "organizations_url": "https://api.github.com/users/amplicity/orgs",
      "repos_url": "https://api.github.com/users/amplicity/repos",
      "events_url": "https://api.github.com/users/amplicity/events{/privacy}",
      "received_events_url": "https://api.github.com/users/amplicity/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2023-07-01T19:11:38Z",
    "updated_at": "2023-07-01T19:11:38Z",
    "author_association": "NONE",
    "body": "I'm having this same issue, but not sure of the best way to remove the geth db. I know there is `geth removedb`, but my data directory is in a custom location. \r\n\r\nMy geth startup command is:\r\n```\r\n./geth  --http --http.api eth,net,engine,admin --authrpc.jwtsecret ~/ethereum/my-jwt.hex --datadir='~/ethereum/execution/data';\r\n```\r\n\r\nIf I want to get rid of this error, would I run `./geth --datadir='~/ethereum/execution/data' removedb` ?",
    "reactions": {
      "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/1616055043/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  }
]
