{
  "url": "https://api.github.com/repos/foundry-rs/foundry/issues/6892",
  "repository_url": "https://api.github.com/repos/foundry-rs/foundry",
  "labels_url": "https://api.github.com/repos/foundry-rs/foundry/issues/6892/labels{/name}",
  "comments_url": "https://api.github.com/repos/foundry-rs/foundry/issues/6892/comments",
  "events_url": "https://api.github.com/repos/foundry-rs/foundry/issues/6892/events",
  "html_url": "https://github.com/foundry-rs/foundry/issues/6892",
  "id": 2098745499,
  "node_id": "I_kwDOGBlvNc59GFCb",
  "number": 6892,
  "title": "Unknown error when verify contract on Sepolia etherscan",
  "user": {
    "login": "Boyuan-Chen",
    "id": 46272347,
    "node_id": "MDQ6VXNlcjQ2MjcyMzQ3",
    "avatar_url": "https://avatars.githubusercontent.com/u/46272347?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Boyuan-Chen",
    "html_url": "https://github.com/Boyuan-Chen",
    "followers_url": "https://api.github.com/users/Boyuan-Chen/followers",
    "following_url": "https://api.github.com/users/Boyuan-Chen/following{/other_user}",
    "gists_url": "https://api.github.com/users/Boyuan-Chen/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Boyuan-Chen/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Boyuan-Chen/subscriptions",
    "organizations_url": "https://api.github.com/users/Boyuan-Chen/orgs",
    "repos_url": "https://api.github.com/users/Boyuan-Chen/repos",
    "events_url": "https://api.github.com/users/Boyuan-Chen/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Boyuan-Chen/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [
    {
      "id": 3334394228,
      "node_id": "MDU6TGFiZWwzMzM0Mzk0MjI4",
      "url": "https://api.github.com/repos/foundry-rs/foundry/labels/T-bug",
      "name": "T-bug",
      "color": "d73a4a",
      "default": false,
      "description": "Type: bug"
    }
  ],
  "state": "open",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 5,
  "created_at": "2024-01-24T17:24:25Z",
  "updated_at": "2024-01-25T14:01:01Z",
  "closed_at": null,
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "### Component\n\nForge\n\n### Have you ensured that all of these are up to date?\n\n- [ ] Foundry\n- [ ] Foundryup\n\n### What version of Foundry are you on?\n\nforge 0.2.0 (0f20cc6 2024-01-03T21:03:37.351917000Z)\n\n### What command(s) is the bug in?\n\nforge verify-contract\n\n### Operating System\n\nmacOS (Apple Silicon)\n\n### Describe the bug\n\nHi, I got `expected value at line 1 column 1` when I verified the smart contract on Sepolia etherscan. This is the command.\r\n```\r\nforge verify-contract [ADDRESS][CONTRACE_NAME] --watch --chain sepolia --constructor-args [ARG]\r\nError: \r\nexpected value at line 1 column 1\r\n```",
  "closed_by": null,
  "reactions": {
    "url": "https://api.github.com/repos/foundry-rs/foundry/issues/6892/reactions",
    "total_count": 1,
    "+1": 1,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/foundry-rs/foundry/issues/6892/timeline",
  "performed_via_github_app": null,
  "state_reason": null
}
[
  {
    "url": "https://api.github.com/repos/foundry-rs/foundry/issues/comments/1908656766",
    "html_url": "https://github.com/foundry-rs/foundry/issues/6892#issuecomment-1908656766",
    "issue_url": "https://api.github.com/repos/foundry-rs/foundry/issues/6892",
    "id": 1908656766,
    "node_id": "IC_kwDOGBlvNc5xw8p-",
    "user": {
      "login": "0xpApaSmURf",
      "id": 89014495,
      "node_id": "MDQ6VXNlcjg5MDE0NDk1",
      "avatar_url": "https://avatars.githubusercontent.com/u/89014495?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/0xpApaSmURf",
      "html_url": "https://github.com/0xpApaSmURf",
      "followers_url": "https://api.github.com/users/0xpApaSmURf/followers",
      "following_url": "https://api.github.com/users/0xpApaSmURf/following{/other_user}",
      "gists_url": "https://api.github.com/users/0xpApaSmURf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/0xpApaSmURf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/0xpApaSmURf/subscriptions",
      "organizations_url": "https://api.github.com/users/0xpApaSmURf/orgs",
      "repos_url": "https://api.github.com/users/0xpApaSmURf/repos",
      "events_url": "https://api.github.com/users/0xpApaSmURf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/0xpApaSmURf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2024-01-24T18:02:04Z",
    "updated_at": "2024-01-24T18:02:04Z",
    "author_association": "NONE",
    "body": "Also having this problem. This seems to be a recent problem as I was able to verify a few days ago. Possible the etherscan API has changed?",
    "reactions": {
      "url": "https://api.github.com/repos/foundry-rs/foundry/issues/comments/1908656766/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/foundry-rs/foundry/issues/comments/1908776332",
    "html_url": "https://github.com/foundry-rs/foundry/issues/6892#issuecomment-1908776332",
    "issue_url": "https://api.github.com/repos/foundry-rs/foundry/issues/6892",
    "id": 1908776332,
    "node_id": "IC_kwDOGBlvNc5xxZ2M",
    "user": {
      "login": "kingster-will",
      "id": 83567446,
      "node_id": "MDQ6VXNlcjgzNTY3NDQ2",
      "avatar_url": "https://avatars.githubusercontent.com/u/83567446?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kingster-will",
      "html_url": "https://github.com/kingster-will",
      "followers_url": "https://api.github.com/users/kingster-will/followers",
      "following_url": "https://api.github.com/users/kingster-will/following{/other_user}",
      "gists_url": "https://api.github.com/users/kingster-will/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kingster-will/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kingster-will/subscriptions",
      "organizations_url": "https://api.github.com/users/kingster-will/orgs",
      "repos_url": "https://api.github.com/users/kingster-will/repos",
      "events_url": "https://api.github.com/users/kingster-will/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kingster-will/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2024-01-24T19:24:41Z",
    "updated_at": "2024-01-24T19:24:41Z",
    "author_association": "NONE",
    "body": "Hit the same issue, it works this Monday.\r\n```\r\nforge verify-contract \\\r\n    --chain-id 11155111 \\\r\n    --num-of-optimizations 20000 \\\r\n    --watch \\\r\n    --etherscan-api-key <API KEY> \\\r\n    --compiler-version 0.8.23 \\\r\n    <smart contract address> \\\r\n    ./SmartContract.sol:SmartContract\r\n    \r\n    \r\nError:\r\nexpected value at line 1 column 1\r\n```\r\n\r\n",
    "reactions": {
      "url": "https://api.github.com/repos/foundry-rs/foundry/issues/comments/1908776332/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/foundry-rs/foundry/issues/comments/1908794032",
    "html_url": "https://github.com/foundry-rs/foundry/issues/6892#issuecomment-1908794032",
    "issue_url": "https://api.github.com/repos/foundry-rs/foundry/issues/6892",
    "id": 1908794032,
    "node_id": "IC_kwDOGBlvNc5xxeKw",
    "user": {
      "login": "jdubpark",
      "id": 21009231,
      "node_id": "MDQ6VXNlcjIxMDA5MjMx",
      "avatar_url": "https://avatars.githubusercontent.com/u/21009231?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jdubpark",
      "html_url": "https://github.com/jdubpark",
      "followers_url": "https://api.github.com/users/jdubpark/followers",
      "following_url": "https://api.github.com/users/jdubpark/following{/other_user}",
      "gists_url": "https://api.github.com/users/jdubpark/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jdubpark/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jdubpark/subscriptions",
      "organizations_url": "https://api.github.com/users/jdubpark/orgs",
      "repos_url": "https://api.github.com/users/jdubpark/repos",
      "events_url": "https://api.github.com/users/jdubpark/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jdubpark/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2024-01-24T19:37:08Z",
    "updated_at": "2024-01-24T19:37:08Z",
    "author_association": "NONE",
    "body": "Pretty sure the internal Etherscan API for Sepolia has changed or is faulty â€” it had some maintenance yesterday and through this morning. I've tested on Etherscan Goerli, which works fine.",
    "reactions": {
      "url": "https://api.github.com/repos/foundry-rs/foundry/issues/comments/1908794032/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/foundry-rs/foundry/issues/comments/1909857562",
    "html_url": "https://github.com/foundry-rs/foundry/issues/6892#issuecomment-1909857562",
    "issue_url": "https://api.github.com/repos/foundry-rs/foundry/issues/6892",
    "id": 1909857562,
    "node_id": "IC_kwDOGBlvNc5x1h0a",
    "user": {
      "login": "0xpApaSmURf",
      "id": 89014495,
      "node_id": "MDQ6VXNlcjg5MDE0NDk1",
      "avatar_url": "https://avatars.githubusercontent.com/u/89014495?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/0xpApaSmURf",
      "html_url": "https://github.com/0xpApaSmURf",
      "followers_url": "https://api.github.com/users/0xpApaSmURf/followers",
      "following_url": "https://api.github.com/users/0xpApaSmURf/following{/other_user}",
      "gists_url": "https://api.github.com/users/0xpApaSmURf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/0xpApaSmURf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/0xpApaSmURf/subscriptions",
      "organizations_url": "https://api.github.com/users/0xpApaSmURf/orgs",
      "repos_url": "https://api.github.com/users/0xpApaSmURf/repos",
      "events_url": "https://api.github.com/users/0xpApaSmURf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/0xpApaSmURf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2024-01-25T10:30:56Z",
    "updated_at": "2024-01-25T10:30:56Z",
    "author_association": "NONE",
    "body": "Seems to work now, maybe the etherscan API is fixed?",
    "reactions": {
      "url": "https://api.github.com/repos/foundry-rs/foundry/issues/comments/1909857562/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/foundry-rs/foundry/issues/comments/1910276419",
    "html_url": "https://github.com/foundry-rs/foundry/issues/6892#issuecomment-1910276419",
    "issue_url": "https://api.github.com/repos/foundry-rs/foundry/issues/6892",
    "id": 1910276419,
    "node_id": "IC_kwDOGBlvNc5x3IFD",
    "user": {
      "login": "Evalir",
      "id": 26014927,
      "node_id": "MDQ6VXNlcjI2MDE0OTI3",
      "avatar_url": "https://avatars.githubusercontent.com/u/26014927?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Evalir",
      "html_url": "https://github.com/Evalir",
      "followers_url": "https://api.github.com/users/Evalir/followers",
      "following_url": "https://api.github.com/users/Evalir/following{/other_user}",
      "gists_url": "https://api.github.com/users/Evalir/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Evalir/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Evalir/subscriptions",
      "organizations_url": "https://api.github.com/users/Evalir/orgs",
      "repos_url": "https://api.github.com/users/Evalir/repos",
      "events_url": "https://api.github.com/users/Evalir/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Evalir/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2024-01-25T14:00:59Z",
    "updated_at": "2024-01-25T14:00:59Z",
    "author_association": "MEMBER",
    "body": "Could everybody else confirm if it works now? This does seem like an etherscan specific issue.",
    "reactions": {
      "url": "https://api.github.com/repos/foundry-rs/foundry/issues/comments/1910276419/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  }
]
