{
  "url": "https://api.github.com/repos/status-im/status-desktop/issues/10819",
  "repository_url": "https://api.github.com/repos/status-im/status-desktop",
  "labels_url": "https://api.github.com/repos/status-im/status-desktop/issues/10819/labels{/name}",
  "comments_url": "https://api.github.com/repos/status-im/status-desktop/issues/10819/comments",
  "events_url": "https://api.github.com/repos/status-im/status-desktop/issues/10819/events",
  "html_url": "https://github.com/status-im/status-desktop/issues/10819",
  "id": 1727232519,
  "node_id": "I_kwDOD5KrTM5m83oH",
  "number": 10819,
  "title": "Onboarding: wrong screen when logging in with incorrect password",
  "user": {
    "login": "anastasiyaig",
    "id": 82375995,
    "node_id": "MDQ6VXNlcjgyMzc1OTk1",
    "avatar_url": "https://avatars.githubusercontent.com/u/82375995?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/anastasiyaig",
    "html_url": "https://github.com/anastasiyaig",
    "followers_url": "https://api.github.com/users/anastasiyaig/followers",
    "following_url": "https://api.github.com/users/anastasiyaig/following{/other_user}",
    "gists_url": "https://api.github.com/users/anastasiyaig/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/anastasiyaig/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/anastasiyaig/subscriptions",
    "organizations_url": "https://api.github.com/users/anastasiyaig/orgs",
    "repos_url": "https://api.github.com/users/anastasiyaig/repos",
    "events_url": "https://api.github.com/users/anastasiyaig/events{/privacy}",
    "received_events_url": "https://api.github.com/users/anastasiyaig/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [
    {
      "id": 2036563458,
      "node_id": "MDU6TGFiZWwyMDM2NTYzNDU4",
      "url": "https://api.github.com/repos/status-im/status-desktop/labels/bug",
      "name": "bug",
      "color": "d73a4a",
      "default": true,
      "description": "Something isn't working"
    },
    {
      "id": 2331339531,
      "node_id": "MDU6TGFiZWwyMzMxMzM5NTMx",
      "url": "https://api.github.com/repos/status-im/status-desktop/labels/wallet-team",
      "name": "wallet-team",
      "color": "b60205",
      "default": false,
      "description": ""
    },
    {
      "id": 2443961659,
      "node_id": "MDU6TGFiZWwyNDQzOTYxNjU5",
      "url": "https://api.github.com/repos/status-im/status-desktop/labels/onboarding",
      "name": "onboarding",
      "color": "f2d42b",
      "default": false,
      "description": ""
    },
    {
      "id": 3904302702,
      "node_id": "LA_kwDOD5KrTM7otu5u",
      "url": "https://api.github.com/repos/status-im/status-desktop/labels/E:Bugfixes",
      "name": "E:Bugfixes",
      "color": "11DEC5",
      "default": false,
      "description": ""
    }
  ],
  "state": "closed",
  "locked": false,
  "assignee": {
    "login": "saledjenic",
    "id": 86303051,
    "node_id": "MDQ6VXNlcjg2MzAzMDUx",
    "avatar_url": "https://avatars.githubusercontent.com/u/86303051?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/saledjenic",
    "html_url": "https://github.com/saledjenic",
    "followers_url": "https://api.github.com/users/saledjenic/followers",
    "following_url": "https://api.github.com/users/saledjenic/following{/other_user}",
    "gists_url": "https://api.github.com/users/saledjenic/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/saledjenic/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/saledjenic/subscriptions",
    "organizations_url": "https://api.github.com/users/saledjenic/orgs",
    "repos_url": "https://api.github.com/users/saledjenic/repos",
    "events_url": "https://api.github.com/users/saledjenic/events{/privacy}",
    "received_events_url": "https://api.github.com/users/saledjenic/received_events",
    "type": "User",
    "site_admin": false
  },
  "assignees": [
    {
      "login": "saledjenic",
      "id": 86303051,
      "node_id": "MDQ6VXNlcjg2MzAzMDUx",
      "avatar_url": "https://avatars.githubusercontent.com/u/86303051?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/saledjenic",
      "html_url": "https://github.com/saledjenic",
      "followers_url": "https://api.github.com/users/saledjenic/followers",
      "following_url": "https://api.github.com/users/saledjenic/following{/other_user}",
      "gists_url": "https://api.github.com/users/saledjenic/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/saledjenic/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/saledjenic/subscriptions",
      "organizations_url": "https://api.github.com/users/saledjenic/orgs",
      "repos_url": "https://api.github.com/users/saledjenic/repos",
      "events_url": "https://api.github.com/users/saledjenic/events{/privacy}",
      "received_events_url": "https://api.github.com/users/saledjenic/received_events",
      "type": "User",
      "site_admin": false
    }
  ],
  "milestone": {
    "url": "https://api.github.com/repos/status-im/status-desktop/milestones/64",
    "html_url": "https://github.com/status-im/status-desktop/milestone/64",
    "labels_url": "https://api.github.com/repos/status-im/status-desktop/milestones/64/labels",
    "id": 9039503,
    "node_id": "MI_kwDOD5KrTM4Aie6P",
    "number": 64,
    "title": "0.13",
    "description": "Priorities **in priority order** for the 0.13 milestone:\r\n\r\n**1. Finish items started in 0.12**\r\n- Complete any outstanding issues related to pairing (for syncing) - Igor\r\n- Implement the 'Admin' role (issue #10114) - Mykhailo\r\n- Any remaining work to pay off tech. debt related to mutual contacts - Mishka\r\n- When creating/editing token based permission, ability to search for and selecting Collectables from OpenSea - MichaelC\r\n\r\n**2. Channel token permissions**\r\n- Create, edit and delete channel token permissions in the permissions admin screens\r\n- This includes the \"no tokens required to view this channel\" permission\r\n- All user facing channel token permissions functionality e.g. what happens when a user tries to access a token gated channel they don't have the required tokens to access, what happens when a user only has permissions to view a channel, etc...\r\n- If a community is an open (not token gated at the community level) community, if a channel is token gated AND if **no** \"no tokens required to view this channel\" permission for that channel exists, then the channel should be automatically encrypted.  If token gating is removed from a channel, the channel should become unencrypted.\r\n\r\n**3. DB perf improvements**\r\n- https://www.notion.so/Database-related-performance-1dbaa7ea894c461d885e55676683be07\r\n- Alex and Patryk to work on this, with help from Lukáš\r\n\r\n**4. Update app to use new 'Share URL' formats**\r\n- add functionality to status-go to generate the new 'Share URL' formats for sharing links to: User Profiles, Communities, Channel inside a Community (issue https://github.com/status-im/status-desktop/issues/10851)\r\n- Update everywhere a user can share a URL from to use the new URL format (issue https://github.com/status-im/status-desktop/issues/10852)\r\n- New/updated URL unroll designs for inside chat, including specific unrolls for the new User Profile, Community and Channel inside a Community URLs (issue https://github.com/status-im/status-desktop/issues/10585)\r\n- Ability to share a URL that points to a specific channel in a community (issue #10160)\r\n- Update all address inputs to accept a user pasting a 'share URL' into the input (in addition to being able to input the raw address).  This includes: Start new chat input, send contact request input in Settings, the import community key input, etc...\r\n- Update Status Desktops URL handler so that if Status is installed on a computer, when a user clicks on a Status 'Share URL' the app is launched (if not already running) and after signing in the user is automatically taken to the entity the Share URL represented inside the app.  e.g. if a user clicks on a URL for a Status Community, the user should be taken to the home screen for that community inside the Status App\r\n\r\n**5. Mint Assets functionality**\r\n- Also includes some small improvements to the mint Collectables functionality\r\n- Noelia, GravityBlast\r\n\r\n**6. Profile showcase backend**\r\n\r\n\r\n**--- For the Wallet team ---**\r\ntldr; continue building out Ben's wallet designs\r\n\r\n1. Complete any outstanding development related to the activity screens\r\n2. All accounts overview screens\r\n3. New settings screens\r\n4. Implement 'imported key and account' syncing and transfer between devices\r\n\r\n\r\n",
    "creator": {
      "login": "iurimatias",
      "id": 176720,
      "node_id": "MDQ6VXNlcjE3NjcyMA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/176720?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/iurimatias",
      "html_url": "https://github.com/iurimatias",
      "followers_url": "https://api.github.com/users/iurimatias/followers",
      "following_url": "https://api.github.com/users/iurimatias/following{/other_user}",
      "gists_url": "https://api.github.com/users/iurimatias/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/iurimatias/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/iurimatias/subscriptions",
      "organizations_url": "https://api.github.com/users/iurimatias/orgs",
      "repos_url": "https://api.github.com/users/iurimatias/repos",
      "events_url": "https://api.github.com/users/iurimatias/events{/privacy}",
      "received_events_url": "https://api.github.com/users/iurimatias/received_events",
      "type": "User",
      "site_admin": false
    },
    "open_issues": 108,
    "closed_issues": 139,
    "state": "open",
    "created_at": "2023-02-13T19:04:13Z",
    "updated_at": "2023-05-31T14:55:47Z",
    "due_on": "2023-06-16T07:00:00Z",
    "closed_at": null
  },
  "comments": 9,
  "created_at": "2023-05-26T09:17:47Z",
  "updated_at": "2023-05-29T13:36:19Z",
  "closed_at": "2023-05-29T13:36:19Z",
  "author_association": "CONTRIBUTOR",
  "active_lock_reason": null,
  "body": "### Description\r\n\r\n1. create basic account with password\r\n2. login\r\n3. logout\r\n4. try to login with wrong password\r\n\r\n<img width=\"1482\" alt=\"Screenshot 2023-05-26 at 12 05 31\" src=\"https://github.com/status-im/status-desktop/assets/82375995/b4679f74-694d-472e-b22a-02c2449b6795\">\r\n",
  "closed_by": {
    "login": "jrainville",
    "id": 11926403,
    "node_id": "MDQ6VXNlcjExOTI2NDAz",
    "avatar_url": "https://avatars.githubusercontent.com/u/11926403?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/jrainville",
    "html_url": "https://github.com/jrainville",
    "followers_url": "https://api.github.com/users/jrainville/followers",
    "following_url": "https://api.github.com/users/jrainville/following{/other_user}",
    "gists_url": "https://api.github.com/users/jrainville/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/jrainville/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/jrainville/subscriptions",
    "organizations_url": "https://api.github.com/users/jrainville/orgs",
    "repos_url": "https://api.github.com/users/jrainville/repos",
    "events_url": "https://api.github.com/users/jrainville/events{/privacy}",
    "received_events_url": "https://api.github.com/users/jrainville/received_events",
    "type": "User",
    "site_admin": false
  },
  "reactions": {
    "url": "https://api.github.com/repos/status-im/status-desktop/issues/10819/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/status-im/status-desktop/issues/10819/timeline",
  "performed_via_github_app": null,
  "state_reason": "completed"
}
[
  {
    "url": "https://api.github.com/repos/status-im/status-desktop/issues/comments/1564082816",
    "html_url": "https://github.com/status-im/status-desktop/issues/10819#issuecomment-1564082816",
    "issue_url": "https://api.github.com/repos/status-im/status-desktop/issues/10819",
    "id": 1564082816,
    "node_id": "IC_kwDOD5KrTM5dOgKA",
    "user": {
      "login": "caybro",
      "id": 5377645,
      "node_id": "MDQ6VXNlcjUzNzc2NDU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/5377645?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/caybro",
      "html_url": "https://github.com/caybro",
      "followers_url": "https://api.github.com/users/caybro/followers",
      "following_url": "https://api.github.com/users/caybro/following{/other_user}",
      "gists_url": "https://api.github.com/users/caybro/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/caybro/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/caybro/subscriptions",
      "organizations_url": "https://api.github.com/users/caybro/orgs",
      "repos_url": "https://api.github.com/users/caybro/repos",
      "events_url": "https://api.github.com/users/caybro/events{/privacy}",
      "received_events_url": "https://api.github.com/users/caybro/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2023-05-26T09:18:32Z",
    "updated_at": "2023-05-26T09:18:58Z",
    "author_association": "MEMBER",
    "body": "Now this might be due to the DB pool changes, wdyt @alexjba @osmaczko ",
    "reactions": {
      "url": "https://api.github.com/repos/status-im/status-desktop/issues/comments/1564082816/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/status-im/status-desktop/issues/comments/1564084598",
    "html_url": "https://github.com/status-im/status-desktop/issues/10819#issuecomment-1564084598",
    "issue_url": "https://api.github.com/repos/status-im/status-desktop/issues/10819",
    "id": 1564084598,
    "node_id": "IC_kwDOD5KrTM5dOgl2",
    "user": {
      "login": "caybro",
      "id": 5377645,
      "node_id": "MDQ6VXNlcjUzNzc2NDU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/5377645?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/caybro",
      "html_url": "https://github.com/caybro",
      "followers_url": "https://api.github.com/users/caybro/followers",
      "following_url": "https://api.github.com/users/caybro/following{/other_user}",
      "gists_url": "https://api.github.com/users/caybro/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/caybro/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/caybro/subscriptions",
      "organizations_url": "https://api.github.com/users/caybro/orgs",
      "repos_url": "https://api.github.com/users/caybro/repos",
      "events_url": "https://api.github.com/users/caybro/events{/privacy}",
      "received_events_url": "https://api.github.com/users/caybro/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2023-05-26T09:19:53Z",
    "updated_at": "2023-05-26T09:19:53Z",
    "author_association": "MEMBER",
    "body": "@anastasiyaig do you have (or have you used) the keycard when logging in?",
    "reactions": {
      "url": "https://api.github.com/repos/status-im/status-desktop/issues/comments/1564084598/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/status-im/status-desktop/issues/comments/1564086002",
    "html_url": "https://github.com/status-im/status-desktop/issues/10819#issuecomment-1564086002",
    "issue_url": "https://api.github.com/repos/status-im/status-desktop/issues/10819",
    "id": 1564086002,
    "node_id": "IC_kwDOD5KrTM5dOg7y",
    "user": {
      "login": "anastasiyaig",
      "id": 82375995,
      "node_id": "MDQ6VXNlcjgyMzc1OTk1",
      "avatar_url": "https://avatars.githubusercontent.com/u/82375995?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/anastasiyaig",
      "html_url": "https://github.com/anastasiyaig",
      "followers_url": "https://api.github.com/users/anastasiyaig/followers",
      "following_url": "https://api.github.com/users/anastasiyaig/following{/other_user}",
      "gists_url": "https://api.github.com/users/anastasiyaig/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/anastasiyaig/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/anastasiyaig/subscriptions",
      "organizations_url": "https://api.github.com/users/anastasiyaig/orgs",
      "repos_url": "https://api.github.com/users/anastasiyaig/repos",
      "events_url": "https://api.github.com/users/anastasiyaig/events{/privacy}",
      "received_events_url": "https://api.github.com/users/anastasiyaig/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2023-05-26T09:21:05Z",
    "updated_at": "2023-05-26T09:21:05Z",
    "author_association": "CONTRIBUTOR",
    "body": "@caybro it is basic account (regular non-keycard account) created with password without any stored user data (data folder is clean)",
    "reactions": {
      "url": "https://api.github.com/repos/status-im/status-desktop/issues/comments/1564086002/reactions",
      "total_count": 1,
      "+1": 1,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/status-im/status-desktop/issues/comments/1564086053",
    "html_url": "https://github.com/status-im/status-desktop/issues/10819#issuecomment-1564086053",
    "issue_url": "https://api.github.com/repos/status-im/status-desktop/issues/10819",
    "id": 1564086053,
    "node_id": "IC_kwDOD5KrTM5dOg8l",
    "user": {
      "login": "caybro",
      "id": 5377645,
      "node_id": "MDQ6VXNlcjUzNzc2NDU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/5377645?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/caybro",
      "html_url": "https://github.com/caybro",
      "followers_url": "https://api.github.com/users/caybro/followers",
      "following_url": "https://api.github.com/users/caybro/following{/other_user}",
      "gists_url": "https://api.github.com/users/caybro/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/caybro/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/caybro/subscriptions",
      "organizations_url": "https://api.github.com/users/caybro/orgs",
      "repos_url": "https://api.github.com/users/caybro/repos",
      "events_url": "https://api.github.com/users/caybro/events{/privacy}",
      "received_events_url": "https://api.github.com/users/caybro/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2023-05-26T09:21:07Z",
    "updated_at": "2023-05-26T09:22:31Z",
    "author_association": "MEMBER",
    "body": "I get a similar failure on Linux (although with a different screen); again with a wrong password; no keycard, no touch ID:\r\n\r\n![image](https://github.com/status-im/status-desktop/assets/5377645/dd37f074-470a-4698-ae9b-5517f5442f1a)\r\n",
    "reactions": {
      "url": "https://api.github.com/repos/status-im/status-desktop/issues/comments/1564086053/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/status-im/status-desktop/issues/comments/1564102252",
    "html_url": "https://github.com/status-im/status-desktop/issues/10819#issuecomment-1564102252",
    "issue_url": "https://api.github.com/repos/status-im/status-desktop/issues/10819",
    "id": 1564102252,
    "node_id": "IC_kwDOD5KrTM5dOk5s",
    "user": {
      "login": "caybro",
      "id": 5377645,
      "node_id": "MDQ6VXNlcjUzNzc2NDU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/5377645?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/caybro",
      "html_url": "https://github.com/caybro",
      "followers_url": "https://api.github.com/users/caybro/followers",
      "following_url": "https://api.github.com/users/caybro/following{/other_user}",
      "gists_url": "https://api.github.com/users/caybro/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/caybro/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/caybro/subscriptions",
      "organizations_url": "https://api.github.com/users/caybro/orgs",
      "repos_url": "https://api.github.com/users/caybro/repos",
      "events_url": "https://api.github.com/users/caybro/events{/privacy}",
      "received_events_url": "https://api.github.com/users/caybro/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2023-05-26T09:33:30Z",
    "updated_at": "2023-05-26T09:33:30Z",
    "author_association": "MEMBER",
    "body": "After this fix, we still get the wrong error message @osmaczko @alexjba:\r\n\r\n![image](https://github.com/status-im/status-desktop/assets/5377645/4fcf9838-d632-4be8-b926-2740150f132e)\r\n",
    "reactions": {
      "url": "https://api.github.com/repos/status-im/status-desktop/issues/comments/1564102252/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/status-im/status-desktop/issues/comments/1564104316",
    "html_url": "https://github.com/status-im/status-desktop/issues/10819#issuecomment-1564104316",
    "issue_url": "https://api.github.com/repos/status-im/status-desktop/issues/10819",
    "id": 1564104316,
    "node_id": "IC_kwDOD5KrTM5dOlZ8",
    "user": {
      "login": "saledjenic",
      "id": 86303051,
      "node_id": "MDQ6VXNlcjg2MzAzMDUx",
      "avatar_url": "https://avatars.githubusercontent.com/u/86303051?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/saledjenic",
      "html_url": "https://github.com/saledjenic",
      "followers_url": "https://api.github.com/users/saledjenic/followers",
      "following_url": "https://api.github.com/users/saledjenic/following{/other_user}",
      "gists_url": "https://api.github.com/users/saledjenic/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/saledjenic/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/saledjenic/subscriptions",
      "organizations_url": "https://api.github.com/users/saledjenic/orgs",
      "repos_url": "https://api.github.com/users/saledjenic/repos",
      "events_url": "https://api.github.com/users/saledjenic/events{/privacy}",
      "received_events_url": "https://api.github.com/users/saledjenic/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2023-05-26T09:35:06Z",
    "updated_at": "2023-05-26T09:35:06Z",
    "author_association": "CONTRIBUTOR",
    "body": "> After this fix, we still get the wrong error message @osmaczko @alexjba:\r\n\r\nIt was like that before I guess? I mean maybe not the same error, but also it was some db error displayed.",
    "reactions": {
      "url": "https://api.github.com/repos/status-im/status-desktop/issues/comments/1564104316/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/status-im/status-desktop/issues/comments/1564179629",
    "html_url": "https://github.com/status-im/status-desktop/issues/10819#issuecomment-1564179629",
    "issue_url": "https://api.github.com/repos/status-im/status-desktop/issues/10819",
    "id": 1564179629,
    "node_id": "IC_kwDOD5KrTM5dO3yt",
    "user": {
      "login": "alexjba",
      "id": 47811206,
      "node_id": "MDQ6VXNlcjQ3ODExMjA2",
      "avatar_url": "https://avatars.githubusercontent.com/u/47811206?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/alexjba",
      "html_url": "https://github.com/alexjba",
      "followers_url": "https://api.github.com/users/alexjba/followers",
      "following_url": "https://api.github.com/users/alexjba/following{/other_user}",
      "gists_url": "https://api.github.com/users/alexjba/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/alexjba/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/alexjba/subscriptions",
      "organizations_url": "https://api.github.com/users/alexjba/orgs",
      "repos_url": "https://api.github.com/users/alexjba/repos",
      "events_url": "https://api.github.com/users/alexjba/events{/privacy}",
      "received_events_url": "https://api.github.com/users/alexjba/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2023-05-26T10:30:48Z",
    "updated_at": "2023-05-26T10:30:48Z",
    "author_association": "CONTRIBUTOR",
    "body": "> After this fix, we still get the wrong error message @osmaczko @alexjba:\r\n> \r\n> ![image](https://user-images.githubusercontent.com/5377645/241180498-4fcf9838-d632-4be8-b926-2740150f132e.png)\r\n\r\n<img width=\"1422\" alt=\"Screenshot 2023-05-26 at 13 20 20\" src=\"https://github.com/status-im/status-desktop/assets/47811206/48dc6484-1f7b-45b9-ae62-6fd70bc715d8\">\r\n\r\n^This is what we've had before. \r\n\r\nWe have new error messages now since the DB pool implementation. Looks like we're expecting this specific error in order to show the appropriate wrong password message in the UI:\r\n```\r\nif (error === \"file is not a database\") {\r\n```",
    "reactions": {
      "url": "https://api.github.com/repos/status-im/status-desktop/issues/comments/1564179629/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/status-im/status-desktop/issues/comments/1564316434",
    "html_url": "https://github.com/status-im/status-desktop/issues/10819#issuecomment-1564316434",
    "issue_url": "https://api.github.com/repos/status-im/status-desktop/issues/10819",
    "id": 1564316434,
    "node_id": "IC_kwDOD5KrTM5dPZMS",
    "user": {
      "login": "osmaczko",
      "id": 33099791,
      "node_id": "MDQ6VXNlcjMzMDk5Nzkx",
      "avatar_url": "https://avatars.githubusercontent.com/u/33099791?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/osmaczko",
      "html_url": "https://github.com/osmaczko",
      "followers_url": "https://api.github.com/users/osmaczko/followers",
      "following_url": "https://api.github.com/users/osmaczko/following{/other_user}",
      "gists_url": "https://api.github.com/users/osmaczko/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/osmaczko/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/osmaczko/subscriptions",
      "organizations_url": "https://api.github.com/users/osmaczko/orgs",
      "repos_url": "https://api.github.com/users/osmaczko/repos",
      "events_url": "https://api.github.com/users/osmaczko/events{/privacy}",
      "received_events_url": "https://api.github.com/users/osmaczko/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2023-05-26T12:26:46Z",
    "updated_at": "2023-05-26T12:26:46Z",
    "author_association": "CONTRIBUTOR",
    "body": "> Looks like we're expecting this specific error in order to show the appropriate wrong password message in the UI:\r\n\r\n```\r\nif (error === \"file is not a database\") {\r\n```\r\n\r\n:man_facepalming: principle of least surprise, you change the error string and then feature stops working. I will fix.",
    "reactions": {
      "url": "https://api.github.com/repos/status-im/status-desktop/issues/comments/1564316434/reactions",
      "total_count": 2,
      "+1": 2,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/status-im/status-desktop/issues/comments/1564321478",
    "html_url": "https://github.com/status-im/status-desktop/issues/10819#issuecomment-1564321478",
    "issue_url": "https://api.github.com/repos/status-im/status-desktop/issues/10819",
    "id": 1564321478,
    "node_id": "IC_kwDOD5KrTM5dPabG",
    "user": {
      "login": "caybro",
      "id": 5377645,
      "node_id": "MDQ6VXNlcjUzNzc2NDU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/5377645?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/caybro",
      "html_url": "https://github.com/caybro",
      "followers_url": "https://api.github.com/users/caybro/followers",
      "following_url": "https://api.github.com/users/caybro/following{/other_user}",
      "gists_url": "https://api.github.com/users/caybro/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/caybro/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/caybro/subscriptions",
      "organizations_url": "https://api.github.com/users/caybro/orgs",
      "repos_url": "https://api.github.com/users/caybro/repos",
      "events_url": "https://api.github.com/users/caybro/events{/privacy}",
      "received_events_url": "https://api.github.com/users/caybro/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2023-05-26T12:31:36Z",
    "updated_at": "2023-05-26T12:31:36Z",
    "author_association": "MEMBER",
    "body": "> > Looks like we're expecting this specific error in order to show the appropriate wrong password message in the UI:\r\n> \r\n> ```\r\n> if (error === \"file is not a database\") {\r\n> ```\r\n> \r\n> man_facepalming principle of least surprise, you change the error string and then feature stops working. I will fix.\r\n\r\nWell we now have several different error strings :)",
    "reactions": {
      "url": "https://api.github.com/repos/status-im/status-desktop/issues/comments/1564321478/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  }
]
