{
  "url": "https://api.github.com/repos/status-im/status-desktop/issues/4173",
  "repository_url": "https://api.github.com/repos/status-im/status-desktop",
  "labels_url": "https://api.github.com/repos/status-im/status-desktop/issues/4173/labels{/name}",
  "comments_url": "https://api.github.com/repos/status-im/status-desktop/issues/4173/comments",
  "events_url": "https://api.github.com/repos/status-im/status-desktop/issues/4173/events",
  "html_url": "https://github.com/status-im/status-desktop/issues/4173",
  "id": 1063440627,
  "node_id": "I_kwDOD5KrTM4_YtDz",
  "number": 4173,
  "title": "Setting local nickname of contact crashes application",
  "user": {
    "login": "0x-r4bbit",
    "id": 445106,
    "node_id": "MDQ6VXNlcjQ0NTEwNg==",
    "avatar_url": "https://avatars.githubusercontent.com/u/445106?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/0x-r4bbit",
    "html_url": "https://github.com/0x-r4bbit",
    "followers_url": "https://api.github.com/users/0x-r4bbit/followers",
    "following_url": "https://api.github.com/users/0x-r4bbit/following{/other_user}",
    "gists_url": "https://api.github.com/users/0x-r4bbit/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/0x-r4bbit/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/0x-r4bbit/subscriptions",
    "organizations_url": "https://api.github.com/users/0x-r4bbit/orgs",
    "repos_url": "https://api.github.com/users/0x-r4bbit/repos",
    "events_url": "https://api.github.com/users/0x-r4bbit/events{/privacy}",
    "received_events_url": "https://api.github.com/users/0x-r4bbit/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [
    {
      "id": 2036563458,
      "node_id": "MDU6TGFiZWwyMDM2NTYzNDU4",
      "url": "https://api.github.com/repos/status-im/status-desktop/labels/bug",
      "name": "bug",
      "color": "d73a4a",
      "default": true,
      "description": "Something isn't working"
    },
    {
      "id": 2347576554,
      "node_id": "MDU6TGFiZWwyMzQ3NTc2NTU0",
      "url": "https://api.github.com/repos/status-im/status-desktop/labels/Profile",
      "name": "Profile",
      "color": "e8e674",
      "default": false,
      "description": ""
    },
    {
      "id": 3205510054,
      "node_id": "MDU6TGFiZWwzMjA1NTEwMDU0",
      "url": "https://api.github.com/repos/status-im/status-desktop/labels/priority%201:%20high",
      "name": "priority 1: high",
      "color": "D93F0B",
      "default": false,
      "description": "an issue that is extremely important to fix, that interferes with the majority of users, occurs ofte"
    }
  ],
  "state": "closed",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 4,
  "created_at": "2021-11-25T10:59:57Z",
  "updated_at": "2022-01-05T09:37:44Z",
  "closed_at": "2022-01-05T09:37:44Z",
  "author_association": "MEMBER",
  "active_lock_reason": null,
  "body": "# Bug Report\r\n\r\n## Description\r\n\r\nWhen trying to set the local nickname of a contact, the application crashes. The reason is the same as what's reported in https://github.com/status-im/status-desktop/issues/4171: `base_bc` uses no longer existing APIs of status-go.\r\n\r\n\r\n## Steps to reproduce\r\n\r\n1. Open profile popup of some contact\r\n2. Select nickname\r\n3. Enter nickname and hit save\r\n\r\n#### Expected behavior\r\n\r\nChanging the nickname, should reflect the change in all contact related components.\r\n\r\n#### Actual behavior\r\n\r\nThe application crashes.\r\n\r\n### Additional Information\r\n\r\n- Status desktop version: `c67384367`\r\n- Operating System: macOS Cataline (10.15.3)\r\n\r\n",
  "closed_by": {
    "login": "0x-r4bbit",
    "id": 445106,
    "node_id": "MDQ6VXNlcjQ0NTEwNg==",
    "avatar_url": "https://avatars.githubusercontent.com/u/445106?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/0x-r4bbit",
    "html_url": "https://github.com/0x-r4bbit",
    "followers_url": "https://api.github.com/users/0x-r4bbit/followers",
    "following_url": "https://api.github.com/users/0x-r4bbit/following{/other_user}",
    "gists_url": "https://api.github.com/users/0x-r4bbit/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/0x-r4bbit/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/0x-r4bbit/subscriptions",
    "organizations_url": "https://api.github.com/users/0x-r4bbit/orgs",
    "repos_url": "https://api.github.com/users/0x-r4bbit/repos",
    "events_url": "https://api.github.com/users/0x-r4bbit/events{/privacy}",
    "received_events_url": "https://api.github.com/users/0x-r4bbit/received_events",
    "type": "User",
    "site_admin": false
  },
  "reactions": {
    "url": "https://api.github.com/repos/status-im/status-desktop/issues/4173/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/status-im/status-desktop/issues/4173/timeline",
  "performed_via_github_app": null,
  "state_reason": "completed"
}
[
  {
    "url": "https://api.github.com/repos/status-im/status-desktop/issues/comments/981513960",
    "html_url": "https://github.com/status-im/status-desktop/issues/4173#issuecomment-981513960",
    "issue_url": "https://api.github.com/repos/status-im/status-desktop/issues/4173",
    "id": 981513960,
    "node_id": "IC_kwDOD5KrTM46gLbo",
    "user": {
      "login": "Khushboo-dev-cpp",
      "id": 60327365,
      "node_id": "MDQ6VXNlcjYwMzI3MzY1",
      "avatar_url": "https://avatars.githubusercontent.com/u/60327365?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Khushboo-dev-cpp",
      "html_url": "https://github.com/Khushboo-dev-cpp",
      "followers_url": "https://api.github.com/users/Khushboo-dev-cpp/followers",
      "following_url": "https://api.github.com/users/Khushboo-dev-cpp/following{/other_user}",
      "gists_url": "https://api.github.com/users/Khushboo-dev-cpp/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Khushboo-dev-cpp/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Khushboo-dev-cpp/subscriptions",
      "organizations_url": "https://api.github.com/users/Khushboo-dev-cpp/orgs",
      "repos_url": "https://api.github.com/users/Khushboo-dev-cpp/repos",
      "events_url": "https://api.github.com/users/Khushboo-dev-cpp/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Khushboo-dev-cpp/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2021-11-29T10:44:15Z",
    "updated_at": "2021-11-29T10:45:11Z",
    "author_association": "CONTRIBUTOR",
    "body": "Can see this is in the log  2021-11-29 11:43:36.888+01:00 NewBE_callPrivateRPC                       topics=\"rpc\" tid=166315 file=core.nim:24 rpc_method=wakuext_saveContact\nERR 2021-11-29 11:43:36.890+01:00 rpc response error                         topics=\"rpc\" tid=166315 file=core.nim:34 err=\"\\nstatus-go error [methodName:wakuext_saveContact, code:-32601, message:the method wakuext_saveContact does not exist/is not available ]\\n\"\n\n\nSame route cause as https://github.com/status-im/status-desktop/issues/4171.",
    "reactions": {
      "url": "https://api.github.com/repos/status-im/status-desktop/issues/comments/981513960/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/status-im/status-desktop/issues/comments/981587303",
    "html_url": "https://github.com/status-im/status-desktop/issues/4173#issuecomment-981587303",
    "issue_url": "https://api.github.com/repos/status-im/status-desktop/issues/4173",
    "id": 981587303,
    "node_id": "IC_kwDOD5KrTM46gdVn",
    "user": {
      "login": "0x-r4bbit",
      "id": 445106,
      "node_id": "MDQ6VXNlcjQ0NTEwNg==",
      "avatar_url": "https://avatars.githubusercontent.com/u/445106?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/0x-r4bbit",
      "html_url": "https://github.com/0x-r4bbit",
      "followers_url": "https://api.github.com/users/0x-r4bbit/followers",
      "following_url": "https://api.github.com/users/0x-r4bbit/following{/other_user}",
      "gists_url": "https://api.github.com/users/0x-r4bbit/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/0x-r4bbit/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/0x-r4bbit/subscriptions",
      "organizations_url": "https://api.github.com/users/0x-r4bbit/orgs",
      "repos_url": "https://api.github.com/users/0x-r4bbit/repos",
      "events_url": "https://api.github.com/users/0x-r4bbit/events{/privacy}",
      "received_events_url": "https://api.github.com/users/0x-r4bbit/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2021-11-29T12:24:57Z",
    "updated_at": "2021-11-29T12:24:57Z",
    "author_association": "MEMBER",
    "body": "> When trying to set the local nickname of a contact, the application crashes. The reason is the same as what's reported in #4171: base_bc uses no longer existing APIs of status-go.\r\n\r\nYeap! Rebasing `base_bc` on top of latest `master` should fix all of this again",
    "reactions": {
      "url": "https://api.github.com/repos/status-im/status-desktop/issues/comments/981587303/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/status-im/status-desktop/issues/comments/997763306",
    "html_url": "https://github.com/status-im/status-desktop/issues/4173#issuecomment-997763306",
    "issue_url": "https://api.github.com/repos/status-im/status-desktop/issues/4173",
    "id": 997763306,
    "node_id": "IC_kwDOD5KrTM47eKjq",
    "user": {
      "login": "anastasiyaig",
      "id": 82375995,
      "node_id": "MDQ6VXNlcjgyMzc1OTk1",
      "avatar_url": "https://avatars.githubusercontent.com/u/82375995?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/anastasiyaig",
      "html_url": "https://github.com/anastasiyaig",
      "followers_url": "https://api.github.com/users/anastasiyaig/followers",
      "following_url": "https://api.github.com/users/anastasiyaig/following{/other_user}",
      "gists_url": "https://api.github.com/users/anastasiyaig/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/anastasiyaig/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/anastasiyaig/subscriptions",
      "organizations_url": "https://api.github.com/users/anastasiyaig/orgs",
      "repos_url": "https://api.github.com/users/anastasiyaig/repos",
      "events_url": "https://api.github.com/users/anastasiyaig/events{/privacy}",
      "received_events_url": "https://api.github.com/users/anastasiyaig/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2021-12-20T09:47:33Z",
    "updated_at": "2021-12-20T09:47:33Z",
    "author_association": "CONTRIBUTOR",
    "body": "it happens in master as well, i reproduced it in `d639219b940b0eb665f89b617bb07713e57e7a11` commit (master from Dec 20,2021)",
    "reactions": {
      "url": "https://api.github.com/repos/status-im/status-desktop/issues/comments/997763306/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/status-im/status-desktop/issues/comments/998716228",
    "html_url": "https://github.com/status-im/status-desktop/issues/4173#issuecomment-998716228",
    "issue_url": "https://api.github.com/repos/status-im/status-desktop/issues/4173",
    "id": 998716228,
    "node_id": "IC_kwDOD5KrTM47hzNE",
    "user": {
      "login": "0x-r4bbit",
      "id": 445106,
      "node_id": "MDQ6VXNlcjQ0NTEwNg==",
      "avatar_url": "https://avatars.githubusercontent.com/u/445106?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/0x-r4bbit",
      "html_url": "https://github.com/0x-r4bbit",
      "followers_url": "https://api.github.com/users/0x-r4bbit/followers",
      "following_url": "https://api.github.com/users/0x-r4bbit/following{/other_user}",
      "gists_url": "https://api.github.com/users/0x-r4bbit/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/0x-r4bbit/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/0x-r4bbit/subscriptions",
      "organizations_url": "https://api.github.com/users/0x-r4bbit/orgs",
      "repos_url": "https://api.github.com/users/0x-r4bbit/repos",
      "events_url": "https://api.github.com/users/0x-r4bbit/events{/privacy}",
      "received_events_url": "https://api.github.com/users/0x-r4bbit/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2021-12-21T11:52:13Z",
    "updated_at": "2021-12-21T11:52:13Z",
    "author_association": "MEMBER",
    "body": "@anastasiyaig Can confirm that this breaks in latest `master`. But this is new and now breaks with a different error.\r\n\r\nLooking into this now..",
    "reactions": {
      "url": "https://api.github.com/repos/status-im/status-desktop/issues/comments/998716228/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  }
]
